/**
 * Authoritative source catalogue.
 *
 * GOVERNANCE RULE (see docs/GOVERNANCE.md): entries in this file represent
 * *source* material — regulatory requirements and framework guidance. The
 * platform never generates entries here; the generation engine may only
 * reference them. Every record is stamped `source_status: 'reference'`,
 * meaning the identifier and title are reproduced as reference metadata for
 * mapping purposes and must be verified against the official publication
 * before being relied upon for audit or regulatory attestation. Customers
 * replace these with `user_imported` records from their licensed copies.
 */

export const FRAMEWORKS = [
  {
    code: 'NCA-ECC',
    name: 'NCA Essential Cybersecurity Controls (ECC-1:2018)',
    publisher: 'National Cybersecurity Authority (Saudi Arabia)',
    version: 'ECC-1:2018',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description:
      'Minimum cybersecurity requirements for national organisations, structured in five main domains, 29 subdomains and 114 controls.',
    // The count the publisher states, recorded so that catalogue coverage can
    // be reported against it rather than implied. Reference metadata like the
    // identifiers themselves: verify against the official publication.
    publishedControls: 114,
    // ECC numbers its controls at the third and fourth levels; the first two are
    // domains and subdomains, so counting those would overstate what is held.
    controlLevels: [3, 4],
    provenance: 'regulatory_requirement'
  },
  {
    code: 'NCA-CSCC',
    name: 'NCA Critical Systems Cybersecurity Controls (CSCC-1:2019)',
    publisher: 'National Cybersecurity Authority (Saudi Arabia)',
    version: 'CSCC-1:2019',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description:
      'Additional controls applicable to systems whose failure would have a significant national impact. Applied on top of the ECC.',
    provenance: 'regulatory_requirement'
  },
  {
    code: 'NCA-DCC',
    name: 'NCA Data Cybersecurity Controls (DCC-1:2022)',
    publisher: 'National Cybersecurity Authority (Saudi Arabia)',
    version: 'DCC-1:2022',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description:
      'Cybersecurity controls for the protection of data across its lifecycle, aligned to data classification levels.',
    provenance: 'regulatory_requirement'
  },
  {
    code: 'NCA-TCC',
    name: 'NCA Telework Cybersecurity Controls (TCC-1:2021)',
    publisher: 'National Cybersecurity Authority (Saudi Arabia)',
    version: 'TCC-1:2021',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description: 'Cybersecurity controls for remote and telework arrangements.',
    provenance: 'regulatory_requirement'
  },
  {
    code: 'NCA-CCC',
    name: 'NCA Cloud Cybersecurity Controls (CCC-1:2020)',
    publisher: 'National Cybersecurity Authority (Saudi Arabia)',
    version: 'CCC-1:2020',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description:
      'Cybersecurity controls for cloud computing, addressed separately to cloud service providers (CSP) and cloud service tenants (CST).',
    provenance: 'regulatory_requirement'
  },
  {
    code: 'SAMA-CSF',
    name: 'SAMA Cyber Security Framework',
    publisher: 'Saudi Central Bank (SAMA)',
    version: 'v1.0',
    kind: 'regulation',
    jurisdiction: 'Saudi Arabia',
    isMandatory: 1,
    description:
      'Cyber security framework for member organisations of the Saudi financial sector, organised in four domains with a defined maturity model.',
    provenance: 'regulatory_requirement'
  },
  {
    code: 'ISO-27001',
    name: 'ISO/IEC 27001:2022 — Information security management systems',
    publisher: 'ISO/IEC',
    version: '2022',
    kind: 'standard',
    jurisdiction: 'International',
    isMandatory: 0,
    description:
      'Requirements for an information security management system (Clauses 4–10) together with the Annex A reference control set of 93 controls.',
    publishedControls: 93,
    // The published count is Annex A only. The management clauses 4-10 are also
    // in this catalogue, so the comparison is restricted to the Annex A refs.
    controlPrefix: 'A.',
    provenance: 'framework_guidance'
  },
  {
    code: 'ISO-27002',
    name: 'ISO/IEC 27002:2022 — Information security controls',
    publisher: 'ISO/IEC',
    version: '2022',
    kind: 'standard',
    jurisdiction: 'International',
    isMandatory: 0,
    description:
      'Implementation guidance for the information security controls referenced by ISO/IEC 27001 Annex A.',
    provenance: 'framework_guidance'
  },
  {
    code: 'ISO-27005',
    name: 'ISO/IEC 27005:2022 — Information security risk management',
    publisher: 'ISO/IEC',
    version: '2022',
    kind: 'standard',
    jurisdiction: 'International',
    isMandatory: 0,
    description: 'Guidance on managing information security risk within an ISMS.',
    provenance: 'framework_guidance'
  },
  {
    code: 'ISO-22301',
    name: 'ISO 22301:2019 — Business continuity management systems',
    publisher: 'ISO',
    version: '2019',
    kind: 'standard',
    jurisdiction: 'International',
    isMandatory: 0,
    description: 'Requirements for a business continuity management system.',
    provenance: 'framework_guidance'
  },
  {
    code: 'NIST-CSF',
    name: 'NIST Cybersecurity Framework 2.0',
    publisher: 'NIST',
    version: '2.0',
    kind: 'framework',
    jurisdiction: 'United States / International',
    isMandatory: 0,
    description:
      'Outcome-based framework organised into six Functions: Govern, Identify, Protect, Detect, Respond and Recover.',
    provenance: 'framework_guidance'
  },
  {
    code: 'NIST-800-53',
    name: 'NIST SP 800-53 Rev. 5 — Security and Privacy Controls',
    publisher: 'NIST',
    version: 'Rev. 5',
    kind: 'framework',
    jurisdiction: 'United States',
    isMandatory: 0,
    description:
      'Catalogue of security and privacy controls for information systems and organisations, organised in 20 control families.',
    provenance: 'framework_guidance'
  },
  {
    code: 'CIS-V8',
    name: 'CIS Critical Security Controls v8',
    publisher: 'Center for Internet Security',
    version: 'v8',
    kind: 'benchmark',
    jurisdiction: 'International',
    isMandatory: 0,
    description:
      'Prioritised set of 18 safeguard groups for defending against the most prevalent attacks.',
    provenance: 'framework_guidance'
  },
  {
    code: 'COBIT-2019',
    name: 'COBIT 2019 — Governance and management objectives',
    publisher: 'ISACA',
    version: '2019',
    kind: 'framework',
    jurisdiction: 'International',
    isMandatory: 0,
    description:
      'Governance framework for enterprise information and technology, comprising 40 governance and management objectives.',
    provenance: 'framework_guidance'
  }
];

/**
 * Requirement entries. `d` is the AutGRC domain key used for auto-mapping.
 * Tuple shape: [ref, title, domainKey, level, parentRef?]
 */
export const REQUIREMENTS = {
  'NCA-ECC': [
    ['1', 'Cybersecurity Governance', 'governance', 1],
    ['1-1', 'Cybersecurity Strategy', 'governance', 2, '1'],
    ['1-2', 'Cybersecurity Management', 'governance', 2, '1'],
    ['1-3', 'Cybersecurity Policies and Procedures', 'governance', 2, '1'],
    ['1-3-1', 'Cybersecurity policies and procedures shall be defined, documented and approved', 'governance', 3, '1-3'],
    ['1-3-2', 'Cybersecurity policies and procedures shall be implemented and supported by technical and procedural security standards', 'governance', 3, '1-3'],
    ['1-3-3', 'Cybersecurity policies and procedures shall be reviewed periodically and updated when changes occur', 'governance', 3, '1-3'],
    ['1-4', 'Cybersecurity Roles and Responsibilities', 'governance', 2, '1'],
    ['1-4-1', 'Cybersecurity organisational structure and roles shall be defined, documented and approved', 'governance', 3, '1-4'],
    ['1-4-2', 'Cybersecurity roles and responsibilities shall be assigned to the relevant stakeholders', 'governance', 3, '1-4'],
    ['1-4-3', 'Cybersecurity roles and responsibilities shall be reviewed periodically', 'governance', 3, '1-4'],
    ['1-5', 'Cybersecurity Risk Management', 'risk_management', 2, '1'],
    ['1-5-1', 'Cybersecurity risk management methodology and procedures shall be defined, documented and approved', 'risk_management', 3, '1-5'],
    ['1-5-2', 'Cybersecurity risk management methodology and procedures shall be implemented', 'risk_management', 3, '1-5'],
    ['1-5-3', 'Cybersecurity risk assessment shall be executed at least in the early stages of technology projects, before a major change and when outsourcing', 'risk_management', 3, '1-5'],
    ['1-6', 'Cybersecurity in Information Technology Projects', 'change_management', 2, '1'],
    ['1-7', 'Compliance with Cybersecurity Standards, Laws and Regulations', 'governance', 2, '1'],
    ['1-8', 'Periodical Cybersecurity Review and Audit', 'governance', 2, '1'],
    ['1-9', 'Cybersecurity in Human Resources', 'security_awareness', 2, '1'],
    ['1-10', 'Cybersecurity Awareness and Training Program', 'security_awareness', 2, '1'],

    ['2', 'Cybersecurity Defence', 'security_operations', 1],
    ['2-1', 'Asset Management', 'asset_management', 2, '2'],
    ['2-1-1', 'Cybersecurity requirements for managing information and technology assets shall be defined, documented and approved', 'asset_management', 3, '2-1'],
    ['2-1-2', 'Cybersecurity requirements for asset management shall be implemented', 'asset_management', 3, '2-1'],
    ['2-1-3', 'Acceptable use policy of information and technology assets shall be defined, documented and approved', 'asset_management', 3, '2-1'],
    ['2-1-4', 'Information and technology assets shall be classified, labelled and handled as per the related laws and regulations', 'asset_management', 3, '2-1'],
    ['2-1-5', 'Cybersecurity requirements for asset management shall be reviewed periodically', 'asset_management', 3, '2-1'],
    ['2-2', 'Identity and Access Management', 'iam', 2, '2'],
    ['2-2-1', 'Cybersecurity requirements for identity and access management shall be defined, documented and approved', 'iam', 3, '2-2'],
    ['2-2-2', 'Cybersecurity requirements for identity and access management shall be implemented', 'iam', 3, '2-2'],
    ['2-2-3', 'Cybersecurity requirements for identity and access management shall include at minimum the following', 'iam', 3, '2-2'],
    ['2-2-3-1', 'User authentication based on username and password', 'iam', 4, '2-2-3'],
    ['2-2-3-2', 'Multi-factor authentication for remote access', 'iam', 4, '2-2-3'],
    ['2-2-3-3', 'User authorisation based on identity and access control principles: Need-to-Know and Need-to-Use, Least Privilege and Segregation of Duties', 'iam', 4, '2-2-3'],
    ['2-2-3-4', 'Privileged access management', 'pam', 4, '2-2-3'],
    ['2-2-3-5', 'Periodic review of users identities and access rights', 'iam', 4, '2-2-3'],
    ['2-2-4', 'Implementation of the identity and access management cybersecurity requirements shall be reviewed periodically', 'iam', 3, '2-2'],
    ['2-3', 'Information System and Information Processing Facilities Protection', 'endpoint_security', 2, '2'],
    ['2-3-1', 'Cybersecurity requirements for protecting information systems and processing facilities shall be defined, documented and approved', 'endpoint_security', 3, '2-3'],
    ['2-3-2', 'Cybersecurity requirements for protecting information systems and processing facilities shall be implemented', 'endpoint_security', 3, '2-3'],
    ['2-3-3', 'The cybersecurity requirements shall include at minimum advanced and up-to-date malware and virus protection, restricted use of external storage media, and patch management', 'endpoint_security', 3, '2-3'],
    ['2-4', 'Email Protection', 'network_security', 2, '2'],
    ['2-5', 'Networks Security Management', 'network_security', 2, '2'],
    ['2-5-1', 'Cybersecurity requirements for network security management shall be defined, documented and approved', 'network_security', 3, '2-5'],
    ['2-5-3', 'Network security requirements shall include logical or physical segregation and segmentation of network segments, network isolation for critical systems, secure browsing and internet connectivity, and wireless network protection', 'network_security', 3, '2-5'],
    ['2-6', 'Mobile Devices Security', 'endpoint_security', 2, '2'],
    ['2-7', 'Data and Information Protection', 'data_protection', 2, '2'],
    ['2-7-1', 'Cybersecurity requirements for protecting and handling data and information shall be defined, documented and approved', 'data_protection', 3, '2-7'],
    ['2-7-2', 'Cybersecurity requirements for protecting and handling data and information shall be implemented', 'data_protection', 3, '2-7'],
    ['2-7-3', 'The cybersecurity requirements shall include data and information ownership, classification and labelling, privacy and retention', 'data_protection', 3, '2-7'],
    ['2-8', 'Cryptography', 'cryptography', 2, '2'],
    ['2-8-1', 'Cybersecurity requirements for cryptography shall be defined, documented and approved', 'cryptography', 3, '2-8'],
    ['2-8-3', 'The cryptography requirements shall include approved cryptographic solutions standards, secure key management, and encryption of data in transit and at rest as per classification', 'cryptography', 3, '2-8'],
    ['2-9', 'Backup and Recovery Management', 'backup_recovery', 2, '2'],
    ['2-9-1', 'Cybersecurity requirements for backup and recovery management shall be defined, documented and approved', 'backup_recovery', 3, '2-9'],
    ['2-9-3', 'The requirements shall include scope and coverage of backups for critical technology and information assets, ability to perform rapid recovery, and periodic tests of backup restoration', 'backup_recovery', 3, '2-9'],
    ['2-10', 'Vulnerabilities Management', 'vulnerability_management', 2, '2'],
    ['2-10-1', 'Cybersecurity requirements for technical vulnerabilities management shall be defined, documented and approved', 'vulnerability_management', 3, '2-10'],
    ['2-10-2', 'Cybersecurity requirements for technical vulnerabilities management shall be implemented', 'vulnerability_management', 3, '2-10'],
    ['2-10-3', 'The requirements shall include periodic vulnerability assessments, classification of vulnerabilities based on criticality, remediation based on classification and associated risk, and security patch management', 'vulnerability_management', 3, '2-10'],
    ['2-11', 'Penetration Testing', 'vulnerability_management', 2, '2'],
    ['2-12', 'Cybersecurity Event Logs and Monitoring Management', 'logging_monitoring', 2, '2'],
    ['2-12-1', 'Cybersecurity requirements for event logs and monitoring management shall be defined, documented and approved', 'logging_monitoring', 3, '2-12'],
    ['2-12-2', 'Cybersecurity requirements for event logs and monitoring management shall be implemented', 'logging_monitoring', 3, '2-12'],
    ['2-12-3', 'The requirements shall include activation of event logs on critical assets, event logs on remote access and privileged user accounts, monitoring of event logs, and retention of event logs', 'logging_monitoring', 3, '2-12'],
    ['2-13', 'Cybersecurity Incident and Threat Management', 'incident_management', 2, '2'],
    ['2-13-1', 'Requirements for cybersecurity incidents and threat management shall be defined, documented and approved', 'incident_management', 3, '2-13'],
    ['2-13-2', 'Requirements for cybersecurity incidents and threat management shall be implemented', 'incident_management', 3, '2-13'],
    ['2-13-3', 'The requirements shall include incident response plans and escalation procedures, incident classification, incident reporting to the NCA, and sharing incident notifications and threat intelligence', 'incident_management', 3, '2-13'],
    ['2-14', 'Physical Security', 'physical_security', 2, '2'],
    ['2-15', 'Web Application Security', 'application_security', 2, '2'],

    ['3', 'Cybersecurity Resilience', 'business_continuity', 1],
    ['3-1', 'Cybersecurity Resilience Aspects of Business Continuity Management', 'business_continuity', 2, '3'],
    ['3-1-1', 'Cybersecurity requirements for business continuity management shall be defined, documented and approved', 'business_continuity', 3, '3-1'],
    ['3-1-3', 'The requirements shall include ensuring continuity of cybersecurity systems and procedures, developing response plans for cybersecurity incidents impacting business continuity, and disaster recovery plans', 'disaster_recovery', 3, '3-1'],

    ['4', 'Third-Party and Cloud Computing Cybersecurity', 'third_party', 1],
    ['4-1', 'Third-Party Cybersecurity', 'third_party', 2, '4'],
    ['4-1-1', 'Cybersecurity requirements for contracts and agreements with third parties shall be identified, documented and approved', 'third_party', 3, '4-1'],
    ['4-1-2', 'Third-party cybersecurity requirements shall include non-disclosure clauses, secure removal or return of data upon contract termination, and communication procedures for cybersecurity incidents', 'third_party', 3, '4-1'],
    ['4-1-3', 'For outsourcing and managed services, the requirements shall include conducting a cybersecurity risk assessment and ensuring services are hosted inside the Kingdom where required', 'third_party', 3, '4-1'],
    ['4-2', 'Cloud Computing and Hosting Cybersecurity', 'cloud_security', 2, '4'],
    ['4-2-1', 'Cybersecurity requirements for cloud computing and hosting shall be defined, documented and approved', 'cloud_security', 3, '4-2'],
    ['4-2-3', 'The requirements shall include classification of data prior to hosting, return and secure deletion of data upon service termination, and location of hosting inside the Kingdom as required', 'cloud_security', 3, '4-2'],

    ['5', 'Industrial Control Systems Cybersecurity', 'security_operations', 1],
    ['5-1', 'Industrial Control Systems (ICS) Protection', 'security_operations', 2, '5']
  ],

  'NCA-CSCC': [
    ['1', 'Cybersecurity Governance (Critical Systems)', 'governance', 1],
    ['1-1', 'Cybersecurity Strategy for Critical Systems', 'governance', 2, '1'],
    ['1-2', 'Cybersecurity Risk Management for Critical Systems', 'risk_management', 2, '1'],
    ['1-3', 'Cybersecurity in Information Technology Projects for Critical Systems', 'change_management', 2, '1'],
    ['1-4', 'Periodical Cybersecurity Review and Audit for Critical Systems', 'governance', 2, '1'],
    ['1-5', 'Cybersecurity in Human Resources for Critical Systems', 'security_awareness', 2, '1'],
    ['2', 'Cybersecurity Defence (Critical Systems)', 'security_operations', 1],
    ['2-1', 'Asset Management for Critical Systems', 'asset_management', 2, '2'],
    ['2-2', 'Identity and Access Management for Critical Systems', 'iam', 2, '2'],
    ['2-3', 'Information System and Processing Facilities Protection for Critical Systems', 'endpoint_security', 2, '2'],
    ['2-4', 'Networks Security Management for Critical Systems', 'network_security', 2, '2'],
    ['2-5', 'Mobile Devices Security for Critical Systems', 'endpoint_security', 2, '2'],
    ['2-6', 'Data and Information Protection for Critical Systems', 'data_protection', 2, '2'],
    ['2-7', 'Cryptography for Critical Systems', 'cryptography', 2, '2'],
    ['2-8', 'Backup and Recovery Management for Critical Systems', 'backup_recovery', 2, '2'],
    ['2-9', 'Vulnerabilities Management for Critical Systems', 'vulnerability_management', 2, '2'],
    ['2-10', 'Penetration Testing for Critical Systems', 'vulnerability_management', 2, '2'],
    ['2-11', 'Cybersecurity Event Logs and Monitoring Management for Critical Systems', 'logging_monitoring', 2, '2'],
    ['2-12', 'Cybersecurity Incident and Threat Management for Critical Systems', 'incident_management', 2, '2'],
    ['2-13', 'Physical Security for Critical Systems', 'physical_security', 2, '2'],
    ['2-14', 'Application Security for Critical Systems', 'application_security', 2, '2'],
    ['3', 'Cybersecurity Resilience (Critical Systems)', 'business_continuity', 1],
    ['3-1', 'Cybersecurity Resilience Aspects of Business Continuity Management for Critical Systems', 'business_continuity', 2, '3'],
    ['4', 'Third-Party and Cloud Computing Cybersecurity (Critical Systems)', 'third_party', 1],
    ['4-1', 'Third-Party Cybersecurity for Critical Systems', 'third_party', 2, '4'],
    ['4-2', 'Cloud Computing and Hosting Cybersecurity for Critical Systems', 'cloud_security', 2, '4']
  ],

  'NCA-DCC': [
    ['1', 'Data Cybersecurity Governance', 'data_protection', 1],
    ['1-1', 'Data Cybersecurity Strategy and Governance', 'data_protection', 2, '1'],
    ['1-2', 'Data Cybersecurity Policies and Procedures', 'data_protection', 2, '1'],
    ['1-3', 'Data Cybersecurity Roles and Responsibilities', 'data_protection', 2, '1'],
    ['1-4', 'Data Cybersecurity Risk Management', 'risk_management', 2, '1'],
    ['2', 'Data Cybersecurity Defence', 'data_protection', 1],
    ['2-1', 'Data Classification and Labelling', 'data_protection', 2, '2'],
    ['2-2', 'Data Ownership and Custodianship', 'data_protection', 2, '2'],
    ['2-3', 'Data Access Management', 'iam', 2, '2'],
    ['2-4', 'Data Encryption and Cryptographic Protection', 'cryptography', 2, '2'],
    ['2-5', 'Data Leakage Prevention', 'data_protection', 2, '2'],
    ['2-6', 'Data Retention, Archiving and Secure Disposal', 'data_protection', 2, '2'],
    ['2-7', 'Data Transfer and Sharing', 'data_protection', 2, '2'],
    ['2-8', 'Data Backup and Recovery', 'backup_recovery', 2, '2'],
    ['2-9', 'Data Masking and De-identification in Non-Production Environments', 'data_protection', 2, '2'],
    ['3', 'Data Cybersecurity Resilience', 'business_continuity', 1],
    ['4', 'Third-Party and Cloud Data Cybersecurity', 'third_party', 1],
    ['4-1', 'Data Protection in Third-Party Engagements', 'third_party', 2, '4'],
    ['4-2', 'Data Protection in Cloud Hosting', 'cloud_security', 2, '4']
  ],

  'NCA-TCC': [
    ['1', 'Telework Cybersecurity Governance', 'governance', 1],
    ['1-1', 'Telework Cybersecurity Policy', 'governance', 2, '1'],
    ['1-2', 'Telework Cybersecurity Risk Management', 'risk_management', 2, '1'],
    ['2', 'Telework Cybersecurity Defence', 'network_security', 1],
    ['2-1', 'Identity and Access Management for Telework', 'iam', 2, '2'],
    ['2-2', 'Secure Remote Connectivity', 'network_security', 2, '2'],
    ['2-3', 'Endpoint Protection for Teleworking Devices', 'endpoint_security', 2, '2'],
    ['2-4', 'Data Protection in Telework', 'data_protection', 2, '2'],
    ['2-5', 'Event Logs and Monitoring for Telework', 'logging_monitoring', 2, '2'],
    ['2-6', 'Awareness for Teleworkers', 'security_awareness', 2, '2'],
    ['3', 'Telework Cybersecurity Resilience', 'business_continuity', 1],
    ['4', 'Third-Party Telework Cybersecurity', 'third_party', 1]
  ],

  'NCA-CCC': [
    ['1', 'Cloud Cybersecurity Governance', 'cloud_security', 1],
    ['1-1', 'Cloud Cybersecurity Strategy and Policy', 'cloud_security', 2, '1'],
    ['1-2', 'Cloud Cybersecurity Risk Management', 'risk_management', 2, '1'],
    ['1-3', 'Cloud Cybersecurity Roles and Responsibilities (Shared Responsibility)', 'cloud_security', 2, '1'],
    ['2', 'Cloud Cybersecurity Defence', 'cloud_security', 1],
    ['2-1', 'Cloud Asset Management', 'asset_management', 2, '2'],
    ['2-2', 'Identity and Access Management for Cloud Services', 'iam', 2, '2'],
    ['2-3', 'Cloud Data Protection and Classification', 'data_protection', 2, '2'],
    ['2-4', 'Cryptography and Key Management for Cloud', 'cryptography', 2, '2'],
    ['2-5', 'Cloud Network and Workload Security', 'network_security', 2, '2'],
    ['2-6', 'Cloud Event Logs, Monitoring and Incident Management', 'logging_monitoring', 2, '2'],
    ['2-7', 'Cloud Backup and Recovery', 'backup_recovery', 2, '2'],
    ['2-8', 'Cloud Vulnerability and Patch Management', 'vulnerability_management', 2, '2'],
    ['3', 'Cloud Cybersecurity Resilience', 'business_continuity', 1],
    ['4', 'Third-Party Cloud Cybersecurity', 'third_party', 1],
    ['4-1', 'Cloud Service Provider Assessment and Contracting', 'third_party', 2, '4'],
    ['4-2', 'Data Location, Return and Secure Deletion', 'cloud_security', 2, '4']
  ],

  'SAMA-CSF': [
    ['1', 'Cyber Security Leadership and Governance', 'governance', 1],
    ['1.1', 'Cyber Security Governance', 'governance', 2, '1'],
    ['1.2', 'Cyber Security Strategy', 'governance', 2, '1'],
    ['1.3', 'Cyber Security Policy', 'governance', 2, '1'],
    ['1.4', 'Cyber Security Roles and Responsibilities', 'governance', 2, '1'],
    ['1.5', 'Cyber Security in Project Management', 'change_management', 2, '1'],
    ['1.6', 'Cyber Security Awareness', 'security_awareness', 2, '1'],
    ['1.7', 'Cyber Security Training', 'security_awareness', 2, '1'],
    ['2', 'Cyber Security Risk Management and Compliance', 'risk_management', 1],
    ['2.1', 'Cyber Security Risk Management', 'risk_management', 2, '2'],
    ['2.2', 'Regulatory Compliance', 'governance', 2, '2'],
    ['2.3', 'Compliance with (inter)national industry standards', 'governance', 2, '2'],
    ['2.4', 'Cyber Security Review', 'governance', 2, '2'],
    ['2.5', 'Cyber Security Audits', 'governance', 2, '2'],
    ['3', 'Cyber Security Operations and Technology', 'security_operations', 1],
    ['3.1', 'Human Resources', 'security_awareness', 2, '3'],
    ['3.2', 'Physical Security', 'physical_security', 2, '3'],
    ['3.3', 'Asset Management', 'asset_management', 2, '3'],
    ['3.4', 'Cyber Security Architecture', 'network_security', 2, '3'],
    ['3.5', 'Identity and Access Management', 'iam', 2, '3'],
    ['3.6', 'Application Security', 'application_security', 2, '3'],
    ['3.7', 'Change Management', 'change_management', 2, '3'],
    ['3.8', 'Infrastructure Security', 'network_security', 2, '3'],
    ['3.9', 'Cryptography', 'cryptography', 2, '3'],
    ['3.10', 'Bring Your Own Device (BYOD)', 'endpoint_security', 2, '3'],
    ['3.11', 'Secure Disposal of Information Assets', 'asset_management', 2, '3'],
    ['3.12', 'Payment Systems', 'application_security', 2, '3'],
    ['3.13', 'Electronic Banking Services', 'application_security', 2, '3'],
    ['3.14', 'Cyber Security Event Management', 'logging_monitoring', 2, '3'],
    ['3.15', 'Cyber Security Incident Management', 'incident_management', 2, '3'],
    ['3.16', 'Threat Management', 'security_monitoring', 2, '3'],
    ['3.17', 'Vulnerability Management', 'vulnerability_management', 2, '3'],
    ['4', 'Third Party Cyber Security', 'third_party', 1],
    ['4.1', 'Contract and Vendor Management', 'third_party', 2, '4'],
    ['4.2', 'Outsourcing', 'third_party', 2, '4'],
    ['4.3', 'Cloud Computing', 'cloud_security', 2, '4']
  ],

  'ISO-27001': [
    ['4', 'Context of the organization', 'governance', 1],
    ['5', 'Leadership', 'governance', 1],
    ['5.2', 'Policy', 'governance', 2, '5'],
    ['5.3', 'Organizational roles, responsibilities and authorities', 'governance', 2, '5'],
    ['6', 'Planning', 'risk_management', 1],
    ['6.1.2', 'Information security risk assessment', 'risk_management', 2, '6'],
    ['6.1.3', 'Information security risk treatment', 'risk_management', 2, '6'],
    ['7', 'Support', 'governance', 1],
    ['7.2', 'Competence', 'security_awareness', 2, '7'],
    ['7.3', 'Awareness', 'security_awareness', 2, '7'],
    ['7.5', 'Documented information', 'governance', 2, '7'],
    ['8', 'Operation', 'security_operations', 1],
    ['8.2', 'Information security risk assessment (operational)', 'risk_management', 2, '8'],
    ['8.3', 'Information security risk treatment (operational)', 'risk_management', 2, '8'],
    ['9', 'Performance evaluation', 'governance', 1],
    ['9.1', 'Monitoring, measurement, analysis and evaluation', 'governance', 2, '9'],
    ['9.2', 'Internal audit', 'governance', 2, '9'],
    ['9.3', 'Management review', 'governance', 2, '9'],
    ['10', 'Improvement', 'governance', 1],
    ['A.5', 'Organizational controls', 'governance', 1],
    ['A.5.1', 'Policies for information security', 'governance', 2, 'A.5'],
    ['A.5.2', 'Information security roles and responsibilities', 'governance', 2, 'A.5'],
    ['A.5.3', 'Segregation of duties', 'governance', 2, 'A.5'],
    ['A.5.4', 'Management responsibilities', 'governance', 2, 'A.5'],
    ['A.5.5', 'Contact with authorities', 'incident_management', 2, 'A.5'],
    ['A.5.6', 'Contact with special interest groups', 'security_monitoring', 2, 'A.5'],
    ['A.5.7', 'Threat intelligence', 'security_monitoring', 2, 'A.5'],
    ['A.5.8', 'Information security in project management', 'change_management', 2, 'A.5'],
    ['A.5.9', 'Inventory of information and other associated assets', 'asset_management', 2, 'A.5'],
    ['A.5.10', 'Acceptable use of information and other associated assets', 'asset_management', 2, 'A.5'],
    ['A.5.11', 'Return of assets', 'asset_management', 2, 'A.5'],
    ['A.5.12', 'Classification of information', 'data_protection', 2, 'A.5'],
    ['A.5.13', 'Labelling of information', 'data_protection', 2, 'A.5'],
    ['A.5.14', 'Information transfer', 'data_protection', 2, 'A.5'],
    ['A.5.15', 'Access control', 'iam', 2, 'A.5'],
    ['A.5.16', 'Identity management', 'iam', 2, 'A.5'],
    ['A.5.17', 'Authentication information', 'iam', 2, 'A.5'],
    ['A.5.18', 'Access rights', 'iam', 2, 'A.5'],
    ['A.5.19', 'Information security in supplier relationships', 'third_party', 2, 'A.5'],
    ['A.5.20', 'Addressing information security within supplier agreements', 'third_party', 2, 'A.5'],
    ['A.5.21', 'Managing information security in the ICT supply chain', 'third_party', 2, 'A.5'],
    ['A.5.22', 'Monitoring, review and change management of supplier services', 'third_party', 2, 'A.5'],
    ['A.5.23', 'Information security for use of cloud services', 'cloud_security', 2, 'A.5'],
    ['A.5.24', 'Information security incident management planning and preparation', 'incident_management', 2, 'A.5'],
    ['A.5.25', 'Assessment and decision on information security events', 'incident_management', 2, 'A.5'],
    ['A.5.26', 'Response to information security incidents', 'incident_management', 2, 'A.5'],
    ['A.5.27', 'Learning from information security incidents', 'incident_management', 2, 'A.5'],
    ['A.5.28', 'Collection of evidence', 'incident_management', 2, 'A.5'],
    ['A.5.29', 'Information security during disruption', 'business_continuity', 2, 'A.5'],
    ['A.5.30', 'ICT readiness for business continuity', 'disaster_recovery', 2, 'A.5'],
    ['A.5.31', 'Legal, statutory, regulatory and contractual requirements', 'governance', 2, 'A.5'],
    ['A.5.32', 'Intellectual property rights', 'governance', 2, 'A.5'],
    ['A.5.33', 'Protection of records', 'data_protection', 2, 'A.5'],
    ['A.5.34', 'Privacy and protection of PII', 'data_protection', 2, 'A.5'],
    ['A.5.35', 'Independent review of information security', 'governance', 2, 'A.5'],
    ['A.5.36', 'Compliance with policies, rules and standards for information security', 'governance', 2, 'A.5'],
    ['A.5.37', 'Documented operating procedures', 'governance', 2, 'A.5'],
    ['A.6', 'People controls', 'security_awareness', 1],
    ['A.6.1', 'Screening', 'security_awareness', 2, 'A.6'],
    ['A.6.2', 'Terms and conditions of employment', 'security_awareness', 2, 'A.6'],
    ['A.6.3', 'Information security awareness, education and training', 'security_awareness', 2, 'A.6'],
    ['A.6.4', 'Disciplinary process', 'security_awareness', 2, 'A.6'],
    ['A.6.5', 'Responsibilities after termination or change of employment', 'security_awareness', 2, 'A.6'],
    ['A.6.6', 'Confidentiality or non-disclosure agreements', 'third_party', 2, 'A.6'],
    ['A.6.7', 'Remote working', 'endpoint_security', 2, 'A.6'],
    ['A.6.8', 'Information security event reporting', 'incident_management', 2, 'A.6'],
    ['A.7', 'Physical controls', 'physical_security', 1],
    ['A.7.1', 'Physical security perimeters', 'physical_security', 2, 'A.7'],
    ['A.7.2', 'Physical entry', 'physical_security', 2, 'A.7'],
    ['A.7.3', 'Securing offices, rooms and facilities', 'physical_security', 2, 'A.7'],
    ['A.7.4', 'Physical security monitoring', 'physical_security', 2, 'A.7'],
    ['A.7.5', 'Protecting against physical and environmental threats', 'physical_security', 2, 'A.7'],
    ['A.7.6', 'Working in secure areas', 'physical_security', 2, 'A.7'],
    ['A.7.7', 'Clear desk and clear screen', 'physical_security', 2, 'A.7'],
    ['A.7.8', 'Equipment siting and protection', 'physical_security', 2, 'A.7'],
    ['A.7.9', 'Security of assets off-premises', 'asset_management', 2, 'A.7'],
    ['A.7.10', 'Storage media', 'data_protection', 2, 'A.7'],
    ['A.7.11', 'Supporting utilities', 'physical_security', 2, 'A.7'],
    ['A.7.12', 'Cabling security', 'physical_security', 2, 'A.7'],
    ['A.7.13', 'Equipment maintenance', 'asset_management', 2, 'A.7'],
    ['A.7.14', 'Secure disposal or re-use of equipment', 'asset_management', 2, 'A.7'],
    ['A.8', 'Technological controls', 'security_operations', 1],
    ['A.8.1', 'User endpoint devices', 'endpoint_security', 2, 'A.8'],
    ['A.8.2', 'Privileged access rights', 'pam', 2, 'A.8'],
    ['A.8.3', 'Information access restriction', 'iam', 2, 'A.8'],
    ['A.8.4', 'Access to source code', 'secure_sdlc', 2, 'A.8'],
    ['A.8.5', 'Secure authentication', 'iam', 2, 'A.8'],
    ['A.8.6', 'Capacity management', 'security_operations', 2, 'A.8'],
    ['A.8.7', 'Protection against malware', 'endpoint_security', 2, 'A.8'],
    ['A.8.8', 'Management of technical vulnerabilities', 'vulnerability_management', 2, 'A.8'],
    ['A.8.9', 'Configuration management', 'change_management', 2, 'A.8'],
    ['A.8.10', 'Information deletion', 'data_protection', 2, 'A.8'],
    ['A.8.11', 'Data masking', 'data_protection', 2, 'A.8'],
    ['A.8.12', 'Data leakage prevention', 'data_protection', 2, 'A.8'],
    ['A.8.13', 'Information backup', 'backup_recovery', 2, 'A.8'],
    ['A.8.14', 'Redundancy of information processing facilities', 'disaster_recovery', 2, 'A.8'],
    ['A.8.15', 'Logging', 'logging_monitoring', 2, 'A.8'],
    ['A.8.16', 'Monitoring activities', 'security_monitoring', 2, 'A.8'],
    ['A.8.17', 'Clock synchronization', 'logging_monitoring', 2, 'A.8'],
    ['A.8.18', 'Use of privileged utility programs', 'pam', 2, 'A.8'],
    ['A.8.19', 'Installation of software on operational systems', 'change_management', 2, 'A.8'],
    ['A.8.20', 'Networks security', 'network_security', 2, 'A.8'],
    ['A.8.21', 'Security of network services', 'network_security', 2, 'A.8'],
    ['A.8.22', 'Segregation of networks', 'network_security', 2, 'A.8'],
    ['A.8.23', 'Web filtering', 'network_security', 2, 'A.8'],
    ['A.8.24', 'Use of cryptography', 'cryptography', 2, 'A.8'],
    ['A.8.25', 'Secure development life cycle', 'secure_sdlc', 2, 'A.8'],
    ['A.8.26', 'Application security requirements', 'application_security', 2, 'A.8'],
    ['A.8.27', 'Secure system architecture and engineering principles', 'secure_sdlc', 2, 'A.8'],
    ['A.8.28', 'Secure coding', 'secure_sdlc', 2, 'A.8'],
    ['A.8.29', 'Security testing in development and acceptance', 'secure_sdlc', 2, 'A.8'],
    ['A.8.30', 'Outsourced development', 'secure_sdlc', 2, 'A.8'],
    ['A.8.31', 'Separation of development, test and production environments', 'secure_sdlc', 2, 'A.8'],
    ['A.8.32', 'Change management', 'change_management', 2, 'A.8'],
    ['A.8.33', 'Test information', 'data_protection', 2, 'A.8'],
    ['A.8.34', 'Protection of information systems during audit testing', 'governance', 2, 'A.8']
  ],

  'ISO-27002': [
    ['5', 'Organizational controls — implementation guidance', 'governance', 1],
    ['6', 'People controls — implementation guidance', 'security_awareness', 1],
    ['7', 'Physical controls — implementation guidance', 'physical_security', 1],
    ['8', 'Technological controls — implementation guidance', 'security_operations', 1],
    ['8.2', 'Privileged access rights — implementation guidance', 'pam', 2, '8'],
    ['8.5', 'Secure authentication — implementation guidance', 'iam', 2, '8'],
    ['8.8', 'Management of technical vulnerabilities — implementation guidance', 'vulnerability_management', 2, '8'],
    ['8.15', 'Logging — implementation guidance', 'logging_monitoring', 2, '8'],
    ['8.24', 'Use of cryptography — implementation guidance', 'cryptography', 2, '8']
  ],

  'ISO-27005': [
    ['7', 'Information security risk assessment process', 'risk_management', 1],
    ['7.2', 'Risk identification', 'risk_management', 2, '7'],
    ['7.3', 'Risk analysis', 'risk_management', 2, '7'],
    ['7.4', 'Risk evaluation', 'risk_management', 2, '7'],
    ['8', 'Information security risk treatment process', 'risk_management', 1],
    ['10', 'Leveraging related ISMS processes', 'risk_management', 1]
  ],

  'ISO-22301': [
    ['4', 'Context of the organization', 'business_continuity', 1],
    ['5', 'Leadership', 'business_continuity', 1],
    ['6', 'Planning', 'business_continuity', 1],
    ['7', 'Support', 'business_continuity', 1],
    ['8', 'Operation', 'business_continuity', 1],
    ['8.2.2', 'Business impact analysis', 'business_continuity', 2, '8'],
    ['8.2.3', 'Risk assessment', 'risk_management', 2, '8'],
    ['8.3', 'Business continuity strategies and solutions', 'business_continuity', 2, '8'],
    ['8.4', 'Business continuity plans and procedures', 'business_continuity', 2, '8'],
    ['8.5', 'Exercise programme', 'disaster_recovery', 2, '8'],
    ['8.6', 'Evaluation of business continuity documentation and capabilities', 'business_continuity', 2, '8'],
    ['9', 'Performance evaluation', 'business_continuity', 1],
    ['10', 'Improvement', 'business_continuity', 1]
  ],

  'NIST-CSF': [
    ['GV', 'GOVERN', 'governance', 1],
    ['GV.OC', 'Organizational Context', 'governance', 2, 'GV'],
    ['GV.RM', 'Risk Management Strategy', 'risk_management', 2, 'GV'],
    ['GV.RR', 'Roles, Responsibilities, and Authorities', 'governance', 2, 'GV'],
    ['GV.RR-02', 'Roles, responsibilities, and authorities related to cybersecurity risk management are established, communicated, understood, and enforced', 'governance', 3, 'GV.RR'],
    ['GV.PO', 'Policy', 'governance', 2, 'GV'],
    ['GV.PO-01', 'Policy for managing cybersecurity risks is established based on organizational context, cybersecurity strategy, and priorities and is communicated and enforced', 'governance', 3, 'GV.PO'],
    ['GV.PO-02', 'Policy for managing cybersecurity risks is reviewed, updated, communicated, and enforced to reflect changes in requirements, threats, technology, and organizational mission', 'governance', 3, 'GV.PO'],
    ['GV.OV', 'Oversight', 'governance', 2, 'GV'],
    ['GV.SC', 'Cybersecurity Supply Chain Risk Management', 'third_party', 2, 'GV'],
    ['ID', 'IDENTIFY', 'asset_management', 1],
    ['ID.AM', 'Asset Management', 'asset_management', 2, 'ID'],
    ['ID.AM-01', 'Inventories of hardware managed by the organization are maintained', 'asset_management', 3, 'ID.AM'],
    ['ID.AM-02', 'Inventories of software, services, and systems managed by the organization are maintained', 'asset_management', 3, 'ID.AM'],
    ['ID.AM-05', 'Assets are prioritized based on classification, criticality, resources, and impact on the mission', 'asset_management', 3, 'ID.AM'],
    ['ID.RA', 'Risk Assessment', 'risk_management', 2, 'ID'],
    ['ID.RA-01', 'Vulnerabilities in assets are identified, validated, and recorded', 'vulnerability_management', 3, 'ID.RA'],
    ['ID.IM', 'Improvement', 'governance', 2, 'ID'],
    ['PR', 'PROTECT', 'security_operations', 1],
    ['PR.AA', 'Identity Management, Authentication, and Access Control', 'iam', 2, 'PR'],
    ['PR.AA-01', 'Identities and credentials for authorized users, services, and hardware are managed by the organization', 'iam', 3, 'PR.AA'],
    ['PR.AA-03', 'Users, services, and hardware are authenticated', 'iam', 3, 'PR.AA'],
    ['PR.AA-05', 'Access permissions, entitlements, and authorizations are defined in a policy, managed, enforced, and reviewed, and incorporate the principles of least privilege and separation of duties', 'iam', 3, 'PR.AA'],
    ['PR.AT', 'Awareness and Training', 'security_awareness', 2, 'PR'],
    ['PR.DS', 'Data Security', 'data_protection', 2, 'PR'],
    ['PR.DS-01', 'The confidentiality, integrity, and availability of data-at-rest are protected', 'data_protection', 3, 'PR.DS'],
    ['PR.DS-02', 'The confidentiality, integrity, and availability of data-in-transit are protected', 'data_protection', 3, 'PR.DS'],
    ['PR.DS-11', 'Backups of data are created, protected, maintained, and tested', 'backup_recovery', 3, 'PR.DS'],
    ['PR.PS', 'Platform Security', 'endpoint_security', 2, 'PR'],
    ['PR.PS-01', 'Configuration management practices are established and applied', 'change_management', 3, 'PR.PS'],
    ['PR.PS-02', 'Software is maintained, replaced, and removed commensurate with risk', 'vulnerability_management', 3, 'PR.PS'],
    ['PR.PS-04', 'Log records are generated and made available for continuous monitoring', 'logging_monitoring', 3, 'PR.PS'],
    ['PR.IR', 'Technology Infrastructure Resilience', 'network_security', 2, 'PR'],
    ['DE', 'DETECT', 'security_monitoring', 1],
    ['DE.CM', 'Continuous Monitoring', 'security_monitoring', 2, 'DE'],
    ['DE.CM-01', 'Networks and network services are monitored to find potentially adverse events', 'security_monitoring', 3, 'DE.CM'],
    ['DE.CM-03', 'Personnel activity and technology usage are monitored to find potentially adverse events', 'security_monitoring', 3, 'DE.CM'],
    ['DE.AE', 'Adverse Event Analysis', 'security_monitoring', 2, 'DE'],
    ['RS', 'RESPOND', 'incident_management', 1],
    ['RS.MA', 'Incident Management', 'incident_management', 2, 'RS'],
    ['RS.MA-01', 'The incident response plan is executed in coordination with relevant third parties once an incident is declared', 'incident_management', 3, 'RS.MA'],
    ['RS.AN', 'Incident Analysis', 'incident_management', 2, 'RS'],
    ['RS.CO', 'Incident Response Reporting and Communication', 'incident_management', 2, 'RS'],
    ['RS.MI', 'Incident Mitigation', 'incident_management', 2, 'RS'],
    ['RC', 'RECOVER', 'disaster_recovery', 1],
    ['RC.RP', 'Incident Recovery Plan Execution', 'disaster_recovery', 2, 'RC'],
    ['RC.CO', 'Incident Recovery Communication', 'disaster_recovery', 2, 'RC']
  ],

  'NIST-800-53': [
    ['AC', 'Access Control', 'iam', 1],
    ['AC-2', 'Account Management', 'iam', 2, 'AC'],
    ['AC-3', 'Access Enforcement', 'iam', 2, 'AC'],
    ['AC-5', 'Separation of Duties', 'iam', 2, 'AC'],
    ['AC-6', 'Least Privilege', 'pam', 2, 'AC'],
    ['AC-17', 'Remote Access', 'network_security', 2, 'AC'],
    ['AT', 'Awareness and Training', 'security_awareness', 1],
    ['AU', 'Audit and Accountability', 'logging_monitoring', 1],
    ['AU-2', 'Event Logging', 'logging_monitoring', 2, 'AU'],
    ['AU-6', 'Audit Record Review, Analysis, and Reporting', 'security_monitoring', 2, 'AU'],
    ['AU-11', 'Audit Record Retention', 'logging_monitoring', 2, 'AU'],
    ['CA', 'Assessment, Authorization, and Monitoring', 'governance', 1],
    ['CM', 'Configuration Management', 'change_management', 1],
    ['CM-3', 'Configuration Change Control', 'change_management', 2, 'CM'],
    ['CM-8', 'System Component Inventory', 'asset_management', 2, 'CM'],
    ['CP', 'Contingency Planning', 'business_continuity', 1],
    ['CP-9', 'System Backup', 'backup_recovery', 2, 'CP'],
    ['CP-10', 'System Recovery and Reconstitution', 'disaster_recovery', 2, 'CP'],
    ['IA', 'Identification and Authentication', 'iam', 1],
    ['IA-2', 'Identification and Authentication (Organizational Users)', 'iam', 2, 'IA'],
    ['IA-5', 'Authenticator Management', 'iam', 2, 'IA'],
    ['IR', 'Incident Response', 'incident_management', 1],
    ['IR-4', 'Incident Handling', 'incident_management', 2, 'IR'],
    ['IR-6', 'Incident Reporting', 'incident_management', 2, 'IR'],
    ['MA', 'Maintenance', 'asset_management', 1],
    ['MP', 'Media Protection', 'data_protection', 1],
    ['PE', 'Physical and Environmental Protection', 'physical_security', 1],
    ['PL', 'Planning', 'governance', 1],
    ['PM', 'Program Management', 'governance', 1],
    ['PS', 'Personnel Security', 'security_awareness', 1],
    ['PT', 'Personally Identifiable Information Processing and Transparency', 'data_protection', 1],
    ['RA', 'Risk Assessment', 'risk_management', 1],
    ['RA-5', 'Vulnerability Monitoring and Scanning', 'vulnerability_management', 2, 'RA'],
    ['SA', 'System and Services Acquisition', 'secure_sdlc', 1],
    ['SA-11', 'Developer Testing and Evaluation', 'secure_sdlc', 2, 'SA'],
    ['SC', 'System and Communications Protection', 'network_security', 1],
    ['SC-8', 'Transmission Confidentiality and Integrity', 'cryptography', 2, 'SC'],
    ['SC-13', 'Cryptographic Protection', 'cryptography', 2, 'SC'],
    ['SC-28', 'Protection of Information at Rest', 'cryptography', 2, 'SC'],
    ['SI', 'System and Information Integrity', 'endpoint_security', 1],
    ['SI-2', 'Flaw Remediation', 'vulnerability_management', 2, 'SI'],
    ['SI-4', 'System Monitoring', 'security_monitoring', 2, 'SI'],
    ['SR', 'Supply Chain Risk Management', 'third_party', 1]
  ],

  'CIS-V8': [
    ['1', 'Inventory and Control of Enterprise Assets', 'asset_management', 1],
    ['2', 'Inventory and Control of Software Assets', 'asset_management', 1],
    ['3', 'Data Protection', 'data_protection', 1],
    ['4', 'Secure Configuration of Enterprise Assets and Software', 'change_management', 1],
    ['5', 'Account Management', 'iam', 1],
    ['5.1', 'Establish and Maintain an Inventory of Accounts', 'iam', 2, '5'],
    ['5.4', 'Restrict Administrator Privileges to Dedicated Administrator Accounts', 'pam', 2, '5'],
    ['6', 'Access Control Management', 'iam', 1],
    ['6.3', 'Require MFA for Externally-Exposed Applications', 'iam', 2, '6'],
    ['6.5', 'Require MFA for Administrative Access', 'pam', 2, '6'],
    ['6.7', 'Centralize Access Control', 'iam', 2, '6'],
    ['6.8', 'Define and Maintain Role-Based Access Control', 'iam', 2, '6'],
    ['7', 'Continuous Vulnerability Management', 'vulnerability_management', 1],
    ['7.1', 'Establish and Maintain a Vulnerability Management Process', 'vulnerability_management', 2, '7'],
    ['7.5', 'Perform Automated Vulnerability Scans of Internal Enterprise Assets', 'vulnerability_management', 2, '7'],
    ['8', 'Audit Log Management', 'logging_monitoring', 1],
    ['8.2', 'Collect Audit Logs', 'logging_monitoring', 2, '8'],
    ['8.10', 'Retain Audit Logs', 'logging_monitoring', 2, '8'],
    ['9', 'Email and Web Browser Protections', 'network_security', 1],
    ['10', 'Malware Defenses', 'endpoint_security', 1],
    ['11', 'Data Recovery', 'backup_recovery', 1],
    ['11.2', 'Perform Automated Backups', 'backup_recovery', 2, '11'],
    ['11.5', 'Test Data Recovery', 'backup_recovery', 2, '11'],
    ['12', 'Network Infrastructure Management', 'network_security', 1],
    ['13', 'Network Monitoring and Defense', 'security_monitoring', 1],
    ['14', 'Security Awareness and Skills Training', 'security_awareness', 1],
    ['15', 'Service Provider Management', 'third_party', 1],
    ['16', 'Application Software Security', 'application_security', 1],
    ['17', 'Incident Response Management', 'incident_management', 1],
    ['18', 'Penetration Testing', 'vulnerability_management', 1]
  ],

  'COBIT-2019': [
    ['EDM01', 'Ensured Governance Framework Setting and Maintenance', 'governance', 1],
    ['EDM03', 'Ensured Risk Optimization', 'risk_management', 1],
    ['APO01', 'Managed I&T Management Framework', 'governance', 1],
    ['APO03', 'Managed Enterprise Architecture', 'network_security', 1],
    ['APO07', 'Managed Human Resources', 'security_awareness', 1],
    ['APO10', 'Managed Vendors', 'third_party', 1],
    ['APO12', 'Managed Risk', 'risk_management', 1],
    ['APO13', 'Managed Security', 'governance', 1],
    ['APO14', 'Managed Data', 'data_protection', 1],
    ['BAI03', 'Managed Solutions Identification and Build', 'secure_sdlc', 1],
    ['BAI06', 'Managed IT Changes', 'change_management', 1],
    ['BAI09', 'Managed Assets', 'asset_management', 1],
    ['BAI10', 'Managed Configuration', 'change_management', 1],
    ['DSS01', 'Managed Operations', 'security_operations', 1],
    ['DSS02', 'Managed Service Requests and Incidents', 'incident_management', 1],
    ['DSS03', 'Managed Problems', 'incident_management', 1],
    ['DSS04', 'Managed Continuity', 'business_continuity', 1],
    ['DSS05', 'Managed Security Services', 'security_operations', 1],
    ['DSS06', 'Managed Business Process Controls', 'governance', 1],
    ['MEA01', 'Managed Performance and Conformance Monitoring', 'governance', 1],
    ['MEA02', 'Managed System of Internal Control', 'governance', 1],
    ['MEA03', 'Managed Compliance With External Requirements', 'governance', 1],
    ['MEA04', 'Managed Assurance', 'governance', 1]
  ]
};

/**
 * Curated cross-framework equivalences, expressed as
 * [sourceFrameworkCode, sourceRef, targetFrameworkCode, targetRef, relation].
 * These drive the cross-framework mapping engine's suggestions.
 */
export const CROSSWALKS = [
  ['NCA-ECC', '2-2-3-2', 'ISO-27001', 'A.8.5', 'equivalent'],
  ['NCA-ECC', '2-2-3-2', 'NIST-CSF', 'PR.AA-03', 'equivalent'],
  ['NCA-ECC', '2-2-3-2', 'CIS-V8', '6.3', 'equivalent'],
  ['NCA-ECC', '2-2-3-2', 'NIST-800-53', 'IA-2', 'broader'],
  ['NCA-ECC', '2-2-3-4', 'ISO-27001', 'A.8.2', 'equivalent'],
  ['NCA-ECC', '2-2-3-4', 'NIST-CSF', 'PR.AA-05', 'related'],
  ['NCA-ECC', '2-2-3-4', 'CIS-V8', '6.5', 'equivalent'],
  ['NCA-ECC', '2-2-3-4', 'NIST-800-53', 'AC-6', 'equivalent'],
  ['NCA-ECC', '2-2-3-4', 'SAMA-CSF', '3.5', 'broader'],
  ['NCA-ECC', '2-2-3-3', 'ISO-27001', 'A.5.15', 'equivalent'],
  ['NCA-ECC', '2-2-3-3', 'NIST-800-53', 'AC-3', 'equivalent'],
  ['NCA-ECC', '2-2-3-3', 'ISO-27001', 'A.5.3', 'related'],
  ['NCA-ECC', '2-2-3-5', 'ISO-27001', 'A.5.18', 'equivalent'],
  ['NCA-ECC', '2-2-3-5', 'NIST-800-53', 'AC-2', 'equivalent'],
  ['NCA-ECC', '2-2-3-5', 'CIS-V8', '5.1', 'related'],
  ['NCA-ECC', '2-2-3-1', 'ISO-27001', 'A.5.17', 'equivalent'],
  ['NCA-ECC', '2-2-1', 'ISO-27001', 'A.5.16', 'equivalent'],
  ['NCA-ECC', '2-2-1', 'NIST-CSF', 'PR.AA-01', 'equivalent'],
  ['NCA-ECC', '2-2-1', 'SAMA-CSF', '3.5', 'equivalent'],
  ['NCA-ECC', '2-1-1', 'ISO-27001', 'A.5.9', 'equivalent'],
  ['NCA-ECC', '2-1-1', 'NIST-CSF', 'ID.AM-01', 'equivalent'],
  ['NCA-ECC', '2-1-1', 'CIS-V8', '1', 'equivalent'],
  ['NCA-ECC', '2-1-1', 'NIST-800-53', 'CM-8', 'equivalent'],
  ['NCA-ECC', '2-1-3', 'ISO-27001', 'A.5.10', 'equivalent'],
  ['NCA-ECC', '2-1-4', 'ISO-27001', 'A.5.12', 'equivalent'],
  ['NCA-ECC', '2-1-4', 'NCA-DCC', '2-1', 'equivalent'],
  ['NCA-ECC', '2-10-3', 'ISO-27001', 'A.8.8', 'equivalent'],
  ['NCA-ECC', '2-10-3', 'NIST-CSF', 'ID.RA-01', 'equivalent'],
  ['NCA-ECC', '2-10-3', 'CIS-V8', '7', 'equivalent'],
  ['NCA-ECC', '2-10-3', 'NIST-800-53', 'RA-5', 'equivalent'],
  ['NCA-ECC', '2-10-3', 'SAMA-CSF', '3.17', 'equivalent'],
  ['NCA-ECC', '2-13-3', 'ISO-27001', 'A.5.26', 'equivalent'],
  ['NCA-ECC', '2-13-3', 'NIST-CSF', 'RS.MA-01', 'equivalent'],
  ['NCA-ECC', '2-13-3', 'CIS-V8', '17', 'equivalent'],
  ['NCA-ECC', '2-13-3', 'NIST-800-53', 'IR-4', 'equivalent'],
  ['NCA-ECC', '2-13-3', 'SAMA-CSF', '3.15', 'equivalent'],
  ['NCA-ECC', '2-12-3', 'ISO-27001', 'A.8.15', 'equivalent'],
  ['NCA-ECC', '2-12-3', 'CIS-V8', '8.2', 'equivalent'],
  ['NCA-ECC', '2-12-3', 'NIST-800-53', 'AU-2', 'equivalent'],
  ['NCA-ECC', '2-12-3', 'NIST-CSF', 'PR.PS-04', 'equivalent'],
  ['NCA-ECC', '2-9-3', 'ISO-27001', 'A.8.13', 'equivalent'],
  ['NCA-ECC', '2-9-3', 'CIS-V8', '11', 'equivalent'],
  ['NCA-ECC', '2-9-3', 'NIST-800-53', 'CP-9', 'equivalent'],
  ['NCA-ECC', '2-9-3', 'NIST-CSF', 'PR.DS-11', 'equivalent'],
  ['NCA-ECC', '2-7-3', 'ISO-27001', 'A.5.12', 'equivalent'],
  ['NCA-ECC', '2-7-3', 'NCA-DCC', '2-1', 'narrower'],
  ['NCA-ECC', '2-8-3', 'ISO-27001', 'A.8.24', 'equivalent'],
  ['NCA-ECC', '2-8-3', 'NIST-800-53', 'SC-13', 'equivalent'],
  ['NCA-ECC', '2-8-3', 'SAMA-CSF', '3.9', 'equivalent'],
  ['NCA-ECC', '4-1-1', 'ISO-27001', 'A.5.19', 'equivalent'],
  ['NCA-ECC', '4-1-1', 'CIS-V8', '15', 'equivalent'],
  ['NCA-ECC', '4-1-1', 'NIST-CSF', 'GV.SC', 'broader'],
  ['NCA-ECC', '4-1-1', 'SAMA-CSF', '4.1', 'equivalent'],
  ['NCA-ECC', '4-1-2', 'ISO-27001', 'A.5.20', 'equivalent'],
  ['NCA-ECC', '4-2-1', 'ISO-27001', 'A.5.23', 'equivalent'],
  ['NCA-ECC', '4-2-1', 'NCA-CCC', '1-1', 'narrower'],
  ['NCA-ECC', '4-2-1', 'SAMA-CSF', '4.3', 'equivalent'],
  ['NCA-ECC', '1-3-1', 'ISO-27001', 'A.5.1', 'equivalent'],
  ['NCA-ECC', '1-3-1', 'NIST-CSF', 'GV.PO-01', 'equivalent'],
  ['NCA-ECC', '1-3-1', 'COBIT-2019', 'APO13', 'related'],
  ['NCA-ECC', '1-3-3', 'NIST-CSF', 'GV.PO-02', 'equivalent'],
  ['NCA-ECC', '1-4-1', 'ISO-27001', 'A.5.2', 'equivalent'],
  ['NCA-ECC', '1-4-1', 'NIST-CSF', 'GV.RR-02', 'equivalent'],
  ['NCA-ECC', '1-4-1', 'SAMA-CSF', '1.4', 'equivalent'],
  ['NCA-ECC', '1-5-1', 'ISO-27001', '6.1.2', 'equivalent'],
  ['NCA-ECC', '1-5-1', 'ISO-27005', '7', 'equivalent'],
  ['NCA-ECC', '1-5-1', 'NIST-CSF', 'GV.RM', 'equivalent'],
  ['NCA-ECC', '1-5-1', 'COBIT-2019', 'APO12', 'equivalent'],
  ['NCA-ECC', '1-5-1', 'SAMA-CSF', '2.1', 'equivalent'],
  ['NCA-ECC', '3-1-1', 'ISO-22301', '8.4', 'equivalent'],
  ['NCA-ECC', '3-1-1', 'ISO-27001', 'A.5.29', 'equivalent'],
  ['NCA-ECC', '3-1-3', 'ISO-27001', 'A.5.30', 'equivalent'],
  ['NCA-ECC', '3-1-3', 'NIST-CSF', 'RC.RP', 'equivalent'],
  ['NCA-ECC', '2-5-3', 'ISO-27001', 'A.8.22', 'equivalent'],
  ['NCA-ECC', '2-5-3', 'NIST-800-53', 'SC-8', 'related'],
  ['NCA-ECC', '2-3-3', 'ISO-27001', 'A.8.7', 'equivalent'],
  ['NCA-ECC', '2-3-3', 'CIS-V8', '10', 'equivalent'],
  ['NCA-ECC', '2-15', 'ISO-27001', 'A.8.26', 'equivalent'],
  ['NCA-ECC', '2-15', 'CIS-V8', '16', 'equivalent'],
  ['NCA-ECC', '1-10', 'ISO-27001', 'A.6.3', 'equivalent'],
  ['NCA-ECC', '1-10', 'CIS-V8', '14', 'equivalent'],
  ['NCA-ECC', '2-14', 'ISO-27001', 'A.7.1', 'equivalent'],
  ['NCA-ECC', '1-6', 'ISO-27001', 'A.5.8', 'equivalent'],
  ['NCA-ECC', '1-6', 'ISO-27001', 'A.8.32', 'related'],
  ['ISO-27001', 'A.8.32', 'CIS-V8', '4', 'related'],
  ['ISO-27001', 'A.8.32', 'COBIT-2019', 'BAI06', 'equivalent'],
  ['ISO-27001', 'A.8.25', 'NIST-800-53', 'SA-11', 'related'],
  ['ISO-27001', 'A.8.16', 'NIST-800-53', 'SI-4', 'equivalent'],
  ['ISO-27001', 'A.8.16', 'NIST-CSF', 'DE.CM-01', 'equivalent']
];

export const SOURCE_NOTE =
  'Reference metadata compiled for control-mapping purposes. Control identifiers ' +
  'and titles must be verified against the official publication before being relied ' +
  'upon for regulatory attestation. Import your licensed copy to replace these entries.';
