/** Canonical requirement models — governance, risk, awareness and change. */
import { raci } from './req-helpers.js';

export const GOVERN_DOMAINS = {
  governance: {
    objectives: [
      'Establish executive direction, authority and accountability for cybersecurity.',
      'Maintain a coherent, approved and current policy framework.',
      'Demonstrate compliance with applicable laws, regulations and standards.'
    ],
    parameters: { policyReviewFrequency: 'annually', committeeFrequency: 'quarterly', strategyHorizon: 'three years', complianceReviewFrequency: 'annually', auditFrequency: 'annually', policyApprovalAuthority: 'the Cybersecurity Steering Committee' , contextReviewFrequency: 'annually, and on any material change to the business, its regulators or its technology', criticalSystemDesignation: 'designated by the business owner and the CISO against defined criteria, recorded in the asset register and reviewed {{complianceReviewFrequency}}', improvementClosureTarget: '85% of agreed improvement actions closed by their due date', auditTestingSafeguards: 'read-only access where possible, agreed timing, and a rollback position where testing could affect a production service', ipComplianceReview: 'annually, covering licensed software, licensed content and open-source obligations', businessProcessControls: 'authorisation, completeness, accuracy and segregation checks defined for each business process handling financial or personal data'},
    requirements: [
      { key: 'cyber_strategy', title: 'Cybersecurity strategy',
        policy: 'A cybersecurity strategy shall be defined, approved by executive management and aligned to {{orgName}} business objectives and regulatory obligations.',
        standard: 'The strategy shall cover a {{strategyHorizon}} horizon, define target capability levels, and be supported by a funded roadmap with named owners. Progress shall be reported to {{policyApprovalAuthority}} {{committeeFrequency}} and the strategy refreshed at least {{policyReviewFrequency}}.',
        clauseOwners: ['ciso', 'ciso'],
        guidance: 'Tie each roadmap item to a specific regulatory or risk driver so funding decisions can be defended at the board table.',
        controlName: 'Approved cybersecurity strategy', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{policyReviewFrequency}}', kpi: '% of roadmap milestones delivered on schedule (target: 85%)',
        risk: 'Security investment is reactive and disconnected from business risk, producing capability gaps in the areas that matter most.', riskRating: 'high',
        evidence: ['Approved cybersecurity strategy document', 'Roadmap with owners and milestone status', 'Steering Committee minutes recording approval'],
        refs: { 'NCA-ECC': ['1-1'], 'ISO-27001': ['5.2', '6'], 'NIST-CSF': ['GV.OC', 'GV.RM'], 'SAMA-CSF': ['1.2'], 'COBIT-2019': ['EDM01', 'APO13'] } },
      { key: 'policy_framework', title: 'Cybersecurity policy framework',
        policy: 'Cybersecurity policies, standards and procedures shall be defined, documented, approved by {{policyApprovalAuthority}}, communicated to relevant parties and reviewed at least {{policyReviewFrequency}}.',
        standard: 'The framework shall follow the hierarchy of Policy, Standard, Procedure and Work Instruction, with each lower tier traceable to the tier above. Every document shall record an owner, approver, version, effective date, review date and classification. Documents overdue for review shall be reported to {{policyApprovalAuthority}}.',
        clauseOwners: ['grc_manager', 'grc_manager', 'grc_manager'],
        guidance: 'Keep normative obligations in the policy and measurable parameters in the standard; mixing them causes the two to drift apart at the next review.',
        controlName: 'Cybersecurity policy framework management', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{policyReviewFrequency}}', kpi: '% of governance documents within their review date (target: 95%)',
        risk: 'Staff follow outdated or contradictory instructions, and the framework proves unenforceable under audit.', riskRating: 'high',
        evidence: ['Document register with owners, versions and review dates', 'Approval records for the current versions', 'Evidence of communication to affected personnel'],
        refs: { 'NCA-ECC': ['1-3-1', '1-3-2', '1-3-3'], 'ISO-27001': ['A.5.1', 'A.5.37', '7.5'], 'NIST-CSF': ['GV.PO-01', 'GV.PO-02'], 'SAMA-CSF': ['1.3'] } },
      { key: 'roles_authority', title: 'Cybersecurity roles, responsibilities and authority',
        policy: 'Cybersecurity roles and responsibilities shall be defined, documented, approved and assigned to named individuals, with sufficient authority to discharge them.',
        standard: 'The cybersecurity organisational structure shall be approved by executive management and shall preserve independence between the function that implements controls and the function that assures them. Responsibilities shall be documented in role descriptions and reflected in RACI matrices for each domain. Assignments shall be reviewed {{policyReviewFrequency}}.',
        clauseOwners: ['ciso', 'grc_manager', 'grc_manager'],
        guidance: 'Ensure the cybersecurity function does not report to the function it assures; this is the most common structural finding in regulatory reviews.',
        controlName: 'Defined cybersecurity roles and responsibilities', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{policyReviewFrequency}}', kpi: '% of defined cybersecurity roles with a named, current holder (target: 100%)',
        risk: 'Controls have no accountable owner, so failures are identified but never remediated.', riskRating: 'high',
        evidence: ['Approved organisational structure', 'Role descriptions with responsibilities and authority', 'Domain RACI matrices', 'Review records of role assignments'],
        refs: { 'NCA-ECC': ['1-4-1', '1-4-2', '1-4-3'], 'ISO-27001': ['A.5.2', '5.3'], 'NIST-CSF': ['GV.RR-02'], 'SAMA-CSF': ['1.4'] } },
      { key: 'compliance_management', title: 'Compliance with laws, regulations and standards',
        policy: 'Applicable cybersecurity laws, regulations, standards and contractual obligations shall be identified, tracked and demonstrably complied with.',
        standard: 'A compliance obligations register shall record each obligation, its source, the accountable owner and the controls that satisfy it. Compliance shall be assessed at least {{complianceReviewFrequency}}, with gaps recorded, risk-rated and tracked to closure. Regulatory change shall be assessed for impact within 30 days of publication.',
        clauseOwners: ['grc_manager', 'grc_manager', 'grc_manager'],
        guidance: 'Map obligations to operating controls rather than to documents; a policy statement is not evidence of compliance, an operating control is.',
        controlName: 'Regulatory compliance management', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{complianceReviewFrequency}}', kpi: '% of obligations with mapped controls and a current assessment (target: 100%)',
        risk: 'A regulatory requirement is missed entirely, surfacing first as a finding from the regulator.', riskRating: 'critical',
        evidence: ['Compliance obligations register', 'Latest compliance assessment results', 'Gap remediation plans with owners and due dates'],
        refs: { 'NCA-ECC': ['1-7'], 'ISO-27001': ['A.5.31', 'A.5.36'], 'COBIT-2019': ['MEA03'], 'SAMA-CSF': ['2.2', '2.3'] } },
      { key: 'review_audit', title: 'Periodic cybersecurity review and audit',
        policy: 'The implementation of cybersecurity controls shall be reviewed periodically by the cybersecurity function and audited independently.',
        standard: 'Internal cybersecurity reviews shall be conducted {{complianceReviewFrequency}} and independent audits {{auditFrequency}}. Audit findings shall be risk-rated, assigned to a named owner with a due date, and tracked to closure. Results shall be reported to {{policyApprovalAuthority}} and, where required, to the regulator.',
        clauseOwners: ['internal_auditor', 'grc_manager', 'ciso'],
        guidance: 'Track audit findings in the same register as post-incident and assessment actions; separate registers hide the total remediation backlog.',
        controlName: 'Cybersecurity review and independent audit', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{auditFrequency}}', kpi: '% of audit findings closed by their due date (target: 90%)',
        risk: 'Control degradation goes undetected between regulatory inspections.', riskRating: 'high',
        evidence: ['Internal review reports', 'Independent audit reports', 'Findings register with closure evidence', 'Committee minutes recording results'],
        refs: { 'NCA-ECC': ['1-8'], 'ISO-27001': ['9.2', '9.3', 'A.5.35'], 'COBIT-2019': ['MEA02', 'MEA04'], 'SAMA-CSF': ['2.4', '2.5'] } },
      { key: 'context_interested_parties', title: 'Context and interested parties',
        policy: 'The internal and external context in which cybersecurity operates shall be understood, recorded and kept current.',
        standard: 'The context shall record the business activities and their information, the regulators and supervisory bodies whose requirements apply, the contractual obligations that bear on cybersecurity, the technology and sourcing model in use, and the threat environment. Interested parties and what each requires shall be listed, including regulators, customers, shareholders and staff. The record shall be reviewed {{contextReviewFrequency}} and shall inform the strategy rather than sit beside it.',
        clauseOwners: ['grc_manager', 'grc_manager', 'ciso'],
        guidance: 'This is the document that answers "why these controls and not others". Without it, the control set is defensible only by reference to a framework, which is not the same as being appropriate to the organisation.',
        controlName: 'Cybersecurity context and interested party requirements', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{contextReviewFrequency}}', kpi: '% of identified regulatory and contractual obligations traced to an operating control (target: 95%)',
        risk: 'The control environment is copied from a framework rather than derived from the organisation, and an obligation specific to it is missed entirely.', riskRating: 'high',
        evidence: ['Recorded context covering business, regulatory, technology and threat factors', 'Interested party register with requirements', 'Traceability from obligations to operating controls'],
        refs: { 'ISO-27001': ['4'], 'ISO-27002': ['5'], 'NCA-ECC': ['1-1', '1-7'], 'SAMA-CSF': ['1.1'], 'COBIT-2019': ['APO01'], 'NIST-800-53': ['PM', 'PL'] } },
      { key: 'critical_system_governance', title: 'Designation and governance of critical systems',
        policy: 'Systems whose compromise would have a severe effect on the organisation, its customers or the national interest shall be designated critical and governed to a higher standard.',
        standard: 'Designation shall be {{criticalSystemDesignation}}. A designated system shall have a named business owner and system owner, an enhanced control baseline, and its own entry in the risk register. The strategy, the review and audit cycle and the assurance programme shall each address critical systems explicitly rather than treating them as part of the general estate. A change in designation shall trigger reassessment of the applicable controls.',
        clauseOwners: ['ciso', 'business_owner', 'grc_manager', 'grc_manager'],
        guidance: 'Designate deliberately and keep the list short. A list on which everything is critical directs no extra attention anywhere, which is the same as having no list.',
        controlName: 'Critical system designation and governance', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{complianceReviewFrequency}}', kpi: '% of designated critical systems with a named owner and enhanced baseline applied (target: 100%)',
        risk: 'The systems that matter most receive the same attention as the rest, and their additional regulatory requirements are never separately addressed.', riskRating: 'high',
        evidence: ['Critical system designation criteria and current list', 'Enhanced baseline applied per designated system', 'Strategy, audit and assurance records addressing critical systems explicitly'],
        refs: { 'NCA-CSCC': ['1-1', '1-4'], 'NCA-ECC': ['1-1', '1-8'], 'ISO-27001': ['A.5.1'], 'SAMA-CSF': ['1.1'] } },
      { key: 'remote_work_policy', title: 'Cybersecurity policy for remote and hybrid working',
        policy: 'Working away from {{orgName}} premises shall be governed by policy rather than by local practice.',
        standard: 'The policy shall state which roles may work remotely, from which locations, on which devices, and what information may be handled in that setting. It shall address the home network, shared living space, personal device use, printing and physical document handling, and the approved collaboration tooling. It shall be approved by {{policyApprovalAuthority}} and reviewed {{policyReviewFrequency}}, and its requirements shall be reflected in the awareness programme and in the technical controls on remote access.',
        clauseOwners: ['grc_manager', 'grc_manager', 'ciso'],
        guidance: 'State what may be handled at home, not only how to connect. The unanswered question in most remote working policies is whether Secret information may be opened in a shared flat.',
        controlName: 'Remote and hybrid working policy', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{policyReviewFrequency}}', kpi: '% of remote-working roles covered by the approved policy (target: 100%)',
        risk: 'Remote working is governed by improvisation, and the controls assumed at the office are absent with no policy saying what should replace them.', riskRating: 'medium',
        evidence: ['Approved remote working policy with approval and review records', 'Mapping from policy requirements to technical controls on remote access', 'Awareness content reflecting the policy'],
        refs: { 'NCA-TCC': ['1-1'], 'NCA-ECC': ['1-3-1'], 'ISO-27001': ['A.6.7', 'A.5.1'], 'ISO-27002': ['5'] } },
      { key: 'improvement_management', title: 'Continual improvement',
        policy: 'Weaknesses found in the cybersecurity programme shall be corrected, and the correction shall be verified.',
        standard: 'Nonconformities and weaknesses from audits, reviews, assessments, exercises and incidents shall be recorded in a single register with a cause, an owner, an action and a due date. Corrective action shall address the cause rather than the instance, and closure shall require verification by someone other than the action owner. {{improvementClosureTarget}} shall be met. Recurring findings shall be escalated to the Cybersecurity Steering Committee as evidence that the cause was not addressed.',
        clauseOwners: ['grc_manager', 'grc_manager', 'grc_manager', 'ciso'],
        guidance: 'One register, whatever the source of the finding. Separate registers per source is how the same underlying cause gets closed three times and fixed none.',
        controlName: 'Continual improvement and corrective action', controlType: 'corrective', controlNature: 'administrative',
        frequency: '{{complianceReviewFrequency}}', kpi: '% of improvement actions closed with verification by their due date (target: {{improvementClosureTarget}})',
        risk: 'Findings are recorded and closed administratively while their causes persist, so the same weakness is found again next cycle.', riskRating: 'medium',
        evidence: ['Single improvement register with causes, owners and due dates', 'Verification records by someone other than the action owner', 'Escalation records for recurring findings'],
        refs: { 'ISO-27001': ['10', 'A.5.35'], 'ISO-27002': ['5'], 'NCA-ECC': ['1-8'], 'NCA-CSCC': ['1-4'], 'COBIT-2019': ['MEA01'] } },
      { key: 'audit_testing_safeguards', title: 'Protection of systems during audit and assessment',
        policy: 'Audit, assessment and testing activity shall not itself become a source of disruption or disclosure.',
        standard: 'Audit and assessment access shall follow {{auditTestingSafeguards}}. Scope, timing and method shall be agreed with the system owner in advance, and access granted shall be time-bound and logged. Data extracted for audit purposes shall be classified, held under the same protection as the source, and destroyed on completion with the destruction evidenced. Testing that could affect availability shall require the system owner\'s explicit approval and a rollback position.',
        clauseOwners: ['internal_auditor', 'system_owner', 'internal_auditor', 'system_owner'],
        guidance: 'The audit extract is a copy of production data living in a spreadsheet on somebody\'s laptop. Classify it, and require its destruction at sign-off.',
        controlName: 'Safeguards over audit and assessment activity', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per engagement', kpi: '% of audit engagements with agreed scope, time-bound access and evidenced data destruction (target: 100%)',
        risk: 'Audit activity disrupts a production service, or audit extracts of sensitive data persist unprotected after the engagement.', riskRating: 'medium',
        evidence: ['Agreed audit scope and method records', 'Time-bound access grants with logs', 'Destruction evidence for audit data extracts'],
        refs: { 'ISO-27001': ['A.8.34', 'A.5.35'], 'ISO-27002': ['5'], 'NCA-ECC': ['1-8'], 'NCA-CSCC': ['1-4'] } },
      { key: 'ip_and_process_controls', title: 'Intellectual property and business process controls',
        policy: 'Licensing obligations shall be met, and the business processes that handle financial and personal data shall carry defined control requirements.',
        standard: 'Compliance with software, content and open-source licensing shall be reviewed {{ipComplianceReview}}, with the installed estate reconciled against entitlements. Open-source components shall be checked for licence obligations before use in a product. {{businessProcessControls}} shall be defined with the process owner and tested within the assurance programme, so that control over financial and personal data is not left to the application alone.',
        clauseOwners: ['it_manager', 'system_owner', 'business_owner'],
        guidance: 'Licence reconciliation and business process control both sit awkwardly between cybersecurity, finance and legal, which is exactly why they end up owned by nobody. Name the owner here.',
        controlName: 'Intellectual property and business process control', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{ipComplianceReview}}', kpi: '% of installed software reconciled against a valid entitlement (target: 98%)',
        risk: 'The organisation is exposed to licensing claims, or a financial process depends on a control nobody has defined or tested.', riskRating: 'medium',
        evidence: ['Licence reconciliation against the installed estate', 'Open-source obligation checks for products', 'Defined and tested business process controls with owners'],
        refs: { 'ISO-27001': ['A.5.32', 'A.5.31'], 'ISO-27002': ['5'], 'COBIT-2019': ['DSS06', 'APO01'], 'NCA-ECC': ['1-7'] } }
    ],
    procedureSeed: {
      purpose: 'To define how the {{orgName}} cybersecurity governance framework is established, approved, communicated, reviewed and assured.',
      steps: [
        { name: 'Identify need', actor: 'Cybersecurity GRC Manager', detail: 'Identify the need for a new or revised governance document from regulatory change, risk assessment, audit finding or incident lesson.' },
        { name: 'Draft', actor: 'Cybersecurity GRC Manager', detail: 'Draft against the approved template, ensuring traceability to framework requirements and to the tier above in the hierarchy.' },
        { name: 'Consult', actor: 'Domain stakeholders', detail: 'Circulate for review to affected owners, IT, Legal and Risk, and resolve comments.', decision: { question: 'Are all material comments resolved?', yes: 'Submit for approval', no: 'Iterate the draft or escalate the disagreement to the CISO' } },
        { name: 'Approve', actor: '{{policyApprovalAuthority}}', detail: 'Approve the document, recording approver, date and version.' },
        { name: 'Publish and communicate', actor: 'Cybersecurity GRC Manager', detail: 'Publish to the document repository and communicate to affected personnel, recording acknowledgement where required.' },
        { name: 'Monitor compliance', actor: 'Cybersecurity Analyst', detail: 'Assess compliance with the document {{complianceReviewFrequency}} and record gaps as findings.' },
        { name: 'Review', actor: 'Document Owner', detail: 'Review at least {{policyReviewFrequency}}, or earlier on material change, and reissue or retire the document.' }
      ],
      inputs: [
        'Regulatory and contractual obligations applicable to {{orgName}}',
        'Audit, review and assessment findings',
        'The risk register and the current risk position',
        'Requests for a new or amended governance document'
      ],
      outputs: [
        'Approved policies, standards and procedures with review dates',
        'A current compliance obligations register with named owners',
        'Improvement actions arising from review and audit'
      ],
      escalation: [
        'A document overdue for review escalates to {{policyApprovalAuthority}}.',
        'A regulatory change with no assigned owner escalates to the CISO within 30 days of publication.',
        'A finding recurring across two review cycles escalates to the Cybersecurity Steering Committee as a systemic issue.'
      ],
      records: [
        'Approved documents with version and approval history (retained for the life of the document plus 3 years)',
        'Compliance assessment results with gap closure evidence (retained 5 years)',
        'Improvement register entries with verified closure (retained 3 years)'
      ]
    },
    raciActivities: [
      raci('Approve the cybersecurity strategy', 'Govern', 'A:ciso R:grc_manager C:risk_manager C:it_manager'),
      raci('Draft cybersecurity policies and standards', 'Govern', 'A:grc_manager R:cyber_analyst C:ciso C:it_manager'),
      raci('Approve the policy framework', 'Govern', 'A:ciso R:grc_manager C:risk_manager'),
      raci('Communicate policies to personnel', 'Govern', 'A:grc_manager R:cyber_analyst C:business_owner'),
      raci('Maintain the compliance obligations register', 'Assure', 'A:grc_manager R:cyber_analyst C:risk_manager C:internal_auditor'),
      raci('Conduct internal cybersecurity review', 'Assure', 'A:ciso R:grc_manager C:cyber_analyst I:internal_auditor'),
      raci('Conduct independent audit', 'Assure', 'A:risk_manager R:internal_auditor C:ciso C:grc_manager'),
      raci('Maintain the cybersecurity context and obligation register', 'Govern', 'A:ciso R:grc_manager C:business_owner'),
      raci('Designate and govern critical systems', 'Govern', 'A:ciso R:business_owner C:system_owner I:internal_auditor'),
      raci('Approve the remote working policy', 'Govern', 'A:ciso R:grc_manager C:business_owner'),
      raci('Drive continual improvement to verified closure', 'Assure', 'A:grc_manager R:risk_manager C:internal_auditor'),
      raci('Safeguard systems during audit and assessment', 'Assure', 'A:system_owner R:internal_auditor C:grc_manager'),
      raci('Reconcile licensing and define business process controls', 'Govern', 'A:business_owner R:grc_manager C:it_manager'),
      raci('Track findings to closure', 'Assure', 'A:grc_manager R:system_owner C:internal_auditor C:risk_manager')
    ]
  },

  risk_management: {
    objectives: [
      'Identify and assess cybersecurity risk consistently across the organisation.',
      'Treat risk in line with the approved risk appetite.',
      'Ensure accepted risk is visible, owned and time-bound.'
    ],
    parameters: { riskAssessmentFrequency: 'annually and on material change', riskRegisterReviewFrequency: 'quarterly', riskAcceptanceMaxDuration: '12 months', criticalRiskEscalation: 'the Cybersecurity Steering Committee within 5 business days', riskMethodology: 'a documented impact and likelihood matrix calibrated to the {{orgName}} risk appetite' , riskEvaluationCriteria: 'defined likelihood and impact scales, an appetite statement per impact category, and the rating at which escalation becomes mandatory', assessmentTriggers: 'a new or materially changed system, a new supplier or cloud service, a change in the regulatory position, a significant incident, and remote working arrangements', riskOwnerRule: 'a named individual with the authority to fund the treatment or to accept the risk, never a team or a committee', appetiteReviewFrequency: 'annually, and on any material change to the business strategy', assuranceIntegration: 'audit findings, control test results, incident causes and exercise outcomes feed the register rather than sitting in separate reports'},
    requirements: [
      { key: 'risk_methodology', title: 'Risk management methodology',
        policy: 'A cybersecurity risk management methodology shall be defined, documented and approved, and applied consistently across {{orgName}}.',
        standard: 'The methodology shall define {{riskMethodology}}, asset and threat identification, vulnerability assessment, risk evaluation criteria, treatment options and acceptance authority by risk level. It shall align to the enterprise risk framework so that cybersecurity risk is comparable with other risk types.',
        clauseOwners: ['risk_manager', 'risk_manager'],
        guidance: 'Calibrate impact bands in currency and service-downtime terms the business already uses, so cyber risk is comparable at the board table.',
        controlName: 'Cybersecurity risk management methodology', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed annually', kpi: '% of risk assessments applying the approved methodology (target: 100%)',
        risk: 'Risks are rated inconsistently, so prioritisation and acceptance decisions cannot be relied upon.', riskRating: 'high',
        evidence: ['Approved risk methodology document', 'Risk evaluation criteria and appetite statement', 'Sample assessments demonstrating consistent application'],
        refs: { 'NCA-ECC': ['1-5-1', '1-5-2'], 'ISO-27001': ['6.1.2', '6.1.3'], 'ISO-27005': ['7'], 'NIST-CSF': ['GV.RM'], 'COBIT-2019': ['APO12'], 'SAMA-CSF': ['2.1'] } },
      { key: 'risk_assessment', title: 'Cybersecurity risk assessment',
        policy: 'Cybersecurity risk assessments shall be conducted {{riskAssessmentFrequency}}, and before significant technology change, new projects and outsourcing arrangements.',
        standard: 'Assessments shall identify assets in scope, applicable threats, existing controls, vulnerabilities, and the resulting inherent and residual risk. Results shall be recorded in the risk register with a named risk owner. Assessment shall precede go-live, not follow it.',
        clauseOwners: ['risk_manager', 'risk_manager', 'system_owner'],
        guidance: 'Embed the assessment trigger in project gating and change approval workflows; assessments required by policy alone are routinely skipped under delivery pressure.',
        controlName: 'Cybersecurity risk assessment', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{riskAssessmentFrequency}}', kpi: '% of in-scope projects with a completed risk assessment before go-live (target: 100%)',
        risk: 'Material risk is introduced by change and discovered only after it has been realised.', riskRating: 'high',
        evidence: ['Completed risk assessment reports', 'Risk register entries with named owners', 'Project gate records showing assessment completion'],
        refs: { 'NCA-ECC': ['1-5-3', '1-6'], 'ISO-27001': ['6.1.2', 'A.5.8'], 'ISO-27005': ['7.2', '7.3'], 'NIST-CSF': ['ID.RA'] } },
      { key: 'risk_treatment', title: 'Risk treatment',
        policy: 'Cybersecurity risks shall be treated in line with the approved risk appetite, through mitigation, transfer, avoidance or formal acceptance.',
        standard: 'Each risk above appetite shall have a treatment plan with defined actions, a named owner, a due date and a target residual rating. Treatment progress shall be reviewed {{riskRegisterReviewFrequency}}. Risks rated Critical shall be escalated to {{criticalRiskEscalation}}.',
        clauseOwners: ['risk_manager', 'risk_manager', 'ciso'],
        guidance: 'Require the treatment plan to name the control it will create or strengthen, so the risk register and the control library stay connected.',
        controlName: 'Risk treatment planning and tracking', controlType: 'corrective', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: '% of treatment actions completed by their due date (target: 85%)',
        risk: 'Identified risks are recorded and then left untreated, so the register becomes a list of known unmanaged exposures.', riskRating: 'high',
        evidence: ['Risk register with treatment plans and due dates', 'Treatment progress reports', 'Escalation records for critical risks'],
        refs: { 'NCA-ECC': ['1-5-2'], 'ISO-27001': ['6.1.3'], 'ISO-27005': ['8'], 'NIST-CSF': ['GV.RM'], 'COBIT-2019': ['EDM03'] } },
      { key: 'risk_acceptance', title: 'Risk acceptance',
        policy: 'Residual risk shall be formally accepted by an authority commensurate with the risk level, and acceptance shall be time-bound.',
        standard: 'Acceptance shall record the residual rating, the rationale, compensating controls and an expiry date not exceeding {{riskAcceptanceMaxDuration}}. Critical residual risk shall be accepted only by the Cybersecurity Steering Committee. Expired acceptances shall be re-evaluated, not automatically renewed.',
        clauseOwners: ['business_owner', 'ciso', 'risk_manager'],
        guidance: 'Expire acceptances automatically and re-present them; a risk accepted once otherwise remains accepted permanently without review.',
        controlName: 'Formal risk acceptance', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per acceptance, reviewed {{riskRegisterReviewFrequency}}', kpi: 'Number of expired risk acceptances still in force (target: 0)',
        risk: 'Risk is accepted informally by people without the authority to accept it, and never revisited.', riskRating: 'medium',
        evidence: ['Risk acceptance records with approver and expiry date', 'Committee minutes for critical acceptances', 'Report of expired acceptances'],
        refs: { 'ISO-27001': ['6.1.3', '8.3'], 'NCA-ECC': ['1-5-2'], 'NIST-CSF': ['GV.RM'] } },
      { key: 'risk_reporting', title: 'Risk reporting',
        policy: 'The cybersecurity risk position shall be reported to executive management and the board on a defined cycle.',
        standard: 'Reporting shall present the risk profile by level, movement since the previous period, treatment progress, accepted risks approaching expiry, and risks above appetite. The register shall be reviewed {{riskRegisterReviewFrequency}}.',
        clauseOwners: ['risk_manager', 'risk_manager'],
        guidance: 'Report movement and overdue treatment rather than a static heat map; the trend is what supports an investment decision.',
        controlName: 'Cybersecurity risk reporting', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: 'Risk register reviewed within the last {{riskRegisterReviewFrequency}} (target: yes)',
        risk: 'Executive management is unaware of accumulating risk and does not act until it is realised.', riskRating: 'medium',
        evidence: ['Risk reports presented to committee', 'Committee minutes recording discussion', 'Risk register version history'],
        refs: { 'NCA-ECC': ['1-5-2'], 'ISO-27001': ['9.1', '9.3'], 'NIST-CSF': ['GV.OV'], 'COBIT-2019': ['APO12'] } },
      { key: 'risk_evaluation_criteria', title: 'Risk evaluation criteria and appetite',
        policy: 'Risk shall be evaluated against criteria agreed in advance, and the organisation shall state how much risk it is prepared to accept.',
        standard: 'The criteria shall comprise {{riskEvaluationCriteria}}, approved by executive management and reviewed {{appetiteReviewFrequency}}. Evaluation shall use the same scales across every assessment, so that two risks rated high are comparable. Appetite shall be expressed per impact category — financial, regulatory, customer, safety, reputation — rather than as a single statement, since the tolerance for each differs. A risk exceeding appetite shall be escalated under {{criticalRiskEscalation}} regardless of the assessor\'s view of its likelihood.',
        clauseOwners: ['ciso', 'risk_manager', 'ciso', 'risk_manager'],
        guidance: 'A single appetite statement covering all impact types is unusable in practice: no organisation has the same tolerance for a regulatory breach as for a reputational bruise. Split it.',
        controlName: 'Risk evaluation criteria and appetite statement', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{appetiteReviewFrequency}}', kpi: '% of assessments evaluated against the approved criteria (target: 100%)',
        risk: 'Ratings are not comparable between assessments, so the register cannot be prioritised and appetite cannot be applied.', riskRating: 'high',
        evidence: ['Approved evaluation criteria with likelihood and impact scales', 'Appetite statement per impact category with approval records', 'Assessments evidencing use of the approved scales'],
        refs: { 'ISO-27005': ['7.4'], 'ISO-27001': ['6.1.2', '8.2'], 'NCA-ECC': ['1-5-1', '1-5-2'], 'NCA-CSCC': ['1-2'], 'NIST-800-53': ['RA'] } },
      { key: 'risk_assessment_triggers', title: 'When a risk assessment is required',
        policy: 'A risk assessment shall be performed at defined trigger points, not only on the annual cycle.',
        standard: 'Assessment shall be required on {{assessmentTriggers}}, in addition to the {{riskAssessmentFrequency}} cycle. The trigger shall be enforced through the change and procurement processes so that an assessment is a prerequisite rather than a follow-up. Where a trigger is met and the assessment concludes no material change to the risk position, that conclusion shall be recorded, so that the absence of new risk entries is evidence of assessment rather than of omission.',
        clauseOwners: ['risk_manager', 'it_manager', 'risk_manager'],
        guidance: 'Hook the trigger into procurement and change. An assessment that depends on someone remembering to ask for it is performed for the projects that were already careful.',
        controlName: 'Risk assessment triggers', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per trigger', kpi: '% of trigger events with a completed or recorded assessment (target: 95%)',
        risk: 'Risk is assessed annually while the environment changes weekly, so the register describes a position the organisation has left.', riskRating: 'high',
        evidence: ['Defined trigger list embedded in change and procurement processes', 'Assessments traced to trigger events', 'Recorded no-material-change conclusions'],
        refs: { 'ISO-27001': ['8.2'], 'ISO-27005': ['7.4'], 'NCA-ECC': ['1-5-3'], 'NCA-DCC': ['1-4'], 'NCA-CCC': ['1-2'], 'NCA-TCC': ['1-2'] } },
      { key: 'risk_ownership', title: 'Risk ownership',
        policy: 'Every risk shall have an owner who can act on it.',
        standard: '{{riskOwnerRule}} shall apply. The owner shall confirm the rating, agree the treatment and be reported against for its progress. Where the natural owner lacks the authority to fund treatment, ownership shall sit with the person who does rather than being recorded against the person closest to the problem. Ownership shall be reconfirmed {{riskRegisterReviewFrequency}}, and a risk whose owner has left shall be reassigned within one review cycle rather than left dormant.',
        clauseOwners: ['risk_manager', 'business_owner', 'ciso', 'risk_manager'],
        guidance: 'A risk owned by a team is owned by nobody. And a risk owned by someone who cannot release budget produces a treatment plan that never starts.',
        controlName: 'Named risk ownership', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: '% of open risks with a named individual owner holding sufficient authority (target: 100%)',
        risk: 'Risks sit in the register with nobody able to act, and treatment plans are agreed by people who cannot fund them.', riskRating: 'medium',
        evidence: ['Register showing a named individual owner per risk', 'Ownership reconfirmation records per review cycle', 'Reassignment records following a departure'],
        refs: { 'ISO-27001': ['6.1.2', '8.2'], 'ISO-27005': ['10'], 'NCA-ECC': ['1-5-2'], 'NCA-CSCC': ['1-2'], 'NIST-800-53': ['RA', 'PM'] } },
      { key: 'risk_assurance_integration', title: 'Integration with assurance and continuity',
        policy: 'The risk register shall be informed by what assurance activity actually finds, and shall inform continuity planning in return.',
        standard: '{{assuranceIntegration}}. A control assessed as ineffective shall raise or re-rate the risk it was mitigating rather than being recorded only as a control finding. Business impact analysis and continuity risk assessment shall use the same criteria and feed the same register, so that the organisation holds one view of disruption risk. Risk information shall be exchanged with the enterprise risk function in its own taxonomy, so that cybersecurity risk is visible at board level alongside other risk.',
        clauseOwners: ['grc_manager', 'risk_manager', 'risk_manager', 'risk_manager'],
        guidance: 'An ineffective control and an under-rated risk are the same fact recorded in two places. Make the control test result change the rating, or the register will read better than reality.',
        controlName: 'Integration of risk with assurance and continuity', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: '% of ineffective control findings reflected in the risk register rating (target: 90%)',
        risk: 'Assurance finds a control ineffective while the register continues to show the risk as mitigated by it.', riskRating: 'high',
        evidence: ['Register entries traced to audit, control test and incident findings', 'Shared criteria between continuity and cybersecurity risk assessment', 'Risk information exchanged with the enterprise risk function'],
        refs: { 'ISO-27005': ['10'], 'ISO-22301': ['8.2.3'], 'ISO-27001': ['8.2', 'A.5.35'], 'NCA-ECC': ['1-5-3', '1-8'], 'NCA-CSCC': ['1-2'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Establish context', actor: 'Risk Manager', detail: 'Confirm scope, assets, business processes, regulatory obligations and the applicable risk appetite.' },
      { name: 'Identify risk', actor: 'Cybersecurity Analyst', detail: 'Identify threats, vulnerabilities and existing controls for the assets in scope.' },
      { name: 'Analyse and evaluate', actor: 'Risk Manager', detail: 'Rate impact and likelihood using {{riskMethodology}} to derive inherent and residual risk.', decision: { question: 'Is residual risk within appetite?', yes: 'Record and monitor', no: 'Proceed to treatment planning' } },
      { name: 'Plan treatment', actor: 'Risk Owner', detail: 'Select mitigation, transfer, avoidance or acceptance, and define actions with owners and due dates.' },
      { name: 'Approve', actor: 'CISO / Steering Committee', detail: 'Approve the treatment plan, or formally accept residual risk for no more than {{riskAcceptanceMaxDuration}}.', decision: { question: 'Is the residual risk rated Critical?', yes: 'Escalate to {{criticalRiskEscalation}}', no: 'Approve at the delegated authority level' } },
      { name: 'Monitor and report', actor: 'Risk Manager', detail: 'Track treatment progress and report the risk position {{riskRegisterReviewFrequency}}.' }
    ],
    inputs: [
      'The asset and system inventory with business criticality',
      'Threat intelligence and incident history',
      'Control effectiveness results from the assurance programme',
      'Changes and projects that meet an assessment trigger, namely {{assessmentTriggers}}'
    ],
    outputs: [
      'A current risk register with named owners and residual ratings',
      'Approved treatment plans with actions, owners and due dates',
      'Recorded risk acceptances with expiry dates'
    ],
    escalation: [
      'A risk rated Critical escalates under {{criticalRiskEscalation}}.',
      'A treatment plan overdue by more than one review cycle escalates to the CISO.',
      'A risk whose owner has left escalates to the Risk Manager for reassignment within one review cycle.'
    ],
    records: [
      'Risk assessments with method, scope and participants (retained 5 years)',
      'Treatment plans and progress records (retained for the life of the risk plus 3 years)',
      'Risk acceptance approvals with expiry dates (retained 5 years)'
    ]
    },
    raciActivities: [
      raci('Define the risk management methodology', 'Govern', 'A:ciso R:risk_manager C:grc_manager C:internal_auditor'),
      raci('Conduct cybersecurity risk assessments', 'Assure', 'A:risk_manager R:cyber_analyst C:system_owner C:it_manager'),
      raci('Own identified risks', 'Govern', 'A:business_owner R:system_owner C:risk_manager C:ciso'),
      raci('Approve risk treatment plans', 'Govern', 'A:ciso R:risk_manager C:business_owner C:grc_manager'),
      raci('Accept residual risk', 'Govern', 'A:ciso R:business_owner C:risk_manager I:internal_auditor'),
      raci('Report the risk position to the committee', 'Govern', 'A:ciso R:risk_manager C:grc_manager'),
      raci('Approve risk evaluation criteria and appetite', 'Govern', 'A:ciso R:risk_manager C:business_owner'),
      raci('Enforce risk assessment triggers in change and procurement', 'Govern', 'A:risk_manager R:grc_manager C:it_manager'),
      raci('Assign and reconfirm named risk owners', 'Govern', 'A:risk_manager R:business_owner C:ciso'),
      raci('Integrate assurance findings into the risk register', 'Assure', 'A:risk_manager R:grc_manager C:internal_auditor'),
      raci('Audit the risk management process', 'Assure', 'A:risk_manager R:internal_auditor C:grc_manager')
    ]
  },

  security_awareness: {
    objectives: [
      'Ensure personnel understand their cybersecurity responsibilities.',
      'Provide role-specific training for higher-risk roles.',
      'Measure behaviour, not only completion.'
    ],
    parameters: { awarenessFrequency: 'annually for all personnel, with quarterly reinforcement', phishingSimulationFrequency: 'quarterly', trainingCompletionTarget: '95% within 30 days of assignment', phishingReportingTarget: 'above 30% of simulated phishing reported', screeningRequirement: 'identity, employment history and criminal record verification proportionate to the role' , onboardingDeadline: 'before access to information systems is granted, and no later than 5 business days from the start date', acceptableUseAcknowledgement: 'acknowledged at onboarding and re-acknowledged {{awarenessFrequency}}', disciplinaryLinkage: 'handled under the applicable human resources disciplinary process, with cybersecurity providing the factual record', leaverReturnSla: '1 business day from the last working day for all assets and credentials', teleworkAwareness: 'additional content on home network security, device sharing, physical privacy and approved collaboration tooling', executiveBriefingFrequency: 'semi-annually to executive management and the board'},
    requirements: [
      { key: 'awareness_programme', title: 'Security awareness programme',
        policy: 'All personnel and relevant third parties shall receive cybersecurity awareness training appropriate to their role, on induction and periodically thereafter.',
        standard: 'Awareness training shall be delivered {{awarenessFrequency}}, covering acceptable use, phishing, data handling, incident reporting, physical security and remote working. Completion shall reach {{trainingCompletionTarget}}, and non-completion shall be escalated to line management.',
        clauseOwners: ['grc_manager', 'business_owner'],
        guidance: 'Tie content to the incidents the organisation actually experiences; generic annual content changes behaviour far less than material drawn from real events.',
        controlName: 'Security awareness programme', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{awarenessFrequency}}', kpi: 'Training completion rate (target: {{trainingCompletionTarget}})',
        risk: 'Personnel remain the most frequently exploited entry point because they were never taught what the attack looks like.', riskRating: 'high',
        evidence: ['Training content and delivery schedule', 'Completion records by department', 'Escalation records for non-completion'],
        refs: { 'NCA-ECC': ['1-10'], 'ISO-27001': ['A.6.3', '7.2', '7.3'], 'CIS-V8': ['14'], 'SAMA-CSF': ['1.6', '1.7'] } },
      { key: 'role_based_training', title: 'Role-based training',
        policy: 'Personnel in roles with elevated cybersecurity responsibility shall receive additional role-specific training.',
        standard: 'Role-based training shall be defined for developers, administrators, security personnel, executives and those handling personal or Confidential data. Competency requirements shall be documented per role and training completion tracked against them.',
        clauseOwners: ['grc_manager', 'grc_manager'],
        guidance: 'Define the competency first and select training against it, rather than recording whatever courses happened to be attended.',
        controlName: 'Role-based security training', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{awarenessFrequency}}', kpi: '% of elevated-risk roles with current role-based training (target: 90%)',
        risk: 'Those with the greatest ability to cause or prevent harm receive only general awareness content.', riskRating: 'medium',
        evidence: ['Role-based training matrix', 'Competency requirements per role', 'Completion records for elevated-risk roles'],
        refs: { 'NCA-ECC': ['1-10', '1-9'], 'ISO-27001': ['A.6.3', '7.2'], 'CIS-V8': ['14'] } },
      { key: 'phishing_simulation', title: 'Phishing simulation',
        policy: 'Simulated phishing shall be used to measure and improve resilience to social engineering.',
        standard: 'Simulations shall be conducted {{phishingSimulationFrequency}} across the organisation. Reporting rate shall be tracked with a target {{phishingReportingTarget}}, alongside click rate. Repeated susceptibility shall trigger targeted coaching rather than sanction in the first instance.',
        clauseOwners: ['cyber_analyst', 'cyber_analyst', 'business_owner'],
        guidance: 'Track reporting rate as the primary measure; click rate alone rewards silence, while reporting is the behaviour that actually enables response.',
        controlName: 'Phishing simulation programme', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{phishingSimulationFrequency}}', kpi: 'Simulated phishing reporting rate (target: {{phishingReportingTarget}})',
        risk: 'Phishing susceptibility is unknown until a real campaign succeeds.', riskRating: 'medium',
        evidence: ['Simulation campaign results with click and report rates', 'Targeted coaching records', 'Trend analysis over at least four campaigns'],
        refs: { 'CIS-V8': ['14'], 'ISO-27001': ['A.6.3'], 'NCA-ECC': ['1-10'] } },
      { key: 'personnel_security', title: 'Personnel security',
        policy: 'Cybersecurity responsibilities shall be addressed before, during and after employment.',
        standard: 'Screening shall comprise {{screeningRequirement}} before employment, and shall be repeated for personnel moving into privileged roles. Employment terms shall include confidentiality obligations and cybersecurity responsibilities. A disciplinary process shall apply to violations, and responsibilities that survive termination shall be communicated at exit.',
        clauseOwners: ['grc_manager', 'grc_manager', 'business_owner'],
        guidance: 'Re-screen on movement into privileged roles rather than only at hire; the risk profile changes with the role, not with the joining date.',
        controlName: 'Personnel security', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'At hire and on role change', kpi: '% of privileged-role holders with completed screening (target: 100%)',
        risk: 'Individuals with undisclosed history are placed directly into positions of significant trust.', riskRating: 'medium',
        evidence: ['Screening completion records', 'Employment terms containing security obligations', 'Exit acknowledgement records'],
        refs: { 'NCA-ECC': ['1-9'], 'ISO-27001': ['A.6.1', 'A.6.2', 'A.6.4', 'A.6.5'], 'SAMA-CSF': ['3.1'], 'NIST-800-53': ['PS'] } },
      { key: 'onboarding_awareness', title: 'Awareness at onboarding',
        policy: 'No individual shall be granted access to {{orgName}} information systems before completing cybersecurity induction and acknowledging the acceptable use requirements.',
        standard: 'Induction shall be completed {{onboardingDeadline}}. It shall cover the acceptable use requirements, how to report a suspected incident, data classification and handling, and the consequences of non-compliance. {{acceptableUseAcknowledgement}}. Completion shall be recorded per individual, and access provisioning shall be able to evidence that the induction preceded the grant. Contractors and third-party personnel shall complete equivalent induction before access.',
        clauseOwners: ['business_owner', 'grc_manager', 'grc_manager', 'iam_specialist', 'grc_manager'],
        guidance: 'Tie the induction record to the joiner workflow rather than tracking it separately. Where the two are separate lists, the gap is always the people who started in a hurry.',
        controlName: 'Cybersecurity induction and acceptable use acknowledgement', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'At hire and on role change', kpi: '% of joiners completing induction before access is granted (target: 100%)',
        risk: 'People operate the environment without knowing the rules, and the organisation cannot show they were ever told.', riskRating: 'medium',
        evidence: ['Induction completion records per individual with dates', 'Signed or recorded acceptable use acknowledgements', 'Reconciliation of induction records against access provisioning dates'],
        refs: { 'NCA-ECC': ['1-9', '1-10'], 'NCA-CSCC': ['1-5'], 'ISO-27001': ['A.6.3', 'A.5.10'], 'ISO-27002': ['6'], 'NIST-800-53': ['AT', 'PS'], 'NIST-CSF': ['PR.AT'] } },
      { key: 'awareness_effectiveness', title: 'Measuring awareness effectiveness',
        policy: 'The awareness programme shall be measured by behaviour, not by completion alone.',
        standard: 'Effectiveness shall be assessed against at least: reporting rate for simulated and real phishing, time from user observation to report, repeat susceptibility by population, and the proportion of incidents whose root cause was user action. Results shall be analysed by business area and role so that targeted content can be directed where it is needed. The programme content shall be revised in response to the measurements and to incident root causes, and the revision recorded.',
        clauseOwners: ['grc_manager', 'grc_manager', 'grc_manager'],
        guidance: 'A 99% completion rate beside a 4% reporting rate means the training was taken, not learned. Reporting rate is the number that predicts whether the next real phish is contained.',
        controlName: 'Awareness effectiveness measurement', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{phishingSimulationFrequency}}', kpi: 'Phishing reporting rate against the target of {{phishingReportingTarget}}',
        risk: 'Training is delivered and recorded while behaviour is unchanged, so the programme reports success it has not achieved.', riskRating: 'medium',
        evidence: ['Effectiveness measurement reports by business area and role', 'Programme revision records traced to measurement and incident causes', 'Repeat susceptibility analysis'],
        refs: { 'NCA-ECC': ['1-10'], 'ISO-27001': ['A.6.3'], 'ISO-27002': ['6'], 'NIST-CSF': ['PR.AT'], 'NIST-800-53': ['AT'], 'COBIT-2019': ['APO07'] } },
      { key: 'joiner_mover_leaver', title: 'Cybersecurity in the employment lifecycle',
        policy: 'Cybersecurity obligations shall be established on joining, revisited on change of role, and discharged on leaving.',
        standard: 'Terms of employment shall include cybersecurity and confidentiality obligations, and those that survive termination shall be stated as such. A change of role shall trigger reassessment of access, of role-based training and, where the new role is privileged, of screening. On leaving, {{leaverReturnSla}} shall apply to the return of assets and the revocation of credentials, evidenced against the asset register. Human resources shall notify cybersecurity of joiners, movers and leavers through a defined channel rather than informally.',
        clauseOwners: ['grc_manager', 'business_owner', 'it_manager', 'business_owner'],
        guidance: 'The mover is the case everyone forgets: access accumulates because the new role is granted and the old one is never removed. Make the reassessment a step in the transfer, not a later review.',
        controlName: 'Cybersecurity in the employment lifecycle', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per event', kpi: '% of leavers with assets returned and credentials revoked within the service level (target: 100%)',
        risk: 'Access and assets persist after the need ends, and obligations that should survive termination were never established.', riskRating: 'high',
        evidence: ['Employment terms containing cybersecurity obligations', 'Mover reassessment records', 'Leaver asset return and revocation evidence reconciled to the asset register'],
        refs: { 'NCA-ECC': ['1-9'], 'NCA-CSCC': ['1-5'], 'ISO-27001': ['A.6.1', 'A.6.2', 'A.6.5', 'A.5.11'], 'ISO-27002': ['6'], 'NIST-800-53': ['PS'], 'COBIT-2019': ['APO07'] } },
      { key: 'telework_awareness', title: 'Awareness for remote and hybrid working',
        policy: 'Personnel working away from {{orgName}} premises shall receive awareness content addressing the risks specific to that setting.',
        standard: 'Remote and hybrid workers shall receive {{teleworkAwareness}}, delivered before remote working begins and refreshed {{awarenessFrequency}}. Content shall state what may and may not be done on a personal device, how to handle printed material away from the office, and the approved channels for Confidential information. Completion shall be recorded, and the content shall be revised when the approved tooling changes.',
        clauseOwners: ['grc_manager', 'grc_manager', 'grc_manager'],
        guidance: 'The specific risks are mundane and worth naming: a household member using the work laptop, a video call in a shared space, a document printed at home and never shredded. Generic content does not reach any of them.',
        controlName: 'Remote working awareness', controlType: 'preventive', controlNature: 'administrative',
        frequency: '{{awarenessFrequency}}', kpi: '% of remote and hybrid workers with current telework awareness training (target: 95%)',
        risk: 'Controls designed for the office are assumed to apply at home, and nobody has told the people working there otherwise.', riskRating: 'medium',
        evidence: ['Telework awareness content and delivery records', 'Completion records for remote and hybrid populations', 'Content revision records following tooling change'],
        refs: { 'NCA-TCC': ['2-6'], 'NCA-ECC': ['1-10'], 'ISO-27001': ['A.6.3', 'A.6.7'], 'ISO-27002': ['6'], 'NIST-800-53': ['AT'] } },
      { key: 'awareness_reporting', title: 'Reporting awareness to management',
        policy: 'The state of cybersecurity awareness shall be reported to executive management and the board on a defined cycle.',
        standard: 'Reporting shall occur {{executiveBriefingFrequency}} and shall cover completion, effectiveness measures, incident root causes attributable to user action, and the actions taken in response. Populations falling below {{trainingCompletionTarget}} shall be named by business area with the accountable executive, rather than reported only as an organisation-wide percentage. Executive and board members shall themselves receive briefing appropriate to their exposure as targets.',
        clauseOwners: ['grc_manager', 'business_owner', 'ciso'],
        guidance: 'Report by business area with the accountable executive named. An organisation-wide average lets every area assume the shortfall belongs to another one.',
        controlName: 'Awareness reporting to management', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{executiveBriefingFrequency}}', kpi: '% of scheduled awareness reports delivered to management on cycle (target: 100%)',
        risk: 'Management believes awareness is adequate because nobody has shown them where it is not.', riskRating: 'low',
        evidence: ['Management and board reporting packs with completion and effectiveness data', 'Records of actions agreed and their closure', 'Executive briefing attendance records'],
        refs: { 'NCA-ECC': ['1-10', '1-2'], 'ISO-27001': ['A.6.3'], 'NIST-CSF': ['PR.AT'], 'COBIT-2019': ['APO07'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Assess need', actor: 'Cybersecurity GRC Manager', detail: 'Identify awareness needs from incident trends, audit findings, regulatory change and role risk.' },
      { name: 'Develop content', actor: 'Cybersecurity GRC Manager', detail: 'Develop general and role-based content reflecting real incidents experienced by {{orgName}}.' },
      { name: 'Deliver', actor: 'Human Resources', detail: 'Assign training at induction and {{awarenessFrequency}}, tracking completion to {{trainingCompletionTarget}}.', decision: { question: 'Is completion below target after 30 days?', yes: 'Escalate to line management', no: 'Record completion' } },
      { name: 'Simulate', actor: 'Cybersecurity Analyst', detail: 'Run phishing simulations {{phishingSimulationFrequency}} and record click and reporting rates.' },
      { name: 'Coach', actor: 'Cybersecurity GRC Manager', detail: 'Provide targeted coaching for repeated susceptibility before considering disciplinary measures.' },
      { name: 'Measure and report', actor: 'CISO', detail: 'Report completion, reporting rate and trend to the Steering Committee and refresh content accordingly.' }
    ],
    inputs: [
      'Incident root causes and audit findings indicating awareness gaps',
      'Joiner, mover and leaver notifications from Human Resources',
      'Phishing simulation results',
      'Policy and regulatory changes affecting staff obligations'
    ],
    outputs: [
      'Delivered training with completion recorded per individual',
      'Phishing simulation results with reporting and click rates',
      'Targeted coaching records where susceptibility recurs'
    ],
    escalation: [
      'Completion below {{trainingCompletionTarget}} in a business area escalates to the accountable executive.',
      'Susceptibility that persists after targeted coaching escalates to line management and Human Resources.',
      'An induction not completed by its deadline escalates to the line manager before access is confirmed.'
    ],
    records: [
      'Training completion records per individual (retained 3 years)',
      'Phishing simulation results and follow-up coaching (retained 3 years)',
      'Acceptable use acknowledgements (retained for the engagement plus 2 years)'
    ]
    },
    raciActivities: [
      raci('Define the awareness programme', 'Govern', 'A:ciso R:grc_manager C:business_owner'),
      raci('Develop awareness and role-based content', 'Govern', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Deliver and track training completion', 'Operate', 'A:business_owner R:grc_manager C:internal_auditor'),
      raci('Run phishing simulations', 'Detect', 'A:ciso R:cyber_analyst C:grc_manager'),
      raci('Screen personnel for privileged roles', 'Protect', 'A:business_owner R:grc_manager C:ciso'),
      raci('Deliver cybersecurity induction before access', 'Govern', 'A:grc_manager R:business_owner C:it_manager'),
      raci('Measure awareness effectiveness', 'Assure', 'A:grc_manager R:cyber_analyst C:business_owner'),
      raci('Manage cybersecurity in the employment lifecycle', 'Govern', 'A:business_owner R:grc_manager C:it_manager I:internal_auditor'),
      raci('Deliver remote working awareness', 'Govern', 'A:grc_manager R:business_owner C:it_manager'),
      raci('Report awareness metrics', 'Govern', 'A:ciso R:grc_manager C:internal_auditor')
    ]
  },

  change_management: {
    objectives: [
      'Ensure changes are assessed for security impact before implementation.',
      'Maintain approved configuration baselines.',
      'Control emergency changes without losing assurance.'
    ],
    parameters: { cabFrequency: 'weekly', emergencyChangeReviewSla: '5 business days', backoutRequirement: 'a documented and tested back-out plan for every standard and major change', configReviewFrequency: 'quarterly', securityReviewThreshold: 'any change affecting internet exposure, authentication, encryption, network boundaries or Confidential data' , unauthorisedChangeSla: '1 business day to investigate and either authorise retrospectively or reverse', patchChangeRoute: 'the pre-approved standard change route, with security patches exempt from advisory board scheduling but not from testing or recording', releaseVerification: 'a post-implementation check of the security controls the change touched', changeFreezeWindows: 'defined periods during which only emergency and security changes are permitted', segregationRule: 'the person who builds a change shall not be the sole person who approves and applies it'},
    requirements: [
      { key: 'change_control', title: 'Change control',
        policy: 'Changes to information systems shall be requested, assessed, approved, tested and recorded before implementation.',
        standard: 'Changes shall be classified as standard, normal or emergency. Normal changes shall be reviewed by the change advisory board {{cabFrequency}}. Every standard and major change shall include {{backoutRequirement}}. Unauthorised changes shall be investigated and reversed.',
        clauseOwners: ['it_manager', 'it_manager', 'system_owner', 'it_manager'],
        guidance: 'Detect unauthorised change through configuration monitoring rather than relying on the change record alone; the changes that cause incidents are usually the ones never raised.',
        controlName: 'Change control process', controlType: 'preventive', controlNature: 'administrative',
        frequency: '{{cabFrequency}}', kpi: '% of production changes with an approved change record (target: 98%)',
        risk: 'Untested and unreviewed changes cause outage or silently remove a security control.', riskRating: 'high',
        evidence: ['Change records with approvals and test evidence', 'Change advisory board minutes', 'Unauthorised change detection reports'],
        refs: { 'ISO-27001': ['A.8.32'], 'NCA-ECC': ['1-6'], 'COBIT-2019': ['BAI06'], 'SAMA-CSF': ['3.7'] } },
      { key: 'security_impact_assessment', title: 'Security impact assessment of change',
        policy: 'Changes shall be assessed for cybersecurity impact before approval.',
        standard: 'Security review shall be mandatory for {{securityReviewThreshold}}. The assessment shall confirm that controls remain effective after the change, that logging continues, and that no new exposure is introduced. Findings shall be resolved before implementation or formally risk-accepted.',
        clauseOwners: ['cyber_analyst', 'cyber_analyst', 'system_owner'],
        guidance: 'Check that monitoring still functions after the change; changes that break log forwarding are rarely noticed until an investigation needs the logs.',
        controlName: 'Security impact assessment of change', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per qualifying change', kpi: '% of qualifying changes with a completed security assessment (target: 100%)',
        risk: 'A routine change removes a control, and the loss is discovered only during an incident.', riskRating: 'high',
        evidence: ['Security assessments attached to change records', 'Evidence of control validation after change', 'Risk acceptances for unresolved findings'],
        refs: { 'ISO-27001': ['A.8.32', 'A.5.8'], 'NCA-ECC': ['1-6', '1-5-3'], 'COBIT-2019': ['BAI06'] } },
      { key: 'config_baseline', title: 'Configuration baselines',
        policy: 'Approved configuration baselines shall be maintained for system classes, and deviations shall be detected and remediated.',
        standard: 'Baselines shall be version-controlled and reviewed {{configReviewFrequency}}. Configuration monitoring shall detect drift from baseline, and deviations shall be remediated or formally approved as a baseline change.',
        clauseOwners: ['it_manager', 'it_manager'],
        guidance: 'Manage baselines as code so that a deviation and its approval are both visible in version history.',
        controlName: 'Configuration baseline management', controlType: 'preventive', controlNature: 'technical',
        frequency: '{{configReviewFrequency}}', kpi: '% of systems compliant with their approved baseline (target: 95%)',
        risk: 'Systems drift into insecure configurations through incremental undocumented change.', riskRating: 'medium',
        evidence: ['Version-controlled baselines', 'Drift detection reports', 'Approved baseline change records'],
        refs: { 'ISO-27001': ['A.8.9'], 'CIS-V8': ['4'], 'NIST-800-53': ['CM-3'], 'NIST-CSF': ['PR.PS-01'], 'COBIT-2019': ['BAI10'] } },
      { key: 'emergency_change', title: 'Emergency change',
        policy: 'Emergency changes shall be permitted where delay would cause greater harm, and shall be reviewed retrospectively.',
        standard: 'Emergency changes shall be authorised by the IT Manager or CISO, recorded at the time of implementation where possible and within 24 hours otherwise, and reviewed by the change advisory board within {{emergencyChangeReviewSla}}. Repeated use of the emergency path for the same cause shall trigger a process review.',
        clauseOwners: ['it_manager', 'grc_manager'],
        guidance: 'Trend emergency change volume; a rising rate normally indicates the standard path is too slow rather than that emergencies are increasing.',
        controlName: 'Emergency change management', controlType: 'corrective', controlNature: 'administrative',
        frequency: 'Per emergency change', kpi: '% of emergency changes retrospectively reviewed within {{emergencyChangeReviewSla}} (target: 100%)',
        risk: 'The emergency path becomes the routine path, bypassing security assessment entirely.', riskRating: 'medium',
        evidence: ['Emergency change records with authorisation', 'Retrospective review records', 'Emergency change volume trend'],
        refs: { 'ISO-27001': ['A.8.32'], 'COBIT-2019': ['BAI06'], 'NIST-800-53': ['CM-3'] } },
      { key: 'unauthorised_change', title: 'Detection of unauthorised change',
        policy: 'Change applied outside the change process shall be detected and investigated rather than discovered at the next audit.',
        standard: 'Configuration drift on in-scope systems shall be detected automatically and reconciled against approved change records. An unexplained change shall be investigated within {{unauthorisedChangeSla}} and either authorised retrospectively with a recorded reason or reversed. Repeated unauthorised change by the same team shall be raised as a control failure rather than handled case by case, and suspected malicious change shall be escalated to the Incident Management process immediately.',
        clauseOwners: ['it_manager', 'cyber_analyst', 'grc_manager'],
        guidance: 'Reconcile drift against the change record automatically. The difference between a change nobody recorded and an intruder is only visible when you look promptly, and both need the same first question answered.',
        controlName: 'Unauthorised change detection', controlType: 'detective', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of detected configuration changes matched to an approved change record (target: 95%)',
        risk: 'Production is altered without review, and an intruder\'s change is indistinguishable from an undocumented one.', riskRating: 'high',
        evidence: ['Configuration drift detection reports reconciled to change records', 'Investigation records for unmatched changes', 'Control failure records for repeated occurrences'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.9', 'A.8.32'], 'NIST-800-53': ['CM-3', 'SI-4'], 'CIS-V8': ['4'] } },
      { key: 'patch_change_route', title: 'Patching within change management',
        policy: 'Security patching shall proceed on its own timetable, through a route that records the change without waiting for a scheduled advisory board.',
        standard: 'Security patches shall use {{patchChangeRoute}}. The route shall require testing proportionate to the risk, a recorded back-out position and a post-implementation check, but shall not require scheduling that would breach the remediation service level. Patches deferred past their service level shall become exceptions with a named owner and an expiry, visible in change reporting rather than only in vulnerability reporting.',
        clauseOwners: ['it_manager', 'it_manager', 'system_owner'],
        guidance: 'Where the change board and the patch service level conflict, the patch is late and the reason is process. A standing pre-approval for security patches resolves it without weakening the record.',
        controlName: 'Security patch change route', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Continuous', kpi: '% of security patches applied within the remediation service level (target: 95%)',
        risk: 'Patching waits for a change window, so the organisation is exposed for administrative reasons it has itself created.', riskRating: 'high',
        evidence: ['Standard change route definition for security patches', 'Patch change records with testing and back-out evidence', 'Deferral exceptions with owners and expiry dates'],
        refs: { 'NCA-ECC': ['2-10-3', '2-10-2'], 'ISO-27001': ['A.8.8', 'A.8.32'], 'NIST-800-53': ['CM-3', 'SI-2'], 'CIS-V8': ['7'] } },
      { key: 'change_verification', title: 'Post-implementation verification',
        policy: 'A change shall not be closed until the controls it touched have been confirmed to be operating.',
        standard: '{{releaseVerification}} shall be performed and recorded before closure, covering at minimum access rights, logging, encryption and monitoring where the change affected them. A change that cannot be verified shall be backed out rather than closed on assumption. Failed verification shall be recorded against the change and reported in change performance, so that a pattern of unverified closure is visible.',
        clauseOwners: ['cyber_analyst', 'it_manager', 'grc_manager'],
        guidance: 'The control most often broken by a change is logging, because nothing stops working visibly when it stops. Check that the events still arrive, not only that the service responds.',
        controlName: 'Post-implementation control verification', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Per change', kpi: '% of closed changes with recorded control verification (target: 95%)',
        risk: 'A change silently disables a control, and the gap persists until an audit or an incident finds it.', riskRating: 'medium',
        evidence: ['Verification records per change', 'Back-out records where verification failed', 'Change performance reporting including verification rate'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.32', 'A.8.9'], 'NIST-800-53': ['CM-3'] } },
      { key: 'change_segregation', title: 'Segregation of duties in change',
        policy: 'Building, approving and applying a change shall not rest with one person for changes to production systems.',
        standard: '{{segregationRule}} shall be enforced. Where team size makes full segregation impossible, a compensating control shall be recorded: peer review by a named reviewer outside the team, or post-implementation review by the control owner within one business day. Standing exceptions shall be recorded in the segregation-of-duties matrix and reviewed {{configReviewFrequency}}. Emergency changes remain subject to review after the fact under {{emergencyChangeReviewSla}}.',
        clauseOwners: ['it_manager', 'it_manager', 'grc_manager', 'grc_manager'],
        guidance: 'Small teams do not get an exemption, they get a compensating control. Write down which one applies, because being too small is not a control and does not survive an audit.',
        controlName: 'Segregation of duties in change management', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Reviewed {{configReviewFrequency}}', kpi: '% of production changes with separate builder and approver, or a recorded compensating control (target: 100%)',
        risk: 'One person changes production unreviewed, so error and deliberate misuse are equally undetectable.', riskRating: 'high',
        evidence: ['Change records showing distinct builder, approver and implementer', 'Segregation-of-duties matrix with recorded exceptions', 'Compensating review records where segregation is not possible'],
        refs: { 'NCA-ECC': ['2-10-3', '1-4-3'], 'ISO-27001': ['A.5.3', 'A.8.32'], 'NIST-800-53': ['AC-5', 'CM-3'] } },
      { key: 'change_freeze', title: 'Change freeze and release windows',
        policy: 'Periods of elevated business risk shall be protected by a change freeze, without preventing security response.',
        standard: '{{changeFreezeWindows}} shall be published in advance and agreed with the business. During a freeze, only emergency changes and security patches within their remediation service level shall proceed, each with recorded authorisation at the level defined for the freeze. Changes deferred by a freeze shall be rescheduled explicitly rather than dropped, and the backlog created shall be reported so that the freeze does not become an accumulating risk.',
        clauseOwners: ['business_owner', 'it_manager', 'it_manager'],
        guidance: 'A freeze that blocks security patching converts a business risk into a security one. Name the exemptions when you declare the freeze, not when the first patch is due.',
        controlName: 'Change freeze governance', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per freeze window', kpi: 'Number of non-exempt changes applied during a freeze without authorisation (target: 0)',
        risk: 'Change destabilises a service at the worst moment, or a freeze is used to justify leaving a known vulnerability unpatched.', riskRating: 'medium',
        evidence: ['Published freeze calendar with business agreement', 'Authorisation records for changes applied during a freeze', 'Deferred change backlog reporting'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.32'], 'NIST-800-53': ['CM-3'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Raise change', actor: 'System Owner', detail: 'Submit the change with description, justification, affected systems, implementation plan and back-out plan.' },
      { name: 'Classify', actor: 'IT Manager', detail: 'Classify as standard, normal or emergency, and determine whether security review is required.', decision: { question: 'Does the change meet {{securityReviewThreshold}}?', yes: 'Route for cybersecurity assessment', no: 'Proceed to change advisory board review' } },
      { name: 'Assess security impact', actor: 'Cybersecurity Analyst', detail: 'Assess the impact on controls, logging and exposure, and record findings on the change record.' },
      { name: 'Approve', actor: 'Change Advisory Board', detail: 'Approve, defer or reject at the {{cabFrequency}} board, confirming {{backoutRequirement}} is present.' },
      { name: 'Implement and verify', actor: 'IT Manager', detail: 'Implement within the approved window and verify that security controls and log forwarding remain effective.', decision: { question: 'Did post-implementation verification pass?', yes: 'Close the change', no: 'Invoke the back-out plan and record the failure' } },
      { name: 'Review', actor: 'Cybersecurity GRC Manager', detail: 'Review emergency changes within {{emergencyChangeReviewSla}} and investigate any change implemented without approval.' }
    ],
    inputs: [
      'Change requests with justification and affected systems',
      'Patches awaiting deployment under {{patchChangeRoute}}',
      'Configuration baselines and drift detection output',
      'Incident and problem records requiring a corrective change'
    ],
    outputs: [
      'Change records evidencing {{backoutRequirement}}',
      'Post-implementation verification results',
      'A change record trail supporting configuration audit'
    ],
    escalation: [
      'A change implemented without authorisation escalates to the Cybersecurity GRC Manager within {{unauthorisedChangeSla}}.',
      'An emergency change not reviewed within {{emergencyChangeReviewSla}} escalates to the CISO.',
      'Failed verification that cannot be backed out escalates to the Change Advisory Board and the system owner.'
    ],
    records: [
      'Change records with approvals and verification evidence (retained 3 years)',
      'Emergency and unauthorised change reviews (retained 3 years)',
      'Configuration baselines and approved deviations (retained for the life of the system)'
    ]
    },
    raciActivities: [
      raci('Define the change management process', 'Govern', 'A:ciso R:grc_manager C:it_manager C:system_owner'),
      raci('Raise and document changes', 'Operate', 'A:system_owner R:it_manager C:business_owner'),
      raci('Assess security impact of change', 'Protect', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Approve changes at the advisory board', 'Govern', 'A:it_manager R:system_owner C:ciso C:business_owner'),
      raci('Verify controls after implementation', 'Assure', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Detect and investigate unauthorised change', 'Detect', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Operate the security patch change route', 'Operate', 'A:it_manager R:system_owner C:cyber_analyst'),
      raci('Verify controls after implementation and close the change', 'Assure', 'A:system_owner R:it_manager C:cyber_analyst'),
      raci('Maintain segregation of duties in change', 'Govern', 'A:ciso R:grc_manager C:it_manager I:internal_auditor'),
      raci('Declare and govern change freeze windows', 'Govern', 'A:business_owner R:it_manager C:ciso'),
      raci('Review emergency and unauthorised changes', 'Assure', 'A:ciso R:grc_manager C:internal_auditor')
    ]
  }
};
