/** Canonical requirement models — data, supplier and cloud domains. */

export const DATA_DOMAINS = {
  third_party: {
    objectives: [
      'Ensure cybersecurity risk introduced by suppliers is assessed before engagement and managed throughout its life.',
      'Ensure security obligations are contractually binding and enforceable.',
      'Ensure supplier access and data are withdrawn cleanly at termination.'
    ],
    parameters: {
      dueDiligenceValidity: '12 months',
      criticalSupplierReviewFrequency: 'annually',
      supplierIncidentNotificationSla: '24 hours of the supplier becoming aware',
      offboardingSla: '30 days of contract termination',
      dataReturnSla: '30 days of contract termination',
      assuranceEvidenceTypes: 'an ISO/IEC 27001 certificate with a relevant scope statement, a SOC 2 Type II report, or a completed and validated security assessment'
    , criticalSupplierCriteria: 'access to Confidential or Secret data, connectivity into the network, or the delivery of a service a critical business activity depends on', subProcessorRule: 'disclosed before engagement and notified before any change, with the right to object where the change raises the risk', supplierRemoteWorkRule: 'supplier personnel working remotely shall meet the same remote access and device requirements as employees', fourthPartyReview: 'annually for critical suppliers, covering the suppliers they themselves depend on for the service', supplierExitTesting: 'the exit path tested or walked through annually for critical suppliers'},
    requirements: [
      { key: 'supplier_risk_tiering', title: 'Supplier risk classification',
        policy: 'Suppliers shall be classified by the cybersecurity risk they present, based on the data they access, the systems they connect to and the criticality of the service they provide.',
        standard: 'Classification shall be assigned before contract signature and reviewed on material change or at renewal. Critical and High tier suppliers require full due diligence; Low tier suppliers require a proportionate assessment. The supplier register shall record tier, data classification accessed, connectivity type and the accountable Business Owner.',
        guidance: 'Tier on data and connectivity rather than contract value; a low-value supplier with production database access is a critical supplier.',
        controlName: 'Supplier cybersecurity risk classification', controlType: 'directive', controlNature: 'administrative',
        frequency: 'At onboarding and at renewal', kpi: '% of active suppliers with an assigned risk tier (target: 100%)',
        risk: 'High-risk suppliers receive the same light-touch assurance as low-risk ones, leaving material exposure unassessed.',
        riskRating: 'high',
        evidence: ['Supplier register with tier and rationale', 'Tiering criteria document', 'Evidence of tier review at renewal'],
        refs: { 'NCA-ECC': ['4-1-1', '4-1-3'], 'ISO-27001': ['A.5.19', 'A.5.21'], 'NIST-CSF': ['GV.SC'], 'CIS-V8': ['15'], 'SAMA-CSF': ['4.1'] } },
      { key: 'due_diligence', title: 'Pre-contract due diligence',
        policy: 'Cybersecurity due diligence shall be completed and risks accepted before a supplier is granted access to {{orgName}} information or systems.',
        standard: 'Due diligence for Critical and High tier suppliers shall obtain {{assuranceEvidenceTypes}}. Assessment results shall remain valid for {{dueDiligenceValidity}}. Identified gaps shall be closed, contractually remediated, or formally accepted by the Business Owner and the CISO before access is granted.',
        guidance: 'Check the scope statement on a certificate, not only its existence — certificates frequently exclude the service actually being bought.',
        controlName: 'Pre-contract supplier due diligence', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'At onboarding, valid {{dueDiligenceValidity}}', kpi: '% of Critical and High tier suppliers with valid due diligence (target: 100%)',
        risk: 'Security weaknesses are inherited from the supplier with no leverage to correct them after signature.',
        riskRating: 'high',
        evidence: ['Completed due diligence assessments', 'Supplier certificates and audit reports with scope statements', 'Risk acceptance records for unremediated gaps'],
        refs: { 'NCA-ECC': ['4-1-1', '4-1-3'], 'ISO-27001': ['A.5.19'], 'NIST-CSF': ['GV.SC'], 'SAMA-CSF': ['4.1', '4.2'] } },
      { key: 'contract_clauses', title: 'Contractual security requirements',
        policy: 'Agreements with suppliers shall include cybersecurity requirements proportionate to the assessed risk, and shall be enforceable.',
        standard: 'Agreements shall address confidentiality and non-disclosure, permitted use and sub-processing, data location and residency, security control obligations, incident notification within {{supplierIncidentNotificationSla}}, the right to audit or receive independent assurance, personnel screening, and secure return or destruction of data at termination.',
        guidance: 'Specify the notification window in hours and name the recipient contact point; "promptly" is unenforceable and has been tested as such.',
        controlName: 'Cybersecurity clauses in supplier agreements', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per contract', kpi: '% of Critical and High tier contracts containing the required security clauses (target: 100%)',
        risk: 'Security expectations cannot be enforced, and the supplier is under no obligation to disclose a breach affecting {{orgName}} data.',
        riskRating: 'high',
        evidence: ['Contract clause library', 'Sampled executed contracts showing the required clauses', 'Non-disclosure agreements on file'],
        refs: { 'NCA-ECC': ['4-1-1', '4-1-2'], 'ISO-27001': ['A.5.20', 'A.6.6'], 'NIST-CSF': ['GV.SC'], 'SAMA-CSF': ['4.1'] } },
      { key: 'ongoing_assurance', title: 'Ongoing supplier assurance',
        policy: 'Supplier security performance shall be monitored throughout the life of the engagement, not assessed only at onboarding.',
        standard: 'Critical suppliers shall be reassessed {{criticalSupplierReviewFrequency}}, covering renewed assurance evidence, open findings from the previous cycle, incidents affecting the service and material changes to sub-processors or data location. Deterioration shall trigger a risk review and may trigger contractual remedies.',
        guidance: 'Track sub-processor changes explicitly; the risk profile frequently changes without any change to the contracted party.',
        controlName: 'Periodic supplier reassessment', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{criticalSupplierReviewFrequency}}', kpi: '% of Critical suppliers reassessed within the cycle (target: 100%)',
        risk: 'A supplier assessed as secure at onboarding degrades unnoticed over a multi-year contract.',
        riskRating: 'medium',
        evidence: ['Reassessment records for the current cycle', 'Updated assurance evidence', 'Findings register with supplier remediation status'],
        refs: { 'ISO-27001': ['A.5.22'], 'NCA-ECC': ['4-1-3'], 'NIST-CSF': ['GV.SC'], 'CIS-V8': ['15'] } },
      { key: 'supplier_incident', title: 'Supplier incident management',
        policy: 'Cybersecurity incidents at a supplier that affect {{orgName}} information or services shall be notified, assessed and managed under the {{orgName}} incident management process.',
        standard: 'Suppliers shall notify {{orgName}} within {{supplierIncidentNotificationSla}}. On notification, the incident shall be raised in the {{orgName}} incident management system, assessed for regulatory reportability, and managed jointly. Communication contacts shall be verified {{criticalSupplierReviewFrequency}}.',
        guidance: 'Test the notification path during supplier review; contact details for security incidents go stale faster than commercial ones.',
        controlName: 'Supplier incident notification and response', controlType: 'corrective', controlNature: 'administrative',
        frequency: 'Per incident', kpi: '% of supplier incidents notified within {{supplierIncidentNotificationSla}} (target: 100%)',
        risk: 'A breach of {{orgName}} data held by a supplier is discovered late, after the regulatory notification window has expired.',
        riskRating: 'high',
        evidence: ['Supplier incident notifications received with timestamps', 'Joint incident records', 'Verified supplier security contact list'],
        refs: { 'NCA-ECC': ['4-1-2', '2-13-3'], 'ISO-27001': ['A.5.20', 'A.5.24'], 'NIST-CSF': ['GV.SC'] } },
      { key: 'supplier_offboarding', title: 'Supplier offboarding',
        policy: 'On termination of a supplier engagement, all access shall be revoked and all {{orgName}} data returned or securely destroyed.',
        standard: 'Access shall be revoked within {{offboardingSla}} across remote access, application accounts, privileged vaults and physical access. Data shall be returned in an agreed format and securely destroyed within {{dataReturnSla}}, evidenced by a certificate of destruction. Offboarding completion shall be confirmed by the Business Owner.',
        guidance: 'Trigger offboarding from the contract register expiry date, not from a manual notification by the business.',
        controlName: 'Supplier offboarding and data return', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per termination', kpi: '% of terminated suppliers fully offboarded within {{offboardingSla}} (target: 100%)',
        risk: 'Former suppliers retain access and copies of data long after any business relationship justifies it.',
        riskRating: 'high',
        evidence: ['Offboarding checklists with completion dates', 'Certificates of destruction or data return confirmations', 'Access revocation evidence'],
        refs: { 'NCA-ECC': ['4-1-2'], 'ISO-27001': ['A.5.20', 'A.8.10'], 'NCA-CCC': ['4-2'], 'SAMA-CSF': ['4.2'] } },
      { key: 'critical_supplier_governance', title: 'Governance of critical suppliers',
        policy: 'Suppliers on whom the organisation critically depends shall be governed more closely than the rest of the supply base.',
        standard: 'Criticality shall be determined by {{criticalSupplierCriteria}}. A critical supplier shall have a named relationship owner within the business, a service review at least {{criticalSupplierReviewFrequency}} covering security performance as well as delivery, and its own entry in the risk register. Concentration, where several critical services rest on one supplier, shall be recorded as a risk with a treatment decision. Cloud service providers shall be assessed and contracted under these requirements as well as under the cloud requirements.',
        guidance: 'The supplier review that only covers delivery is the common failure. Put the security performance on the same agenda, with the same owner, or it is discussed nowhere.',
        controlName: 'Critical supplier governance', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{criticalSupplierReviewFrequency}}', kpi: '% of critical suppliers with a named owner and a completed security service review (target: 100%)',
        risk: 'A supplier the organisation cannot operate without is managed as an ordinary vendor, and its security posture is nobody\'s standing agenda item.', riskRating: 'high',
        evidence: ['Criticality determination records against the criteria', 'Service review minutes covering security performance', 'Concentration risk records with treatment decisions'],
        refs: { 'NCA-CSCC': ['4-1'], 'NCA-CCC': ['4-1'], 'NCA-ECC': ['4-1'], 'ISO-27001': ['A.5.19', 'A.5.22'], 'COBIT-2019': ['APO10'] } },
      { key: 'supplier_data_protection', title: 'Data protection in supplier engagements',
        policy: 'Information disclosed to a supplier shall remain subject to {{orgName}} protection requirements, and the chain of onward processing shall be known.',
        standard: 'The contract shall state the data disclosed, its classification, the permitted purposes, the permitted locations and the retention period. {{subProcessorRule}}. Transfers outside the agreed locations shall be prohibited without approval. Where personal data is involved, the lawful basis and the respective responsibilities shall be recorded, and the supplier shall be obliged to assist with data subject requests and with breach assessment within {{supplierIncidentNotificationSla}}.',
        guidance: 'Ask for the sub-processor list in writing before signing, not in the annual review. The fourth party holding your data is the one nobody assessed.',
        controlName: 'Data protection in supplier engagements', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per contract', kpi: '% of contracts disclosing data with recorded classification, purpose, location and sub-processors (target: 95%)',
        risk: 'Data is processed in an unknown location by an unassessed party, and the organisation cannot answer a regulator asking where it is.', riskRating: 'high',
        evidence: ['Contract terms recording data, classification, purpose, location and retention', 'Sub-processor disclosures and change notifications', 'Records of approvals for transfers outside agreed locations'],
        refs: { 'NCA-DCC': ['4-1'], 'NCA-ECC': ['4-1'], 'ISO-27001': ['A.5.19', 'A.5.34', 'A.5.14'], 'NCA-CCC': ['4-1'] } },
      { key: 'supplier_access_and_remote', title: 'Supplier access and remote working',
        policy: 'Supplier access shall be granted to named individuals, for a defined period, through the approved access path.',
        standard: 'Access shall be individually attributable, never through a shared supplier account, and shall expire with the contract term unless renewed. {{supplierRemoteWorkRule}}. Supplier personnel shall be recorded by name with their access, and the supplier shall be obliged to notify leavers so that access can be revoked within {{offboardingSla}}. Supplier activity on organisational systems shall be logged and reviewed at the same frequency as privileged internal activity.',
        guidance: 'The dangerous account is the shared one named after the supplier. It survives every one of their staff changes and cannot be attributed to anybody.',
        controlName: 'Supplier access control', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous, reviewed {{criticalSupplierReviewFrequency}}', kpi: '% of supplier access accounts attributable to a named individual (target: 100%)',
        risk: 'A shared supplier account persists after the individuals using it have left, with no means of telling who acted.', riskRating: 'high',
        evidence: ['Supplier personnel register with named accounts and expiry dates', 'Leaver notification records from suppliers with revocation evidence', 'Supplier activity logs and review records'],
        refs: { 'NCA-TCC': ['4'], 'NCA-ECC': ['4-1', '2-2-3-3'], 'NCA-CSCC': ['4-1'], 'ISO-27001': ['A.5.19', 'A.8.2'] } },
      { key: 'supplier_exit_testing', title: 'Exit and fourth-party dependency',
        policy: 'The organisation shall be able to leave a critical supplier, and shall know what that supplier itself depends on.',
        standard: '{{fourthPartyReview}} shall be conducted. An exit plan shall exist for each critical supplier, recording the data to be returned or destroyed, the format it will be returned in, the transition path and the notice period required. {{supplierExitTesting}} shall be performed, at least as a walkthrough, since an exit plan that has never been examined is an assumption. Supplier failure shall be a scenario in continuity planning, not only a contractual matter.',
        guidance: 'Ask what format the data comes back in. A promise to provide an export is not an answer you want to discover the meaning of during a contested termination.',
        controlName: 'Supplier exit and fourth-party dependency management', controlType: 'preventive', controlNature: 'administrative',
        frequency: '{{fourthPartyReview}}', kpi: '% of critical suppliers with a tested or walked-through exit plan (target: 90%)',
        risk: 'The organisation cannot leave a failing supplier, or is disrupted by a party it has no relationship with and never assessed.', riskRating: 'high',
        evidence: ['Fourth-party dependency reviews for critical suppliers', 'Exit plans recording data return format and transition path', 'Exit walkthrough or test records'],
        refs: { 'NCA-CSCC': ['4-1'], 'NCA-CCC': ['4-1'], 'ISO-27001': ['A.5.22', 'A.5.30'], 'COBIT-2019': ['APO10'], 'ISO-22301': ['8'] } }
    ],
    procedure: {
      purpose: 'To define how cybersecurity risk arising from third parties is assessed, contracted, monitored and terminated at {{orgName}}.',
      preconditions: ['The supplier register is operational.', 'The contract clause library is approved by Legal and the CISO.', 'Risk tiering criteria are published.'],
      inputs: ['Procurement request and service description', 'Data classification and connectivity requirements', 'Supplier assurance evidence', 'Contract renewal and termination notifications'],
      steps: [
        { name: 'Classify', actor: 'Cybersecurity GRC Manager', detail: 'Assign a supplier risk tier based on data accessed, connectivity required and service criticality.' },
        { name: 'Assess', actor: 'Cybersecurity Analyst', detail: 'Conduct due diligence proportionate to the tier, obtaining {{assuranceEvidenceTypes}} for Critical and High tier suppliers.', decision: { question: 'Does the supplier meet the required security posture?', yes: 'Proceed to Contract', no: 'Require remediation, contractual commitment, or formal risk acceptance before access' } },
        { name: 'Contract', actor: 'Legal / Business Owner', detail: 'Incorporate the required cybersecurity clauses, including incident notification within {{supplierIncidentNotificationSla}} and data return obligations.' },
        { name: 'Onboard', actor: 'IAM Specialist', detail: 'Provision time-bound, least-privilege access aligned to the contract term, through the approved remote access path.' },
        { name: 'Monitor', actor: 'Cybersecurity GRC Manager', detail: 'Reassess Critical suppliers {{criticalSupplierReviewFrequency}} and track open findings, incidents and sub-processor changes.', decision: { question: 'Has the supplier security posture deteriorated?', yes: 'Raise a risk review and consider contractual remedies', no: 'Record the assurance outcome and continue' } },
        { name: 'Offboard', actor: 'Business Owner / IAM Specialist', detail: 'On termination, revoke all access within {{offboardingSla}} and obtain evidence of data return or destruction within {{dataReturnSla}}.' }
      ],
      outputs: ['Tiered supplier register', 'Due diligence assessments and risk acceptances', 'Executed contracts with security clauses', 'Offboarding and data destruction evidence'],
      escalation: ['Suppliers granted access without completed due diligence escalate immediately to the CISO.', 'Supplier refusal to accept required security clauses escalates to the Business Owner and the CISO for risk acceptance.', 'Supplier incidents affecting {{orgName}} data escalate immediately to the Incident Management process.', 'Offboarding incomplete after {{offboardingSla}} escalates to the Cybersecurity GRC Manager.'],
      records: ['Supplier register and tiering rationale (retained for contract life plus 3 years)', 'Due diligence assessments (retained {{dueDiligenceValidity}} plus 3 years)', 'Certificates of destruction (retained 7 years)'],
      kpis: [{ name: 'Due diligence coverage', target: '100% of Critical and High tier suppliers' }, { name: 'Contract clause compliance', target: '100% of Critical and High tier contracts' }, { name: 'Reassessment completion', target: '100% of Critical suppliers {{criticalSupplierReviewFrequency}}' }, { name: 'Offboarding timeliness', target: '100% within {{offboardingSla}}' }]
    },
    roles: ['ciso', 'grc_manager', 'cyber_analyst', 'risk_manager', 'business_owner', 'it_manager', 'internal_auditor'],
    raciActivities: [
      { activity: 'Define and approve the Third-Party Security Policy', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', risk_manager: 'C', business_owner: 'I', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Classify supplier risk tier', phase: 'Govern', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'R', risk_manager: 'C', business_owner: 'C', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Conduct pre-contract due diligence', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'R', risk_manager: 'C', business_owner: 'C', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Negotiate cybersecurity contract clauses', phase: 'Protect', assign: { ciso: 'C', grc_manager: 'R', cyber_analyst: 'C', risk_manager: 'I', business_owner: 'A', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Accept residual supplier risk', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', risk_manager: 'R', business_owner: 'R', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Provision and manage supplier access', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'C', risk_manager: 'I', business_owner: 'C', it_manager: 'R', internal_auditor: 'I' } },
      { activity: 'Reassess critical suppliers', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'R', risk_manager: 'C', business_owner: 'C', it_manager: 'I', internal_auditor: 'C' } },
      { activity: 'Manage supplier security incidents', phase: 'Respond', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'R', risk_manager: 'C', business_owner: 'C', it_manager: 'C', internal_auditor: 'I' } },
      { activity: 'Offboard suppliers and confirm data destruction', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'C', risk_manager: 'I', business_owner: 'R', it_manager: 'R', internal_auditor: 'C' } },
      { activity: 'Govern critical supplier relationships', phase: 'Govern', assign: { ciso: 'C', grc_manager: 'R', cyber_analyst: 'I', risk_manager: 'C', business_owner: 'A', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Record data protection terms in supplier contracts', phase: 'Protect', assign: { ciso: 'C', grc_manager: 'A', cyber_analyst: 'I', risk_manager: 'C', business_owner: 'R', it_manager: 'I', internal_auditor: 'I' } },
      { activity: 'Control and review supplier access', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'C', risk_manager: 'I', business_owner: 'C', it_manager: 'R', internal_auditor: 'C' } },
      { activity: 'Maintain and test supplier exit plans', phase: 'Resilience', assign: { ciso: 'I', grc_manager: 'R', cyber_analyst: 'I', risk_manager: 'C', business_owner: 'A', it_manager: 'C', internal_auditor: 'I' } }
    ]
  },

  data_protection: {
    objectives: [
      'Classify information consistently and apply handling controls proportionate to classification.',
      'Prevent unauthorised disclosure, modification and loss of information across its lifecycle.',
      'Meet privacy and data residency obligations.'
    ],
    parameters: {
      classificationLevels: 'Public, Internal, Confidential and Secret',
      classificationReviewFrequency: 'annually',
      dlpCoverageTarget: '95% of managed endpoints and email gateways',
      retentionScheduleReviewFrequency: 'annually',
      dataResidency: 'inside the Kingdom of Saudi Arabia unless an approved exception applies',
      piiBreachAssessmentSla: '24 hours'
    , dataGovernanceOwner: 'a named data governance owner accountable for the classification scheme, the retention schedule and the register of processing', transferControls: 'encrypted in transit, sent only through approved channels, with the recipient and the lawful basis recorded for transfers outside the organisation', criticalDataProtection: 'enhanced controls for data supporting a critical system: encryption with customer-managed keys, access logged and reviewed monthly, and copies restricted to approved locations', teleworkDataRule: 'Confidential and Secret information handled remotely only on managed devices, through approved tooling, and not printed at home', dataProcessingRegister: 'the processing activities, their purposes, the categories of data and data subject, the recipients and the retention period'},
    requirements: [
      { key: 'classification_scheme', title: 'Information classification scheme',
        policy: 'All information shall be classified according to the {{orgName}} classification scheme of {{classificationLevels}}, and handled in line with the requirements for its level.',
        standard: 'Classification shall be assigned by the Information Owner at creation, based on the impact of unauthorised disclosure, modification or loss. Handling requirements shall be defined per level for storage, transmission, printing, sharing, retention and disposal. Classification shall be reviewed {{classificationReviewFrequency}} or on material change.',
        guidance: 'Publish a one-page handling matrix; a scheme that requires reading a policy to apply will not be applied.',
        controlName: 'Information classification and handling', controlType: 'directive', controlNature: 'administrative',
        frequency: 'At creation, reviewed {{classificationReviewFrequency}}', kpi: '% of registered information assets with an assigned classification (target: 100%)',
        risk: 'Sensitive information receives the same protection as public information, and controls cannot be targeted where they matter.',
        riskRating: 'high',
        evidence: ['Approved classification scheme and handling matrix', 'Classification assignments in the information asset register', 'Sample documents showing applied labels'],
        refs: { 'NCA-ECC': ['2-7-3', '2-1-4'], 'ISO-27001': ['A.5.12', 'A.5.13'], 'NCA-DCC': ['2-1'], 'CIS-V8': ['3'] } },
      { key: 'data_ownership', title: 'Information ownership and custodianship',
        policy: 'Every information asset shall have a named Information Owner accountable for classification, access decisions and retention, and a Custodian responsible for day-to-day protection.',
        standard: 'Ownership shall be recorded in the information asset register. Owners shall approve access to their information, authorise sharing outside {{orgName}} and approve retention and disposal decisions.',
        guidance: 'Separate owner from custodian explicitly; conflating them puts the accountability for data decisions with the team that merely operates the storage.',
        controlName: 'Information ownership assignment', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{classificationReviewFrequency}}', kpi: '% of information assets with a named owner (target: 100%)',
        risk: 'No one is accountable for deciding who may access sensitive data, so access defaults to whoever asks.',
        riskRating: 'medium',
        evidence: ['Information asset register with owners and custodians', 'Owner approval records for data sharing', 'Ownership attestation records'],
        refs: { 'NCA-ECC': ['2-7-3'], 'ISO-27001': ['A.5.9', 'A.5.12'], 'NCA-DCC': ['2-2'], 'COBIT-2019': ['APO14'] } },
      { key: 'data_leakage_prevention', title: 'Data leakage prevention',
        policy: 'Technical controls shall be implemented to detect and prevent the unauthorised transfer of Confidential and Secret information outside {{orgName}}.',
        standard: 'Data leakage prevention shall cover email, web upload, removable media and managed cloud storage, reaching {{dlpCoverageTarget}}. Policies shall be tuned to the classification scheme. Blocked and alerted events shall be reviewed, and repeated violations escalated to Human Resources under the disciplinary process.',
        guidance: 'Run in monitor mode first and tune against real traffic; blocking from day one generates business resistance that ends the programme.',
        controlName: 'Data leakage prevention', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: 'Data leakage prevention coverage (target: {{dlpCoverageTarget}})',
        risk: 'Confidential information leaves the organisation through everyday channels without any record that it did.',
        riskRating: 'high',
        evidence: ['Data leakage prevention policy configuration', 'Coverage report across channels', 'Event review records and escalations'],
        refs: { 'ISO-27001': ['A.8.12'], 'NCA-DCC': ['2-5'], 'NCA-ECC': ['2-7-2'], 'CIS-V8': ['3'] } },
      { key: 'data_retention', title: 'Retention, archiving and disposal',
        policy: 'Information shall be retained only for as long as required by business need, contract or law, and shall then be securely disposed of.',
        standard: 'A retention schedule shall define the retention period and disposal method for each information category, and shall be reviewed {{retentionScheduleReviewFrequency}}. Disposal shall render information irrecoverable. Legal holds shall suspend disposal and shall be recorded.',
        guidance: 'Implement disposal for the largest, most sensitive repositories first; an unenforced schedule creates liability without reducing it.',
        controlName: 'Information retention and secure disposal', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{retentionScheduleReviewFrequency}}', kpi: '% of information categories with a defined retention period (target: 100%)',
        risk: 'Data retained beyond its purpose expands the impact of any breach and may itself breach privacy obligations.',
        riskRating: 'medium',
        evidence: ['Approved retention schedule', 'Disposal records referencing the schedule', 'Legal hold register'],
        refs: { 'NCA-ECC': ['2-7-3'], 'ISO-27001': ['A.5.33', 'A.8.10'], 'NCA-DCC': ['2-6'], 'NIST-800-53': ['MP'] } },
      { key: 'privacy_protection', title: 'Privacy and protection of personal data',
        policy: 'Personal data shall be processed lawfully, minimised to what is necessary, and protected in line with applicable privacy legislation.',
        standard: 'Processing activities involving personal data shall be recorded, including purpose, lawful basis, categories of data subject, recipients and retention. Personal data shall be stored {{dataResidency}}. Suspected personal data breaches shall be assessed for notifiability within {{piiBreachAssessmentSla}} of detection.',
        guidance: 'Maintain the processing record as a live register rather than a periodic survey; it is the first artefact any privacy regulator requests.',
        controlName: 'Personal data protection', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Continuous, reviewed {{classificationReviewFrequency}}', kpi: '% of processing activities recorded in the register (target: 100%)',
        risk: 'Personal data is processed without a lawful basis or transferred outside permitted jurisdictions, attracting regulatory penalties.',
        riskRating: 'high',
        evidence: ['Record of processing activities', 'Data residency evidence for personal data stores', 'Personal data breach assessment records'],
        refs: { 'ISO-27001': ['A.5.34'], 'NCA-DCC': ['2-7'], 'NCA-ECC': ['2-7-3'], 'NIST-800-53': ['PT'] } },
      { key: 'data_masking', title: 'Masking of data in non-production environments',
        policy: 'Confidential and Secret information, including personal data, shall not be used in development, test or training environments unless masked, tokenised or synthesised.',
        standard: 'Non-production environments shall be populated with masked, tokenised or synthetic data. Where production data must be used, it shall require Information Owner approval, be time-bounded, and the environment shall be protected to production standard for the duration.',
        guidance: 'Provide a supported masking pipeline; without one, teams copy production data because it is the only way to test realistically.',
        controlName: 'Test data protection and masking', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Per environment refresh', kpi: 'Number of non-production environments holding unmasked production data (target: 0)',
        risk: 'Production data spreads into weakly controlled environments accessible to a much larger population.',
        riskRating: 'high',
        evidence: ['Masking configuration and pipeline documentation', 'Environment data classification records', 'Approvals for production data use in non-production'],
        refs: { 'ISO-27001': ['A.8.11', 'A.8.33'], 'NCA-DCC': ['2-9'], 'NCA-ECC': ['2-7-2'] } },
      { key: 'data_governance', title: 'Data cybersecurity governance and ownership',
        policy: 'Responsibility for the protection of information shall be assigned at organisational level, not only per system.',
        standard: '{{dataGovernanceOwner}} shall be appointed. A data cybersecurity strategy and its supporting policies shall be approved and reviewed {{classificationReviewFrequency}}, stating how classification, retention, residency and disposal are decided across the organisation rather than negotiated per project. {{dataProcessingRegister}} shall be maintained and reviewed {{retentionScheduleReviewFrequency}}. Roles for data owner, data custodian and data user shall be defined with their respective decisions named.',
        guidance: 'Without a single owner for the scheme, each project invents its own classification and the labels stop meaning the same thing across the organisation.',
        controlName: 'Data governance and ownership at organisational level', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{classificationReviewFrequency}}', kpi: '% of processing activities recorded in the register with a named owner (target: 95%)',
        risk: 'Data protection decisions are made inconsistently per project, and no single view exists of what the organisation holds or why.', riskRating: 'high',
        evidence: ['Appointment of the data governance owner', 'Approved data cybersecurity strategy and policies with review records', 'Register of processing activities with owners'],
        refs: { 'NCA-DCC': ['1-1', '1-2', '1-3'], 'NCA-ECC': ['2-7-1'], 'ISO-27001': ['A.5.1', 'A.5.9', 'A.5.34'], 'NCA-CSCC': ['2-6'] } },
      { key: 'information_transfer', title: 'Information transfer',
        policy: 'Information shall be transferred only through approved channels, with protection appropriate to its classification.',
        standard: 'Transfers shall meet {{transferControls}}. Approved channels shall be published per classification, and the use of personal email, consumer file-sharing or removable media for Confidential or Secret information shall be prohibited and technically prevented where possible. Transfer agreements shall be in place with recurring external recipients. Bulk extraction shall require the data owner\'s approval, be logged, and be reported in the data leakage monitoring rather than treated as routine.',
        guidance: 'Publish the approved channels per classification, plainly. Most unapproved transfer happens because the approved path was unclear and a deadline was near.',
        controlName: 'Controlled information transfer', controlType: 'preventive', controlNature: 'hybrid',
        frequency: 'Continuous', kpi: '% of detected Confidential or Secret transfers using an approved channel (target: 95%)',
        risk: 'Sensitive information leaves through consumer services with no record, no encryption and no recipient assurance.', riskRating: 'high',
        evidence: ['Published approved channels per classification', 'Transfer agreements with recurring recipients', 'Logs and approvals for bulk extraction'],
        refs: { 'ISO-27001': ['A.5.14', 'A.8.12'], 'NCA-ECC': ['2-7-1'], 'NCA-DCC': ['2-5'], 'NCA-TCC': ['2-4'] } },
      { key: 'critical_data_protection', title: 'Protection of data in critical systems',
        policy: 'Data held in or produced by a critical system shall receive protection proportionate to the consequence of its loss.',
        standard: '{{criticalDataProtection}} shall apply. Copies, extracts and reports derived from such data shall inherit its classification and shall be inventoried, since a spreadsheet extract is frequently the least protected copy in existence. Access shall be reviewed monthly against continued business need. Cross-border transfer of this data shall require approval against {{dataResidency}} and shall be recorded.',
        guidance: 'Follow the extracts. The database is usually well protected; the weekly report someone mails to themselves is not, and it holds the same data.',
        controlName: 'Enhanced protection of critical system data', controlType: 'preventive', controlNature: 'hybrid',
        frequency: 'Monthly', kpi: '% of critical system data stores and known extracts under enhanced controls (target: 95%)',
        risk: 'The primary store is protected while extracts of the same data circulate with none of its controls.', riskRating: 'critical',
        evidence: ['Enhanced control evidence per critical data store', 'Inventory of extracts and derived reports with classification', 'Monthly access review records'],
        refs: { 'NCA-CSCC': ['2-6'], 'NCA-DCC': ['2-4'], 'NCA-ECC': ['2-7-1'], 'ISO-27001': ['A.5.12', 'A.8.12'] } },
      { key: 'remote_data_handling', title: 'Handling information away from the office',
        policy: 'Information handled away from {{orgName}} premises shall remain under the same classification requirements.',
        standard: '{{teleworkDataRule}} shall apply. Where remote printing or physical handling is unavoidable, the disposal route shall be stated and the individual made responsible for it. Collaboration tooling used remotely shall be limited to the approved set, and content shared through it shall be subject to the same leakage monitoring as internal channels. Personal device use shall either be prohibited for Confidential and Secret information or brought under management with the same enforcement.',
        guidance: 'Say what happens to a document printed at home. The unanswered question in most remote policies is disposal, and the honest answer is usually that nobody knows.',
        controlName: 'Remote information handling', controlType: 'preventive', controlNature: 'hybrid',
        frequency: 'Reviewed {{classificationReviewFrequency}}', kpi: '% of remote Confidential and Secret handling on managed devices through approved tooling (target: 95%)',
        risk: 'Classified information is handled on unmanaged devices and disposed of in a domestic bin, outside every control the organisation operates.', riskRating: 'high',
        evidence: ['Approved remote tooling list with enforcement evidence', 'Managed device coverage for remote handling', 'Leakage monitoring coverage of collaboration channels'],
        refs: { 'NCA-TCC': ['2-4'], 'NCA-ECC': ['2-7-1'], 'ISO-27001': ['A.6.7', 'A.5.14', 'A.7.7'], 'NCA-DCC': ['2-5'] } }
    ],
    procedure: {
      purpose: 'To define how information is classified, labelled, handled, retained and disposed of at {{orgName}}.',
      preconditions: ['The classification scheme and handling matrix are approved.', 'Information Owners are nominated for each information asset.', 'The retention schedule is current.'],
      inputs: ['Newly created or acquired information assets', 'Data sharing and transfer requests', 'Retention schedule', 'Data leakage prevention alerts'],
      steps: [
        { name: 'Identify', actor: 'Information Owner', detail: 'Register the information asset with its purpose, format, location and volume.' },
        { name: 'Classify and label', actor: 'Information Owner', detail: 'Assign one of {{classificationLevels}} based on disclosure, modification and loss impact, and apply the corresponding label.' },
        { name: 'Apply handling controls', actor: 'IT Manager / Custodian', detail: 'Apply the storage, transmission, access and encryption requirements defined for the assigned level.', decision: { question: 'Is the information Confidential or above?', yes: 'Apply encryption at rest and in transit and enable data leakage prevention', no: 'Apply baseline handling controls' } },
        { name: 'Authorise sharing', actor: 'Information Owner', detail: 'Approve any transfer outside {{orgName}}, confirming the recipient agreement, transfer mechanism and residency requirements are satisfied.' },
        { name: 'Monitor', actor: 'Cybersecurity Analyst', detail: 'Review data leakage prevention events and investigate policy violations.', decision: { question: 'Does the event indicate unauthorised disclosure?', yes: 'Raise a cybersecurity incident', no: 'Close with rationale and tune the policy if a false positive' } },
        { name: 'Retain and dispose', actor: 'Information Owner / Custodian', detail: 'Retain per the retention schedule and dispose securely on expiry, unless a legal hold applies.' }
      ],
      outputs: ['Classified and labelled information assets', 'Applied handling controls', 'Approved transfer records', 'Disposal evidence'],
      escalation: ['Suspected unauthorised disclosure of Confidential or Secret information escalates immediately to the Incident Management process.', 'Personal data breaches escalate to Legal and the CISO within {{piiBreachAssessmentSla}}.', 'Unmasked production data found in non-production escalates to the Information Owner and the Cybersecurity GRC Manager.'],
      records: ['Information asset register (retained for asset life plus 3 years)', 'Transfer approvals (retained 3 years)', 'Disposal records (retained 7 years)'],
      kpis: [{ name: 'Classification coverage', target: '100% of registered information assets' }, { name: 'Data leakage prevention coverage', target: '{{dlpCoverageTarget}}' }, { name: 'Retention schedule currency', target: 'Reviewed within {{retentionScheduleReviewFrequency}}' }]
    },
    roles: ['ciso', 'grc_manager', 'cyber_analyst', 'it_manager', 'asset_owner', 'business_owner', 'internal_auditor'],
    raciActivities: [
      { activity: 'Define and approve the Data Protection Policy', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', it_manager: 'C', asset_owner: 'I', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Maintain the classification scheme and handling matrix', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', it_manager: 'I', asset_owner: 'C', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Classify and label information assets', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'I', it_manager: 'I', asset_owner: 'A', business_owner: 'R', internal_auditor: 'I' } },
      { activity: 'Apply handling and encryption controls', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'C', it_manager: 'R', asset_owner: 'A', business_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Operate data leakage prevention', phase: 'Detect', assign: { ciso: 'A', grc_manager: 'I', cyber_analyst: 'R', it_manager: 'R', asset_owner: 'I', business_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Approve external data sharing', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'I', it_manager: 'I', asset_owner: 'A', business_owner: 'R', internal_auditor: 'I' } },
      { activity: 'Maintain the retention schedule and dispose of data', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'I', it_manager: 'R', asset_owner: 'R', business_owner: 'C', internal_auditor: 'C' } },
      { activity: 'Own data governance at organisational level', phase: 'Govern', assign: { ciso: 'C', grc_manager: 'R', cyber_analyst: 'I', it_manager: 'I', asset_owner: 'A', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Publish and enforce approved transfer channels', phase: 'Protect', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', it_manager: 'R', asset_owner: 'C', business_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Apply enhanced protection to critical system data', phase: 'Protect', assign: { ciso: 'C', grc_manager: 'C', cyber_analyst: 'R', it_manager: 'R', asset_owner: 'A', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Govern information handling away from the office', phase: 'Protect', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', it_manager: 'C', asset_owner: 'C', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Audit data protection controls', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'I', it_manager: 'I', asset_owner: 'I', business_owner: 'I', internal_auditor: 'R' } }
    ]
  }
};
