/** Canonical requirement models — technical protection domains. */
import { raci } from './req-helpers.js';

export const TECH_DOMAINS = {
  cryptography: {
    objectives: ['Protect information in transit and at rest using approved cryptography.', 'Manage keys securely across their full lifecycle.', 'Retire weak algorithms before they become exploitable.'],
    parameters: { approvedAlgorithms: 'AES-256 for symmetric encryption, RSA-3072 or ECDSA P-256 and above for asymmetric operations, and SHA-256 or stronger for hashing', minTlsVersion: 'TLS 1.2, with TLS 1.3 preferred', keyRotationFrequency: 'annually, or immediately on suspected compromise', certificateExpiryAlert: '30 days before expiry', cryptoReviewFrequency: 'annually', keyStorage: 'a hardware security module or an approved key management service' },
    requirements: [
      { key: 'approved_crypto', title: 'Approved cryptographic algorithms',
        policy: 'Only cryptographic algorithms, protocols and key lengths approved by {{orgName}} shall be used to protect information.',
        standard: 'Approved cryptography comprises {{approvedAlgorithms}}. Network transmission shall use {{minTlsVersion}}. Deprecated algorithms and protocols shall be disabled. The approved list shall be reviewed {{cryptoReviewFrequency}} against national and international guidance.',
        guidance: 'Maintain an inventory of where each algorithm is used; algorithm retirement is otherwise impossible to plan or verify.',
        controlName: 'Approved cryptographic standards', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Reviewed {{cryptoReviewFrequency}}', kpi: '% of in-scope services using approved algorithms and protocol versions (target: 98%)',
        risk: 'Weak or deprecated cryptography is broken, exposing data that was assumed protected.', riskRating: 'high',
        evidence: ['Approved algorithm standard', 'Configuration scan results for TLS and cipher suites', 'Deprecation plan for legacy algorithms'],
        refs: { 'NCA-ECC': ['2-8-1', '2-8-3'], 'ISO-27001': ['A.8.24'], 'NIST-800-53': ['SC-13', 'SC-8'], 'SAMA-CSF': ['3.9'] } },
      { key: 'encryption_at_rest', title: 'Encryption of data at rest and in transit',
        policy: 'Confidential and Secret information shall be encrypted at rest and in transit.',
        standard: 'Encryption at rest shall be applied to databases, file stores, backups, removable media and endpoint storage holding Confidential or Secret information. Encryption in transit shall be applied to all traffic traversing untrusted networks and to internal traffic carrying Confidential or Secret information.',
        guidance: 'Full-disk encryption protects against device loss but not against an authenticated attacker; apply database or field-level encryption where the threat is a compromised application.',
        controlName: 'Encryption of sensitive information', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of Confidential and Secret data stores encrypted at rest (target: 100%)',
        risk: 'Sensitive data is readable directly from storage media, backups or intercepted network traffic.', riskRating: 'high',
        evidence: ['Encryption configuration evidence per data store', 'TLS configuration scan results', 'Backup encryption evidence'],
        refs: { 'NCA-ECC': ['2-8-3'], 'ISO-27001': ['A.8.24'], 'NIST-800-53': ['SC-28', 'SC-8'], 'NIST-CSF': ['PR.DS-01', 'PR.DS-02'], 'NCA-DCC': ['2-4'] } },
      { key: 'key_management', title: 'Cryptographic key management',
        policy: 'Cryptographic keys shall be generated, distributed, stored, rotated, archived and destroyed under a documented key management process.',
        standard: 'Keys shall be generated with an approved random source and stored in {{keyStorage}}. Keys shall be rotated {{keyRotationFrequency}}. Key custodians shall be named, with dual control for the most sensitive keys. Key compromise shall be handled as a cybersecurity incident.',
        guidance: 'Test the key recovery path before relying on encryption for critical data; unrecoverable keys have caused more data loss than key compromise.',
        controlName: 'Cryptographic key lifecycle management', controlType: 'preventive', controlNature: 'technical',
        frequency: '{{keyRotationFrequency}}', kpi: '% of production keys held in {{keyStorage}} (target: 100%)',
        risk: 'Keys are lost, rendering data unrecoverable, or disclosed, rendering encryption ineffective.', riskRating: 'critical',
        evidence: ['Key inventory with custodians and rotation dates', 'Key management system configuration', 'Key recovery test records'],
        refs: { 'NCA-ECC': ['2-8-3'], 'ISO-27001': ['A.8.24'], 'NIST-800-53': ['SC-13'], 'NCA-CCC': ['2-4'], 'SAMA-CSF': ['3.9'] } },
      { key: 'certificate_management', title: 'Certificate management',
        policy: 'Digital certificates shall be inventoried, monitored and renewed before expiry.',
        standard: 'All certificates shall be recorded with owner, subject, issuer, expiry date and the service they protect. Expiry alerts shall be issued {{certificateExpiryAlert}}. Private keys shall never be shared between environments, and certificates shall be revoked promptly on compromise or decommissioning.',
        guidance: 'Certificate expiry is one of the most frequent causes of unplanned outage; automated renewal removes the failure mode rather than managing it.',
        controlName: 'Digital certificate management', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: 'Number of unplanned outages caused by certificate expiry (target: 0)',
        risk: 'Expired certificates cause service outage, and unmanaged certificates enable interception.', riskRating: 'medium',
        evidence: ['Certificate inventory with expiry dates', 'Expiry alerting configuration', 'Revocation records'],
        refs: { 'ISO-27001': ['A.8.24'], 'NCA-ECC': ['2-8-3'], 'NIST-800-53': ['SC-13'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Identify requirement', actor: 'System Owner', detail: 'Determine the cryptographic protection required from the data classification and the transmission path.' },
      { name: 'Select approved cryptography', actor: 'Security Architect', detail: 'Select from {{approvedAlgorithms}} and confirm protocol versions meet {{minTlsVersion}}.', decision: { question: 'Is the proposed cryptography on the approved list?', yes: 'Proceed to key provisioning', no: 'Escalate to the CISO for assessment or select an approved alternative' } },
      { name: 'Provision keys', actor: 'Security Architect', detail: 'Generate keys with an approved random source and store them in {{keyStorage}} with named custodians.' },
      { name: 'Implement', actor: 'IT Manager', detail: 'Apply encryption to the data store or transmission path and validate by configuration scan.' },
      { name: 'Monitor', actor: 'Cybersecurity Analyst', detail: 'Scan for deprecated algorithms and protocol versions, and monitor certificate expiry with alerts {{certificateExpiryAlert}}.' },
      { name: 'Rotate and retire', actor: 'Security Architect', detail: 'Rotate keys {{keyRotationFrequency}} and retire deprecated algorithms under the change process.' }
    ] },
    raciActivities: [
      raci('Define approved cryptographic standards', 'Govern', 'A:ciso R:grc_manager C:it_manager C:cyber_analyst'),
      raci('Implement encryption at rest and in transit', 'Protect', 'A:system_owner R:it_manager C:cyber_analyst'),
      raci('Manage cryptographic keys', 'Protect', 'A:ciso R:it_manager C:cyber_analyst I:internal_auditor'),
      raci('Manage certificates and renewals', 'Operate', 'A:it_manager R:system_owner C:cyber_analyst'),
      raci('Scan for deprecated cryptography', 'Assure', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Audit cryptographic controls', 'Assure', 'A:risk_manager R:internal_auditor C:ciso')
    ]
  },

  network_security: {
    objectives: ['Segment networks to limit the reach of a compromise.', 'Control traffic at trust boundaries.', 'Secure remote and wireless access.'],
    parameters: { firewallReviewFrequency: 'semi-annually', segmentationModel: 'separate zones for user, server, management, industrial and third-party traffic, with critical systems isolated', remoteAccessMethod: 'the approved VPN or zero-trust access gateway with multi-factor authentication', wirelessEncryption: 'WPA3-Enterprise, or WPA2-Enterprise where WPA3 is not supported', ruleExpiryReview: 'annually' },
    requirements: [
      { key: 'segmentation', title: 'Network segmentation',
        policy: 'Networks shall be logically or physically segmented, and systems processing critical or Confidential information shall be isolated from general-purpose network segments.',
        standard: 'Segmentation shall implement {{segmentationModel}}. Traffic between zones shall pass through an enforcement point that denies by default. Management interfaces shall reside on a dedicated management network not reachable from user segments.',
        guidance: 'Segment the management plane first; flat management access converts any single compromise into an estate-wide one.',
        controlName: 'Network segmentation and isolation', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous, reviewed {{firewallReviewFrequency}}', kpi: '% of critical systems in an isolated segment (target: 100%)',
        risk: 'An attacker who compromises one workstation reaches every system on a flat network.', riskRating: 'critical',
        evidence: ['Network architecture diagram showing zones', 'Firewall or access control list configuration between zones', 'Segmentation validation test results'],
        refs: { 'NCA-ECC': ['2-5-1', '2-5-3'], 'ISO-27001': ['A.8.22', 'A.8.20'], 'NIST-800-53': ['SC-8'], 'CIS-V8': ['12'], 'SAMA-CSF': ['3.8'] } },
      { key: 'perimeter_control', title: 'Perimeter and traffic filtering',
        policy: 'Traffic crossing network trust boundaries shall be filtered and permitted only where a documented business need exists.',
        standard: 'Firewall rule sets shall deny by default. Each rule shall record a business justification, owner and review date. Rules shall be reviewed {{firewallReviewFrequency}} and unused rules removed {{ruleExpiryReview}}. Direct internet exposure of management protocols shall be prohibited.',
        guidance: 'Attach an expiry date to every rule added for a project; rule sets grow monotonically without one.',
        controlName: 'Network traffic filtering', controlType: 'preventive', controlNature: 'technical',
        frequency: '{{firewallReviewFrequency}}', kpi: '% of firewall rules with a recorded justification and owner (target: 95%)',
        risk: 'Rule sets accumulate permissive entries until the perimeter no longer restricts anything meaningful.', riskRating: 'high',
        evidence: ['Firewall rule base export with justifications', 'Rule review records', 'External exposure scan results'],
        refs: { 'NCA-ECC': ['2-5-3'], 'ISO-27001': ['A.8.20', 'A.8.21'], 'CIS-V8': ['12'], 'NIST-800-53': ['SC-8'] } },
      { key: 'remote_access', title: 'Secure remote access',
        policy: 'Remote access to {{orgName}} networks shall be established only through approved, authenticated and encrypted channels.',
        standard: 'Remote access shall use {{remoteAccessMethod}}. Split tunnelling shall be disabled for access to Confidential or Secret systems. Devices shall meet the endpoint compliance baseline before access is granted, and sessions shall be logged.',
        guidance: 'Enforce device posture at connection rather than trusting the user alone; credentials used from an unmanaged device are the common bypass.',
        controlName: 'Secure remote access', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of remote sessions authenticated with multi-factor authentication (target: 100%)',
        risk: 'Remote access becomes an unmonitored, weakly authenticated route directly into internal networks.', riskRating: 'high',
        evidence: ['Remote access gateway configuration', 'Device compliance policy evidence', 'Remote session logs'],
        refs: { 'NCA-ECC': ['2-2-3-2', '2-5-3'], 'ISO-27001': ['A.6.7', 'A.8.20'], 'NIST-800-53': ['AC-17'], 'NCA-TCC': ['2-2'] } },
      { key: 'wireless_security', title: 'Wireless network security',
        policy: 'Wireless networks shall be secured, segregated by purpose, and monitored for unauthorised access points.',
        standard: 'Corporate wireless shall use {{wirelessEncryption}} with certificate or directory-based authentication. Guest wireless shall be isolated from corporate networks with no route to internal systems. Rogue access point detection shall operate continuously.',
        guidance: 'Isolate guest wireless at the network layer rather than relying on client isolation alone.',
        controlName: 'Wireless network security', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: 'Number of unauthorised access points not removed within 48 hours of detection (target: 0)',
        risk: 'An unauthorised access point provides an unmonitored bridge into the corporate network.', riskRating: 'medium',
        evidence: ['Wireless configuration evidence', 'Guest network isolation verification', 'Rogue access point detection reports'],
        refs: { 'NCA-ECC': ['2-5-3'], 'ISO-27001': ['A.8.20', 'A.8.21'], 'CIS-V8': ['12'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Design', actor: 'Security Architect', detail: 'Define the required zone, trust boundary and enforcement point for the system, following {{segmentationModel}}.' },
      { name: 'Request rule', actor: 'System Owner', detail: 'Submit a firewall rule request with source, destination, service, business justification and required duration.' },
      { name: 'Review', actor: 'Cybersecurity Analyst', detail: 'Assess the request against the segmentation model and least-privilege principles.', decision: { question: 'Does the rule cross a critical trust boundary?', yes: 'Escalate to the Security Architect and CISO for approval', no: 'Approve at the delegated level' } },
      { name: 'Implement', actor: 'IT Manager', detail: 'Implement the rule through the Change Management process, recording owner and review date.' },
      { name: 'Verify', actor: 'Cybersecurity Analyst', detail: 'Confirm the rule behaves as intended and does not expose management protocols externally.' },
      { name: 'Review periodically', actor: 'Security Architect', detail: 'Review the rule base {{firewallReviewFrequency}} and remove unused or expired rules {{ruleExpiryReview}}.' }
    ] },
    raciActivities: [
      raci('Define the network security architecture', 'Govern', 'A:ciso R:grc_manager C:it_manager C:cyber_analyst'),
      raci('Approve firewall rule changes', 'Protect', 'A:it_manager R:cyber_analyst C:system_owner'),
      raci('Implement network segmentation', 'Protect', 'A:it_manager R:system_owner C:cyber_analyst I:ciso'),
      raci('Operate secure remote access', 'Protect', 'A:it_manager R:system_owner C:cyber_analyst'),
      raci('Detect rogue access points', 'Detect', 'A:ciso R:cyber_analyst C:it_manager'),
      raci('Review the firewall rule base', 'Assure', 'A:grc_manager R:cyber_analyst C:it_manager C:internal_auditor')
    ]
  },

  endpoint_security: {
    objectives: ['Harden endpoints to a defined baseline.', 'Detect and prevent malicious code.', 'Control removable media and mobile devices.'],
    parameters: { baselineStandard: 'the approved {{orgName}} hardening baseline derived from the CIS Benchmarks', malwareSignatureUpdate: 'at least daily, with automatic update enabled', edrCoverageTarget: '98% of managed endpoints', mobileEncryption: 'device-level encryption with a passcode and remote wipe capability', removableMediaPolicy: 'blocked by default, with write access permitted only on encrypted approved media', baselineReviewFrequency: 'annually' },
    requirements: [
      { key: 'endpoint_hardening', title: 'Endpoint hardening baseline',
        policy: 'Endpoints shall be configured to an approved security baseline before being placed into service.',
        standard: 'Baselines shall follow {{baselineStandard}} for each supported platform, covering account configuration, service reduction, logging, local firewall and application control. Compliance shall be monitored continuously and drift remediated. Baselines shall be reviewed {{baselineReviewFrequency}}.',
        guidance: 'Monitor drift continuously rather than auditing periodically; configuration returns to insecure defaults through routine support activity.',
        controlName: 'Endpoint security baseline', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous, reviewed {{baselineReviewFrequency}}', kpi: '% of endpoints compliant with the approved baseline (target: 95%)',
        risk: 'Default configurations leave unnecessary services and weak settings exposed on every endpoint.', riskRating: 'high',
        evidence: ['Approved baseline documents per platform', 'Configuration compliance reports', 'Drift remediation records'],
        refs: { 'NCA-ECC': ['2-3-1', '2-3-3'], 'ISO-27001': ['A.8.1', 'A.8.9'], 'CIS-V8': ['4'], 'NIST-CSF': ['PR.PS-01'] } },
      { key: 'malware_protection', title: 'Malware protection',
        policy: 'Advanced and up-to-date protection against malicious code shall be deployed on all endpoints and servers.',
        standard: 'Endpoint detection and response shall be deployed to at least {{edrCoverageTarget}}. Signatures and detection content shall update {{malwareSignatureUpdate}}. Tamper protection shall prevent local disabling. Detections shall be forwarded to the central monitoring platform.',
        guidance: 'Alert on agents that stop reporting; an uninstalled agent produces no alerts and looks identical to a clean endpoint.',
        controlName: 'Malware protection', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: 'Endpoint detection and response coverage (target: {{edrCoverageTarget}})',
        risk: 'Malicious code executes undetected, providing an attacker with a durable foothold.', riskRating: 'critical',
        evidence: ['Endpoint agent coverage report', 'Signature and content currency report', 'Tamper protection configuration'],
        refs: { 'NCA-ECC': ['2-3-3'], 'ISO-27001': ['A.8.7'], 'CIS-V8': ['10'], 'NIST-800-53': ['SI-2'] } },
      { key: 'removable_media', title: 'Removable media control',
        policy: 'The use of removable storage media shall be restricted and controlled.',
        standard: 'Removable media shall be {{removableMediaPolicy}}. Approved use shall require Information Owner authorisation and shall be logged. Media holding Confidential or Secret information shall be encrypted and securely disposed of at end of life.',
        guidance: 'Provide a sanctioned file transfer alternative when blocking media; otherwise users route around the control through personal cloud storage.',
        controlName: 'Removable media control', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of endpoints with the removable media policy enforced (target: 98%)',
        risk: 'Large volumes of data leave the organisation on devices that leave no trace.', riskRating: 'medium',
        evidence: ['Removable media policy configuration', 'Approved exception register', 'Media usage logs'],
        refs: { 'NCA-ECC': ['2-3-3'], 'ISO-27001': ['A.7.10', 'A.8.12'], 'NIST-800-53': ['MP'] } },
      { key: 'mobile_devices', title: 'Mobile device security',
        policy: 'Mobile devices accessing {{orgName}} information shall be enrolled in mobile device management and protected in line with the classification of information accessed.',
        standard: 'Enrolled devices shall enforce {{mobileEncryption}}, screen lock, operating system currency and application control. Corporate data shall be held in a managed container permitting selective wipe. Jailbroken or rooted devices shall be denied access.',
        guidance: 'Selective wipe of the corporate container avoids the dispute that full-device wipe creates on personally owned devices.',
        controlName: 'Mobile device management', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of mobile devices accessing corporate data that are enrolled and compliant (target: 100%)',
        risk: 'Corporate data on lost or personally owned devices is accessible with no ability to remove it.', riskRating: 'high',
        evidence: ['Mobile device management enrolment report', 'Compliance policy configuration', 'Remote wipe records'],
        refs: { 'NCA-ECC': ['2-6'], 'ISO-27001': ['A.8.1', 'A.6.7'], 'SAMA-CSF': ['3.10'], 'NCA-TCC': ['2-3'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Build', actor: 'IT Manager', detail: 'Build the endpoint from the approved image and apply {{baselineStandard}}.' },
      { name: 'Deploy protection', actor: 'IT Manager', detail: 'Install endpoint detection and response with tamper protection and confirm telemetry reaches the monitoring platform.', decision: { question: 'Is the endpoint reporting to the monitoring platform?', yes: 'Release to the user', no: 'Withhold release until telemetry is confirmed' } },
      { name: 'Enrol', actor: 'IT Manager', detail: 'Enrol mobile devices in mobile device management and apply {{mobileEncryption}}.' },
      { name: 'Monitor compliance', actor: 'Cybersecurity Analyst', detail: 'Monitor baseline compliance and agent health, and investigate endpoints that stop reporting.' },
      { name: 'Remediate drift', actor: 'IT Manager', detail: 'Restore configuration to baseline and record the cause of drift.' },
      { name: 'Decommission', actor: 'IT Manager', detail: 'Wipe corporate data, remove enrolment and sanitise storage before disposal or re-use.' }
    ] },
    raciActivities: [
      raci('Define the endpoint hardening baseline', 'Govern', 'A:ciso R:grc_manager C:it_manager C:cyber_analyst'),
      raci('Deploy and maintain endpoint protection', 'Protect', 'A:it_manager R:system_owner C:cyber_analyst'),
      raci('Monitor baseline compliance and agent health', 'Detect', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Control removable media use', 'Protect', 'A:it_manager R:cyber_analyst C:business_owner'),
      raci('Manage mobile device enrolment', 'Protect', 'A:it_manager R:system_owner C:business_owner'),
      raci('Audit endpoint controls', 'Assure', 'A:risk_manager R:internal_auditor C:ciso')
    ]
  },

  application_security: {
    objectives: ['Define security requirements for applications before development or purchase.', 'Test applications for security defects before and after release.', 'Protect production applications from attack.'],
    parameters: { appTestFrequency: 'before each major release and at least annually', criticalAppFindingSla: '15 days', wafMode: 'blocking mode for internet-facing applications', apiAuthStandard: 'OAuth 2.0 with short-lived tokens, or mutual TLS for service-to-service calls', appInventoryReviewFrequency: 'quarterly' },
    requirements: [
      { key: 'app_requirements', title: 'Application security requirements',
        policy: 'Security requirements shall be defined and agreed before an application is developed, purchased or materially changed.',
        standard: 'Requirements shall cover authentication, authorisation, session management, input validation, output encoding, error handling, logging, cryptography and data protection, derived from a recognised application security standard. Requirements shall be recorded as acceptance criteria and verified before release.',
        guidance: 'Express requirements as testable acceptance criteria; requirements written as principles are not verifiable at release.',
        controlName: 'Application security requirements definition', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per project or material change', kpi: '% of in-scope applications with documented security requirements (target: 100%)',
        risk: 'Security is retrofitted after design, at high cost and with poor coverage.', riskRating: 'high',
        evidence: ['Security requirements per application', 'Acceptance criteria in the project record', 'Verification evidence before release'],
        refs: { 'NCA-ECC': ['2-15', '1-6'], 'ISO-27001': ['A.8.26', 'A.5.8'], 'CIS-V8': ['16'], 'SAMA-CSF': ['3.6'] } },
      { key: 'app_testing', title: 'Application security testing',
        policy: 'Applications shall be tested for security vulnerabilities before release to production and periodically thereafter.',
        standard: 'Testing shall include static analysis, dependency and component analysis, and dynamic testing appropriate to the application. Internet-facing and critical applications shall be tested {{appTestFrequency}}. Critical findings shall be remediated within {{criticalAppFindingSla}} and verified before release.',
        guidance: 'Gate the release on critical findings rather than on a completed scan; a scan whose findings are not acted on adds no assurance.',
        controlName: 'Application security testing', controlType: 'detective', controlNature: 'technical',
        frequency: '{{appTestFrequency}}', kpi: '% of releases with completed security testing and no open critical findings (target: 95%)',
        risk: 'Exploitable defects reach production, where they are discovered by attackers rather than by testing.', riskRating: 'high',
        evidence: ['Static and dynamic test reports', 'Dependency analysis results', 'Release gate records showing finding closure'],
        refs: { 'NCA-ECC': ['2-15'], 'ISO-27001': ['A.8.29', 'A.8.26'], 'CIS-V8': ['16'], 'NIST-800-53': ['SA-11'] } },
      { key: 'app_protection', title: 'Production application protection',
        policy: 'Internet-facing applications shall be protected by controls that detect and block common attack techniques.',
        standard: 'A web application firewall shall operate in {{wafMode}} for internet-facing applications, tuned to the application and monitored. Application programming interfaces shall authenticate using {{apiAuthStandard}} and enforce rate limiting. Application security events shall be forwarded to the monitoring platform.',
        guidance: 'Run in detection mode only long enough to tune; a firewall left permanently in monitor mode provides visibility but no protection.',
        controlName: 'Production application protection', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of internet-facing applications behind a tuned web application firewall in {{wafMode}} (target: 100%)',
        risk: 'Common web attacks reach the application directly, exploiting defects that testing did not find.', riskRating: 'high',
        evidence: ['Web application firewall configuration and mode evidence', 'Application inventory with protection status', 'Application security event forwarding evidence'],
        refs: { 'NCA-ECC': ['2-15'], 'ISO-27001': ['A.8.26'], 'CIS-V8': ['16'], 'SAMA-CSF': ['3.6'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Define requirements', actor: 'Security Architect', detail: 'Define testable security requirements as acceptance criteria for the application or change.' },
      { name: 'Design review', actor: 'Security Architect', detail: 'Review the design against the requirements and identify threats to the application.', decision: { question: 'Does the design meet the security requirements?', yes: 'Proceed to build', no: 'Return for redesign or record a risk-accepted deviation' } },
      { name: 'Test', actor: 'Cybersecurity Analyst', detail: 'Run static, dependency and dynamic testing appropriate to the application.' },
      { name: 'Remediate', actor: 'System Owner', detail: 'Remediate critical findings within {{criticalAppFindingSla}} and verify closure.', decision: { question: 'Are critical findings still open?', yes: 'Block the release until remediated or formally risk-accepted', no: 'Approve for release' } },
      { name: 'Protect', actor: 'IT Manager', detail: 'Deploy behind a web application firewall in {{wafMode}} and confirm event forwarding to monitoring.' },
      { name: 'Reassess', actor: 'Cybersecurity Analyst', detail: 'Retest {{appTestFrequency}} and on material change.' }
    ] },
    raciActivities: [
      raci('Define application security requirements', 'Govern', 'A:ciso R:grc_manager C:system_owner C:it_manager'),
      raci('Conduct security design review', 'Protect', 'A:grc_manager R:cyber_analyst C:system_owner'),
      raci('Perform application security testing', 'Assure', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Remediate application findings', 'Protect', 'A:system_owner R:it_manager C:cyber_analyst'),
      raci('Operate application protection controls', 'Protect', 'A:it_manager R:system_owner C:cyber_analyst'),
      raci('Approve release with open risk', 'Govern', 'A:ciso R:business_owner C:risk_manager C:grc_manager')
    ]
  },

  secure_sdlc: {
    objectives: ['Embed security throughout the development lifecycle.', 'Separate environments and control access to source code.', 'Assure the security of outsourced development.'],
    parameters: { codeReviewCoverage: '100% of changes to production code', secretScanFrequency: 'on every commit', envSeparation: 'physically or logically separate development, test and production environments with no shared credentials', trainingFrequency: 'annually for all developers', pipelineGate: 'a mandatory security gate that blocks promotion on critical findings' },
    requirements: [
      { key: 'secure_development', title: 'Secure development lifecycle',
        policy: 'Security shall be integrated into each phase of the development lifecycle for software developed by or for {{orgName}}.',
        standard: 'The lifecycle shall define security activities for requirements, design, implementation, testing, release and maintenance, including threat modelling for critical applications and secure coding standards per language. Developers shall complete secure development training {{trainingFrequency}}.',
        guidance: 'Automate the gates in the pipeline; lifecycle requirements enforced by review meetings are skipped under delivery pressure.',
        controlName: 'Secure development lifecycle', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per release, training {{trainingFrequency}}', kpi: '% of developers with current secure development training (target: 95%)',
        risk: 'Security defects are introduced systematically and found only after release.', riskRating: 'high',
        evidence: ['Secure development lifecycle documentation', 'Secure coding standards per language', 'Training completion records', 'Threat models for critical applications'],
        refs: { 'ISO-27001': ['A.8.25', 'A.8.27', 'A.8.28'], 'NCA-ECC': ['2-15', '1-6'], 'NIST-800-53': ['SA-11'], 'CIS-V8': ['16'] } },
      { key: 'code_control', title: 'Source code and pipeline protection',
        policy: 'Access to source code and build pipelines shall be restricted, and changes shall be reviewed before merge to production branches.',
        standard: 'Repositories shall enforce branch protection with mandatory peer review covering {{codeReviewCoverage}}. Secret scanning shall run {{secretScanFrequency}}, and detected secrets shall be revoked, not merely removed from the code. Build pipelines shall enforce {{pipelineGate}}, and pipeline credentials shall be scoped to the minimum required.',
        guidance: 'A secret committed to history remains valid until revoked; removing the commit is not remediation.',
        controlName: 'Source code and pipeline access control', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: '% of production repositories with branch protection and secret scanning enabled (target: 100%)',
        risk: 'The build pipeline becomes a route to inject code directly into production, bypassing every application control.', riskRating: 'critical',
        evidence: ['Repository access and branch protection configuration', 'Secret scanning results and revocation records', 'Pipeline gate configuration'],
        refs: { 'ISO-27001': ['A.8.4', 'A.8.28'], 'NCA-ECC': ['2-15'], 'CIS-V8': ['16'], 'NIST-800-53': ['SA-11'] } },
      { key: 'environment_separation', title: 'Environment separation',
        policy: 'Development, test and production environments shall be separated, and production data shall not be used in non-production environments without protection.',
        standard: 'Environments shall implement {{envSeparation}}. Developers shall not hold standing privileged access to production. Test data shall be masked or synthetic in line with the Data Protection Standard.',
        guidance: 'Shared credentials between environments are the most common form of separation failure and are not visible on an architecture diagram.',
        controlName: 'Development environment separation', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Continuous', kpi: 'Number of shared credentials between production and non-production (target: 0)',
        risk: 'A compromise of a weakly controlled development environment provides a direct path into production.', riskRating: 'high',
        evidence: ['Environment architecture and access control evidence', 'Credential separation verification', 'Test data masking evidence'],
        refs: { 'ISO-27001': ['A.8.31', 'A.8.33'], 'NCA-ECC': ['2-15'], 'NCA-DCC': ['2-9'] } },
      { key: 'outsourced_development', title: 'Outsourced development',
        policy: 'Security requirements shall be imposed on, and verified for, software developed by third parties.',
        standard: 'Contracts shall require adherence to {{orgName}} secure coding standards, the right to test, disclosure of components used, and remediation obligations with defined timeframes. Delivered code shall be tested independently before acceptance.',
        guidance: 'Require a software bill of materials at delivery; without it, component vulnerabilities in delivered code cannot be tracked.',
        controlName: 'Outsourced development security', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per engagement', kpi: '% of outsourced deliveries independently security tested before acceptance (target: 100%)',
        risk: 'Vulnerable or malicious code enters the estate through a supplier with no contractual obligation to fix it.', riskRating: 'high',
        evidence: ['Contract clauses for outsourced development', 'Independent test results before acceptance', 'Software bill of materials for delivered code'],
        refs: { 'ISO-27001': ['A.8.30', 'A.5.21'], 'NCA-ECC': ['4-1-1'], 'NIST-800-53': ['SA-11', 'SR'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Plan', actor: 'System Owner', detail: 'Define security requirements and, for critical applications, produce a threat model.' },
      { name: 'Develop', actor: 'Development team', detail: 'Implement against the secure coding standard, with peer review covering {{codeReviewCoverage}}.' },
      { name: 'Scan', actor: 'Build pipeline', detail: 'Run static analysis, dependency scanning and secret scanning {{secretScanFrequency}}.', decision: { question: 'Are critical findings or secrets detected?', yes: 'Block promotion; revoke any exposed secret and remediate', no: 'Promote to test' } },
      { name: 'Test', actor: 'Cybersecurity Analyst', detail: 'Perform dynamic security testing in the test environment against masked data.' },
      { name: 'Approve release', actor: 'Security Architect', detail: 'Confirm the security gate is satisfied and no critical findings remain open.', decision: { question: 'Is the security gate satisfied?', yes: 'Approve promotion to production', no: 'Return to development or obtain formal risk acceptance' } },
      { name: 'Maintain', actor: 'System Owner', detail: 'Monitor component vulnerabilities post-release and remediate under the vulnerability management service levels.' }
    ] },
    raciActivities: [
      raci('Define the secure development lifecycle', 'Govern', 'A:ciso R:grc_manager C:system_owner C:it_manager'),
      raci('Enforce code review and branch protection', 'Protect', 'A:system_owner R:it_manager C:cyber_analyst'),
      raci('Operate pipeline security gates', 'Protect', 'A:it_manager R:cyber_analyst C:system_owner'),
      raci('Maintain environment separation', 'Protect', 'A:it_manager R:system_owner C:cyber_analyst I:ciso'),
      raci('Assure outsourced development security', 'Assure', 'A:grc_manager R:cyber_analyst C:business_owner'),
      raci('Approve release with residual risk', 'Govern', 'A:ciso R:system_owner C:risk_manager')
    ]
  },

  physical_security: {
    objectives: ['Protect facilities housing information processing from unauthorised physical access.', 'Protect equipment from environmental threats.', 'Control physical access records and visitors.'],
    parameters: { accessReviewFrequency: 'quarterly', visitorEscortRequirement: 'continuous escort within secure areas', cctvRetention: '90 days', environmentalMonitoring: 'temperature, humidity, water ingress, smoke and power monitoring with alerting', badgeRevocationSla: 'the effective leaving time' },
    requirements: [
      { key: 'perimeter', title: 'Physical security perimeters and entry control',
        policy: 'Physical security perimeters shall protect areas containing information and information processing facilities, and entry shall be controlled and recorded.',
        standard: 'Secure areas shall require authenticated entry using an access badge, with access granted on documented approval by the facility owner. Access rights shall be reviewed {{accessReviewFrequency}} and revoked by {{badgeRevocationSla}} on termination. Entry and exit events shall be logged and retained for 12 months.',
        guidance: 'Reconcile badge holders against the HR register on the same cycle as logical access review; physical access is frequently missed in leaver processing.',
        controlName: 'Physical perimeter and entry control', controlType: 'preventive', controlNature: 'physical',
        frequency: 'Continuous, reviewed {{accessReviewFrequency}}', kpi: '% of secure-area access rights recertified within the cycle (target: 100%)',
        risk: 'Unauthorised physical access defeats logical controls entirely, giving direct access to systems and media.', riskRating: 'high',
        evidence: ['Access control system configuration and badge holder list', 'Access review records', 'Entry and exit logs for secure areas'],
        refs: { 'NCA-ECC': ['2-14'], 'ISO-27001': ['A.7.1', 'A.7.2', 'A.7.3'], 'NIST-800-53': ['PE'], 'SAMA-CSF': ['3.2'] } },
      { key: 'visitor_control', title: 'Visitor management',
        policy: 'Visitors to {{orgName}} facilities shall be identified, authorised, recorded and escorted in secure areas.',
        standard: 'Visitors shall present identification, be registered against a named host, wear a visibly distinct badge, and be subject to {{visitorEscortRequirement}}. Visitor records shall be retained for 12 months. Third-party engineers requiring access to secure areas shall have their work authorised in advance.',
        guidance: 'Record the specific work authorised for engineer visits; unrestricted access granted for one task is a routine audit finding.',
        controlName: 'Visitor access control', controlType: 'preventive', controlNature: 'physical',
        frequency: 'Per visit', kpi: '% of secure-area visits with a recorded host and escort (target: 100%)',
        risk: 'An unescorted visitor gains access to equipment, media or unattended screens.', riskRating: 'medium',
        evidence: ['Visitor register', 'Escort policy and badge design', 'Engineer work authorisation records'],
        refs: { 'ISO-27001': ['A.7.2', 'A.7.6'], 'NCA-ECC': ['2-14'], 'NIST-800-53': ['PE'] } },
      { key: 'physical_monitoring', title: 'Physical monitoring and environmental protection',
        policy: 'Facilities housing information processing shall be monitored for unauthorised access and protected against environmental threats.',
        standard: 'Secure areas shall be monitored by video surveillance with recordings retained for {{cctvRetention}}, and by intrusion detection. Environmental protection shall include {{environmentalMonitoring}}, with supporting utilities protected and tested. Alerts shall route to a monitored location at all times.',
        guidance: 'Test the alert path rather than only the sensors; alerts routing to an unmonitored mailbox is a common and consequential failure.',
        controlName: 'Physical monitoring and environmental controls', controlType: 'detective', controlNature: 'physical',
        frequency: 'Continuous', kpi: '% of secure areas with tested environmental alerting (target: 100%)',
        risk: 'Environmental failure destroys equipment and data, or intrusion goes unnoticed and unrecorded.', riskRating: 'medium',
        evidence: ['Surveillance coverage and retention configuration', 'Environmental monitoring and alert test records', 'Supporting utility test records'],
        refs: { 'ISO-27001': ['A.7.4', 'A.7.5', 'A.7.11'], 'NCA-ECC': ['2-14'], 'NIST-800-53': ['PE'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Define zones', actor: 'Facility Owner', detail: 'Define physical security zones and the entry requirements for each, based on the sensitivity of what they contain.' },
      { name: 'Authorise access', actor: 'Facility Owner', detail: 'Approve badge access on documented business need, recording the approval against the individual.', decision: { question: 'Is access to a secure area requested?', yes: 'Require facility owner and CISO approval', no: 'Approve at the delegated level' } },
      { name: 'Issue and control', actor: 'IT Manager', detail: 'Issue the badge with the approved permissions and register it against the individual.' },
      { name: 'Manage visitors', actor: 'Reception / Host', detail: 'Register visitors against a named host, issue a distinct badge and apply {{visitorEscortRequirement}}.' },
      { name: 'Monitor', actor: 'Cybersecurity Analyst', detail: 'Monitor surveillance, intrusion and environmental alerts, and investigate anomalies.' },
      { name: 'Review and revoke', actor: 'Facility Owner', detail: 'Review access {{accessReviewFrequency}} and revoke by {{badgeRevocationSla}} on termination.' }
    ] },
    raciActivities: [
      raci('Define physical security zones', 'Govern', 'A:ciso R:it_manager C:business_owner C:grc_manager'),
      raci('Authorise physical access', 'Protect', 'A:business_owner R:it_manager C:ciso'),
      raci('Manage visitor access', 'Operate', 'A:business_owner R:it_manager I:grc_manager'),
      raci('Monitor surveillance and environmental alerts', 'Detect', 'A:it_manager R:cyber_analyst I:ciso'),
      raci('Review physical access rights', 'Assure', 'A:grc_manager R:business_owner C:it_manager C:internal_auditor'),
      raci('Audit physical security controls', 'Assure', 'A:risk_manager R:internal_auditor C:ciso')
    ]
  }
};
