/** Canonical requirement models — governance, risk, awareness and change. */
import { raci } from './req-helpers.js';

export const GOVERN_DOMAINS = {
  governance: {
    objectives: [
      'Establish executive direction, authority and accountability for cybersecurity.',
      'Maintain a coherent, approved and current policy framework.',
      'Demonstrate compliance with applicable laws, regulations and standards.'
    ],
    parameters: { policyReviewFrequency: 'annually', committeeFrequency: 'quarterly', strategyHorizon: 'three years', complianceReviewFrequency: 'annually', auditFrequency: 'annually', policyApprovalAuthority: 'the Cybersecurity Steering Committee' },
    requirements: [
      { key: 'cyber_strategy', title: 'Cybersecurity strategy',
        policy: 'A cybersecurity strategy shall be defined, approved by executive management and aligned to {{orgName}} business objectives and regulatory obligations.',
        standard: 'The strategy shall cover a {{strategyHorizon}} horizon, define target capability levels, and be supported by a funded roadmap with named owners. Progress shall be reported to {{policyApprovalAuthority}} {{committeeFrequency}} and the strategy refreshed at least {{policyReviewFrequency}}.',
        guidance: 'Tie each roadmap item to a specific regulatory or risk driver so funding decisions can be defended at the board table.',
        controlName: 'Approved cybersecurity strategy', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed {{policyReviewFrequency}}', kpi: '% of roadmap milestones delivered on schedule (target: 85%)',
        risk: 'Security investment is reactive and disconnected from business risk, producing capability gaps in the areas that matter most.', riskRating: 'high',
        evidence: ['Approved cybersecurity strategy document', 'Roadmap with owners and milestone status', 'Steering Committee minutes recording approval'],
        refs: { 'NCA-ECC': ['1-1'], 'ISO-27001': ['5.2', '6'], 'NIST-CSF': ['GV.OC', 'GV.RM'], 'SAMA-CSF': ['1.2'], 'COBIT-2019': ['EDM01', 'APO13'] } },
      { key: 'policy_framework', title: 'Cybersecurity policy framework',
        policy: 'Cybersecurity policies, standards and procedures shall be defined, documented, approved by {{policyApprovalAuthority}}, communicated to relevant parties and reviewed at least {{policyReviewFrequency}}.',
        standard: 'The framework shall follow the hierarchy of Policy, Standard, Procedure and Work Instruction, with each lower tier traceable to the tier above. Every document shall record an owner, approver, version, effective date, review date and classification. Documents overdue for review shall be reported to {{policyApprovalAuthority}}.',
        guidance: 'Keep normative obligations in the policy and measurable parameters in the standard; mixing them causes the two to drift apart at the next review.',
        controlName: 'Cybersecurity policy framework management', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{policyReviewFrequency}}', kpi: '% of governance documents within their review date (target: 95%)',
        risk: 'Staff follow outdated or contradictory instructions, and the framework proves unenforceable under audit.', riskRating: 'high',
        evidence: ['Document register with owners, versions and review dates', 'Approval records for the current versions', 'Evidence of communication to affected personnel'],
        refs: { 'NCA-ECC': ['1-3-1', '1-3-2', '1-3-3'], 'ISO-27001': ['A.5.1', 'A.5.37', '7.5'], 'NIST-CSF': ['GV.PO-01', 'GV.PO-02'], 'SAMA-CSF': ['1.3'] } },
      { key: 'roles_authority', title: 'Cybersecurity roles, responsibilities and authority',
        policy: 'Cybersecurity roles and responsibilities shall be defined, documented, approved and assigned to named individuals, with sufficient authority to discharge them.',
        standard: 'The cybersecurity organisational structure shall be approved by executive management and shall preserve independence between the function that implements controls and the function that assures them. Responsibilities shall be documented in role descriptions and reflected in RACI matrices for each domain. Assignments shall be reviewed {{policyReviewFrequency}}.',
        guidance: 'Ensure the cybersecurity function does not report to the function it assures; this is the most common structural finding in regulatory reviews.',
        controlName: 'Defined cybersecurity roles and responsibilities', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{policyReviewFrequency}}', kpi: '% of defined cybersecurity roles with a named, current holder (target: 100%)',
        risk: 'Controls have no accountable owner, so failures are identified but never remediated.', riskRating: 'high',
        evidence: ['Approved organisational structure', 'Role descriptions with responsibilities and authority', 'Domain RACI matrices', 'Review records of role assignments'],
        refs: { 'NCA-ECC': ['1-4-1', '1-4-2', '1-4-3'], 'ISO-27001': ['A.5.2', '5.3'], 'NIST-CSF': ['GV.RR-02'], 'SAMA-CSF': ['1.4'] } },
      { key: 'compliance_management', title: 'Compliance with laws, regulations and standards',
        policy: 'Applicable cybersecurity laws, regulations, standards and contractual obligations shall be identified, tracked and demonstrably complied with.',
        standard: 'A compliance obligations register shall record each obligation, its source, the accountable owner and the controls that satisfy it. Compliance shall be assessed at least {{complianceReviewFrequency}}, with gaps recorded, risk-rated and tracked to closure. Regulatory change shall be assessed for impact within 30 days of publication.',
        guidance: 'Map obligations to operating controls rather than to documents; a policy statement is not evidence of compliance, an operating control is.',
        controlName: 'Regulatory compliance management', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{complianceReviewFrequency}}', kpi: '% of obligations with mapped controls and a current assessment (target: 100%)',
        risk: 'A regulatory requirement is missed entirely, surfacing first as a finding from the regulator.', riskRating: 'critical',
        evidence: ['Compliance obligations register', 'Latest compliance assessment results', 'Gap remediation plans with owners and due dates'],
        refs: { 'NCA-ECC': ['1-7'], 'ISO-27001': ['A.5.31', 'A.5.36'], 'COBIT-2019': ['MEA03'], 'SAMA-CSF': ['2.2', '2.3'] } },
      { key: 'review_audit', title: 'Periodic cybersecurity review and audit',
        policy: 'The implementation of cybersecurity controls shall be reviewed periodically by the cybersecurity function and audited independently.',
        standard: 'Internal cybersecurity reviews shall be conducted {{complianceReviewFrequency}} and independent audits {{auditFrequency}}. Audit findings shall be risk-rated, assigned to a named owner with a due date, and tracked to closure. Results shall be reported to {{policyApprovalAuthority}} and, where required, to the regulator.',
        guidance: 'Track audit findings in the same register as post-incident and assessment actions; separate registers hide the total remediation backlog.',
        controlName: 'Cybersecurity review and independent audit', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{auditFrequency}}', kpi: '% of audit findings closed by their due date (target: 90%)',
        risk: 'Control degradation goes undetected between regulatory inspections.', riskRating: 'high',
        evidence: ['Internal review reports', 'Independent audit reports', 'Findings register with closure evidence', 'Committee minutes recording results'],
        refs: { 'NCA-ECC': ['1-8'], 'ISO-27001': ['9.2', '9.3', 'A.5.35'], 'COBIT-2019': ['MEA02', 'MEA04'], 'SAMA-CSF': ['2.4', '2.5'] } }
    ],
    procedureSeed: {
      purpose: 'To define how the {{orgName}} cybersecurity governance framework is established, approved, communicated, reviewed and assured.',
      steps: [
        { name: 'Identify need', actor: 'Cybersecurity GRC Manager', detail: 'Identify the need for a new or revised governance document from regulatory change, risk assessment, audit finding or incident lesson.' },
        { name: 'Draft', actor: 'Cybersecurity GRC Manager', detail: 'Draft against the approved template, ensuring traceability to framework requirements and to the tier above in the hierarchy.' },
        { name: 'Consult', actor: 'Domain stakeholders', detail: 'Circulate for review to affected owners, IT, Legal and Risk, and resolve comments.', decision: { question: 'Are all material comments resolved?', yes: 'Submit for approval', no: 'Iterate the draft or escalate the disagreement to the CISO' } },
        { name: 'Approve', actor: '{{policyApprovalAuthority}}', detail: 'Approve the document, recording approver, date and version.' },
        { name: 'Publish and communicate', actor: 'Cybersecurity GRC Manager', detail: 'Publish to the document repository and communicate to affected personnel, recording acknowledgement where required.' },
        { name: 'Monitor compliance', actor: 'Cybersecurity Analyst', detail: 'Assess compliance with the document {{complianceReviewFrequency}} and record gaps as findings.' },
        { name: 'Review', actor: 'Document Owner', detail: 'Review at least {{policyReviewFrequency}}, or earlier on material change, and reissue or retire the document.' }
      ]
    },
    raciActivities: [
      raci('Approve the cybersecurity strategy', 'Govern', 'A:ciso R:grc_manager C:risk_manager C:it_manager'),
      raci('Draft cybersecurity policies and standards', 'Govern', 'A:grc_manager R:cyber_analyst C:ciso C:it_manager'),
      raci('Approve the policy framework', 'Govern', 'A:ciso R:grc_manager C:risk_manager'),
      raci('Communicate policies to personnel', 'Govern', 'A:grc_manager R:cyber_analyst C:business_owner'),
      raci('Maintain the compliance obligations register', 'Assure', 'A:grc_manager R:cyber_analyst C:risk_manager C:internal_auditor'),
      raci('Conduct internal cybersecurity review', 'Assure', 'A:ciso R:grc_manager C:cyber_analyst I:internal_auditor'),
      raci('Conduct independent audit', 'Assure', 'A:risk_manager R:internal_auditor C:ciso C:grc_manager'),
      raci('Track findings to closure', 'Assure', 'A:grc_manager R:system_owner C:internal_auditor C:risk_manager')
    ]
  },

  risk_management: {
    objectives: [
      'Identify and assess cybersecurity risk consistently across the organisation.',
      'Treat risk in line with the approved risk appetite.',
      'Ensure accepted risk is visible, owned and time-bound.'
    ],
    parameters: { riskAssessmentFrequency: 'annually and on material change', riskRegisterReviewFrequency: 'quarterly', riskAcceptanceMaxDuration: '12 months', criticalRiskEscalation: 'the Cybersecurity Steering Committee within 5 business days', riskMethodology: 'a documented impact and likelihood matrix calibrated to the {{orgName}} risk appetite' },
    requirements: [
      { key: 'risk_methodology', title: 'Risk management methodology',
        policy: 'A cybersecurity risk management methodology shall be defined, documented and approved, and applied consistently across {{orgName}}.',
        standard: 'The methodology shall define {{riskMethodology}}, asset and threat identification, vulnerability assessment, risk evaluation criteria, treatment options and acceptance authority by risk level. It shall align to the enterprise risk framework so that cybersecurity risk is comparable with other risk types.',
        guidance: 'Calibrate impact bands in currency and service-downtime terms the business already uses, so cyber risk is comparable at the board table.',
        controlName: 'Cybersecurity risk management methodology', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed annually', kpi: '% of risk assessments applying the approved methodology (target: 100%)',
        risk: 'Risks are rated inconsistently, so prioritisation and acceptance decisions cannot be relied upon.', riskRating: 'high',
        evidence: ['Approved risk methodology document', 'Risk evaluation criteria and appetite statement', 'Sample assessments demonstrating consistent application'],
        refs: { 'NCA-ECC': ['1-5-1', '1-5-2'], 'ISO-27001': ['6.1.2', '6.1.3'], 'ISO-27005': ['7'], 'NIST-CSF': ['GV.RM'], 'COBIT-2019': ['APO12'], 'SAMA-CSF': ['2.1'] } },
      { key: 'risk_assessment', title: 'Cybersecurity risk assessment',
        policy: 'Cybersecurity risk assessments shall be conducted {{riskAssessmentFrequency}}, and before significant technology change, new projects and outsourcing arrangements.',
        standard: 'Assessments shall identify assets in scope, applicable threats, existing controls, vulnerabilities, and the resulting inherent and residual risk. Results shall be recorded in the risk register with a named risk owner. Assessment shall precede go-live, not follow it.',
        guidance: 'Embed the assessment trigger in project gating and change approval workflows; assessments required by policy alone are routinely skipped under delivery pressure.',
        controlName: 'Cybersecurity risk assessment', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{riskAssessmentFrequency}}', kpi: '% of in-scope projects with a completed risk assessment before go-live (target: 100%)',
        risk: 'Material risk is introduced by change and discovered only after it has been realised.', riskRating: 'high',
        evidence: ['Completed risk assessment reports', 'Risk register entries with named owners', 'Project gate records showing assessment completion'],
        refs: { 'NCA-ECC': ['1-5-3', '1-6'], 'ISO-27001': ['6.1.2', 'A.5.8'], 'ISO-27005': ['7.2', '7.3'], 'NIST-CSF': ['ID.RA'] } },
      { key: 'risk_treatment', title: 'Risk treatment',
        policy: 'Cybersecurity risks shall be treated in line with the approved risk appetite, through mitigation, transfer, avoidance or formal acceptance.',
        standard: 'Each risk above appetite shall have a treatment plan with defined actions, a named owner, a due date and a target residual rating. Treatment progress shall be reviewed {{riskRegisterReviewFrequency}}. Risks rated Critical shall be escalated to {{criticalRiskEscalation}}.',
        guidance: 'Require the treatment plan to name the control it will create or strengthen, so the risk register and the control library stay connected.',
        controlName: 'Risk treatment planning and tracking', controlType: 'corrective', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: '% of treatment actions completed by their due date (target: 85%)',
        risk: 'Identified risks are recorded and then left untreated, so the register becomes a list of known unmanaged exposures.', riskRating: 'high',
        evidence: ['Risk register with treatment plans and due dates', 'Treatment progress reports', 'Escalation records for critical risks'],
        refs: { 'NCA-ECC': ['1-5-2'], 'ISO-27001': ['6.1.3'], 'ISO-27005': ['8'], 'NIST-CSF': ['GV.RM'], 'COBIT-2019': ['EDM03'] } },
      { key: 'risk_acceptance', title: 'Risk acceptance',
        policy: 'Residual risk shall be formally accepted by an authority commensurate with the risk level, and acceptance shall be time-bound.',
        standard: 'Acceptance shall record the residual rating, the rationale, compensating controls and an expiry date not exceeding {{riskAcceptanceMaxDuration}}. Critical residual risk shall be accepted only by the Cybersecurity Steering Committee. Expired acceptances shall be re-evaluated, not automatically renewed.',
        guidance: 'Expire acceptances automatically and re-present them; a risk accepted once otherwise remains accepted permanently without review.',
        controlName: 'Formal risk acceptance', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per acceptance, reviewed {{riskRegisterReviewFrequency}}', kpi: 'Number of expired risk acceptances still in force (target: 0)',
        risk: 'Risk is accepted informally by people without the authority to accept it, and never revisited.', riskRating: 'medium',
        evidence: ['Risk acceptance records with approver and expiry date', 'Committee minutes for critical acceptances', 'Report of expired acceptances'],
        refs: { 'ISO-27001': ['6.1.3', '8.3'], 'NCA-ECC': ['1-5-2'], 'NIST-CSF': ['GV.RM'] } },
      { key: 'risk_reporting', title: 'Risk reporting',
        policy: 'The cybersecurity risk position shall be reported to executive management and the board on a defined cycle.',
        standard: 'Reporting shall present the risk profile by level, movement since the previous period, treatment progress, accepted risks approaching expiry, and risks above appetite. The register shall be reviewed {{riskRegisterReviewFrequency}}.',
        guidance: 'Report movement and overdue treatment rather than a static heat map; the trend is what supports an investment decision.',
        controlName: 'Cybersecurity risk reporting', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{riskRegisterReviewFrequency}}', kpi: 'Risk register reviewed within the last {{riskRegisterReviewFrequency}} (target: yes)',
        risk: 'Executive management is unaware of accumulating risk and does not act until it is realised.', riskRating: 'medium',
        evidence: ['Risk reports presented to committee', 'Committee minutes recording discussion', 'Risk register version history'],
        refs: { 'NCA-ECC': ['1-5-2'], 'ISO-27001': ['9.1', '9.3'], 'NIST-CSF': ['GV.OV'], 'COBIT-2019': ['APO12'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Establish context', actor: 'Risk Manager', detail: 'Confirm scope, assets, business processes, regulatory obligations and the applicable risk appetite.' },
      { name: 'Identify risk', actor: 'Cybersecurity Analyst', detail: 'Identify threats, vulnerabilities and existing controls for the assets in scope.' },
      { name: 'Analyse and evaluate', actor: 'Risk Manager', detail: 'Rate impact and likelihood using {{riskMethodology}} to derive inherent and residual risk.', decision: { question: 'Is residual risk within appetite?', yes: 'Record and monitor', no: 'Proceed to treatment planning' } },
      { name: 'Plan treatment', actor: 'Risk Owner', detail: 'Select mitigation, transfer, avoidance or acceptance, and define actions with owners and due dates.' },
      { name: 'Approve', actor: 'CISO / Steering Committee', detail: 'Approve the treatment plan, or formally accept residual risk for no more than {{riskAcceptanceMaxDuration}}.', decision: { question: 'Is the residual risk rated Critical?', yes: 'Escalate to {{criticalRiskEscalation}}', no: 'Approve at the delegated authority level' } },
      { name: 'Monitor and report', actor: 'Risk Manager', detail: 'Track treatment progress and report the risk position {{riskRegisterReviewFrequency}}.' }
    ] },
    raciActivities: [
      raci('Define the risk management methodology', 'Govern', 'A:ciso R:risk_manager C:grc_manager C:internal_auditor'),
      raci('Conduct cybersecurity risk assessments', 'Assure', 'A:risk_manager R:cyber_analyst C:system_owner C:it_manager'),
      raci('Own identified risks', 'Govern', 'A:business_owner R:system_owner C:risk_manager C:ciso'),
      raci('Approve risk treatment plans', 'Govern', 'A:ciso R:risk_manager C:business_owner C:grc_manager'),
      raci('Accept residual risk', 'Govern', 'A:ciso R:business_owner C:risk_manager I:internal_auditor'),
      raci('Report the risk position to the committee', 'Govern', 'A:ciso R:risk_manager C:grc_manager'),
      raci('Audit the risk management process', 'Assure', 'A:risk_manager R:internal_auditor C:grc_manager')
    ]
  },

  security_awareness: {
    objectives: [
      'Ensure personnel understand their cybersecurity responsibilities.',
      'Provide role-specific training for higher-risk roles.',
      'Measure behaviour, not only completion.'
    ],
    parameters: { awarenessFrequency: 'annually for all personnel, with quarterly reinforcement', phishingSimulationFrequency: 'quarterly', trainingCompletionTarget: '95% within 30 days of assignment', phishingReportingTarget: 'above 30% of simulated phishing reported', screeningRequirement: 'identity, employment history and criminal record verification proportionate to the role' },
    requirements: [
      { key: 'awareness_programme', title: 'Security awareness programme',
        policy: 'All personnel and relevant third parties shall receive cybersecurity awareness training appropriate to their role, on induction and periodically thereafter.',
        standard: 'Awareness training shall be delivered {{awarenessFrequency}}, covering acceptable use, phishing, data handling, incident reporting, physical security and remote working. Completion shall reach {{trainingCompletionTarget}}, and non-completion shall be escalated to line management.',
        guidance: 'Tie content to the incidents the organisation actually experiences; generic annual content changes behaviour far less than material drawn from real events.',
        controlName: 'Security awareness programme', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{awarenessFrequency}}', kpi: 'Training completion rate (target: {{trainingCompletionTarget}})',
        risk: 'Personnel remain the most frequently exploited entry point because they were never taught what the attack looks like.', riskRating: 'high',
        evidence: ['Training content and delivery schedule', 'Completion records by department', 'Escalation records for non-completion'],
        refs: { 'NCA-ECC': ['1-10'], 'ISO-27001': ['A.6.3', '7.2', '7.3'], 'CIS-V8': ['14'], 'SAMA-CSF': ['1.6', '1.7'] } },
      { key: 'role_based_training', title: 'Role-based training',
        policy: 'Personnel in roles with elevated cybersecurity responsibility shall receive additional role-specific training.',
        standard: 'Role-based training shall be defined for developers, administrators, security personnel, executives and those handling personal or Confidential data. Competency requirements shall be documented per role and training completion tracked against them.',
        guidance: 'Define the competency first and select training against it, rather than recording whatever courses happened to be attended.',
        controlName: 'Role-based security training', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{awarenessFrequency}}', kpi: '% of elevated-risk roles with current role-based training (target: 90%)',
        risk: 'Those with the greatest ability to cause or prevent harm receive only general awareness content.', riskRating: 'medium',
        evidence: ['Role-based training matrix', 'Competency requirements per role', 'Completion records for elevated-risk roles'],
        refs: { 'NCA-ECC': ['1-10', '1-9'], 'ISO-27001': ['A.6.3', '7.2'], 'CIS-V8': ['14'] } },
      { key: 'phishing_simulation', title: 'Phishing simulation',
        policy: 'Simulated phishing shall be used to measure and improve resilience to social engineering.',
        standard: 'Simulations shall be conducted {{phishingSimulationFrequency}} across the organisation. Reporting rate shall be tracked with a target {{phishingReportingTarget}}, alongside click rate. Repeated susceptibility shall trigger targeted coaching rather than sanction in the first instance.',
        guidance: 'Track reporting rate as the primary measure; click rate alone rewards silence, while reporting is the behaviour that actually enables response.',
        controlName: 'Phishing simulation programme', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{phishingSimulationFrequency}}', kpi: 'Simulated phishing reporting rate (target: {{phishingReportingTarget}})',
        risk: 'Phishing susceptibility is unknown until a real campaign succeeds.', riskRating: 'medium',
        evidence: ['Simulation campaign results with click and report rates', 'Targeted coaching records', 'Trend analysis over at least four campaigns'],
        refs: { 'CIS-V8': ['14'], 'ISO-27001': ['A.6.3'], 'NCA-ECC': ['1-10'] } },
      { key: 'personnel_security', title: 'Personnel security',
        policy: 'Cybersecurity responsibilities shall be addressed before, during and after employment.',
        standard: 'Screening shall comprise {{screeningRequirement}} before employment, and shall be repeated for personnel moving into privileged roles. Employment terms shall include confidentiality obligations and cybersecurity responsibilities. A disciplinary process shall apply to violations, and responsibilities that survive termination shall be communicated at exit.',
        guidance: 'Re-screen on movement into privileged roles rather than only at hire; the risk profile changes with the role, not with the joining date.',
        controlName: 'Personnel security', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'At hire and on role change', kpi: '% of privileged-role holders with completed screening (target: 100%)',
        risk: 'Individuals with undisclosed history are placed directly into positions of significant trust.', riskRating: 'medium',
        evidence: ['Screening completion records', 'Employment terms containing security obligations', 'Exit acknowledgement records'],
        refs: { 'NCA-ECC': ['1-9'], 'ISO-27001': ['A.6.1', 'A.6.2', 'A.6.4', 'A.6.5'], 'SAMA-CSF': ['3.1'], 'NIST-800-53': ['PS'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Assess need', actor: 'Cybersecurity GRC Manager', detail: 'Identify awareness needs from incident trends, audit findings, regulatory change and role risk.' },
      { name: 'Develop content', actor: 'Cybersecurity GRC Manager', detail: 'Develop general and role-based content reflecting real incidents experienced by {{orgName}}.' },
      { name: 'Deliver', actor: 'Human Resources', detail: 'Assign training at induction and {{awarenessFrequency}}, tracking completion to {{trainingCompletionTarget}}.', decision: { question: 'Is completion below target after 30 days?', yes: 'Escalate to line management', no: 'Record completion' } },
      { name: 'Simulate', actor: 'Cybersecurity Analyst', detail: 'Run phishing simulations {{phishingSimulationFrequency}} and record click and reporting rates.' },
      { name: 'Coach', actor: 'Cybersecurity GRC Manager', detail: 'Provide targeted coaching for repeated susceptibility before considering disciplinary measures.' },
      { name: 'Measure and report', actor: 'CISO', detail: 'Report completion, reporting rate and trend to the Steering Committee and refresh content accordingly.' }
    ] },
    raciActivities: [
      raci('Define the awareness programme', 'Govern', 'A:ciso R:grc_manager C:business_owner'),
      raci('Develop awareness and role-based content', 'Govern', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Deliver and track training completion', 'Operate', 'A:business_owner R:grc_manager C:internal_auditor'),
      raci('Run phishing simulations', 'Detect', 'A:ciso R:cyber_analyst C:grc_manager'),
      raci('Screen personnel for privileged roles', 'Protect', 'A:business_owner R:grc_manager C:ciso'),
      raci('Report awareness metrics', 'Govern', 'A:ciso R:grc_manager C:internal_auditor')
    ]
  },

  change_management: {
    objectives: [
      'Ensure changes are assessed for security impact before implementation.',
      'Maintain approved configuration baselines.',
      'Control emergency changes without losing assurance.'
    ],
    parameters: { cabFrequency: 'weekly', emergencyChangeReviewSla: '5 business days', backoutRequirement: 'a documented and tested back-out plan for every standard and major change', configReviewFrequency: 'quarterly', securityReviewThreshold: 'any change affecting internet exposure, authentication, encryption, network boundaries or Confidential data' },
    requirements: [
      { key: 'change_control', title: 'Change control',
        policy: 'Changes to information systems shall be requested, assessed, approved, tested and recorded before implementation.',
        standard: 'Changes shall be classified as standard, normal or emergency. Normal changes shall be reviewed by the change advisory board {{cabFrequency}}. Every standard and major change shall include {{backoutRequirement}}. Unauthorised changes shall be investigated and reversed.',
        guidance: 'Detect unauthorised change through configuration monitoring rather than relying on the change record alone; the changes that cause incidents are usually the ones never raised.',
        controlName: 'Change control process', controlType: 'preventive', controlNature: 'administrative',
        frequency: '{{cabFrequency}}', kpi: '% of production changes with an approved change record (target: 98%)',
        risk: 'Untested and unreviewed changes cause outage or silently remove a security control.', riskRating: 'high',
        evidence: ['Change records with approvals and test evidence', 'Change advisory board minutes', 'Unauthorised change detection reports'],
        refs: { 'ISO-27001': ['A.8.32'], 'NCA-ECC': ['1-6'], 'COBIT-2019': ['BAI06'], 'SAMA-CSF': ['3.7'] } },
      { key: 'security_impact_assessment', title: 'Security impact assessment of change',
        policy: 'Changes shall be assessed for cybersecurity impact before approval.',
        standard: 'Security review shall be mandatory for {{securityReviewThreshold}}. The assessment shall confirm that controls remain effective after the change, that logging continues, and that no new exposure is introduced. Findings shall be resolved before implementation or formally risk-accepted.',
        guidance: 'Check that monitoring still functions after the change; changes that break log forwarding are rarely noticed until an investigation needs the logs.',
        controlName: 'Security impact assessment of change', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per qualifying change', kpi: '% of qualifying changes with a completed security assessment (target: 100%)',
        risk: 'A routine change removes a control, and the loss is discovered only during an incident.', riskRating: 'high',
        evidence: ['Security assessments attached to change records', 'Evidence of control validation after change', 'Risk acceptances for unresolved findings'],
        refs: { 'ISO-27001': ['A.8.32', 'A.5.8'], 'NCA-ECC': ['1-6', '1-5-3'], 'COBIT-2019': ['BAI06'] } },
      { key: 'config_baseline', title: 'Configuration baselines',
        policy: 'Approved configuration baselines shall be maintained for system classes, and deviations shall be detected and remediated.',
        standard: 'Baselines shall be version-controlled and reviewed {{configReviewFrequency}}. Configuration monitoring shall detect drift from baseline, and deviations shall be remediated or formally approved as a baseline change.',
        guidance: 'Manage baselines as code so that a deviation and its approval are both visible in version history.',
        controlName: 'Configuration baseline management', controlType: 'preventive', controlNature: 'technical',
        frequency: '{{configReviewFrequency}}', kpi: '% of systems compliant with their approved baseline (target: 95%)',
        risk: 'Systems drift into insecure configurations through incremental undocumented change.', riskRating: 'medium',
        evidence: ['Version-controlled baselines', 'Drift detection reports', 'Approved baseline change records'],
        refs: { 'ISO-27001': ['A.8.9'], 'CIS-V8': ['4'], 'NIST-800-53': ['CM-3'], 'NIST-CSF': ['PR.PS-01'], 'COBIT-2019': ['BAI10'] } },
      { key: 'emergency_change', title: 'Emergency change',
        policy: 'Emergency changes shall be permitted where delay would cause greater harm, and shall be reviewed retrospectively.',
        standard: 'Emergency changes shall be authorised by the IT Manager or CISO, recorded at the time of implementation where possible and within 24 hours otherwise, and reviewed by the change advisory board within {{emergencyChangeReviewSla}}. Repeated use of the emergency path for the same cause shall trigger a process review.',
        guidance: 'Trend emergency change volume; a rising rate normally indicates the standard path is too slow rather than that emergencies are increasing.',
        controlName: 'Emergency change management', controlType: 'corrective', controlNature: 'administrative',
        frequency: 'Per emergency change', kpi: '% of emergency changes retrospectively reviewed within {{emergencyChangeReviewSla}} (target: 100%)',
        risk: 'The emergency path becomes the routine path, bypassing security assessment entirely.', riskRating: 'medium',
        evidence: ['Emergency change records with authorisation', 'Retrospective review records', 'Emergency change volume trend'],
        refs: { 'ISO-27001': ['A.8.32'], 'COBIT-2019': ['BAI06'], 'NIST-800-53': ['CM-3'] } }
    ],
    procedureSeed: { steps: [
      { name: 'Raise change', actor: 'System Owner', detail: 'Submit the change with description, justification, affected systems, implementation plan and back-out plan.' },
      { name: 'Classify', actor: 'IT Manager', detail: 'Classify as standard, normal or emergency, and determine whether security review is required.', decision: { question: 'Does the change meet {{securityReviewThreshold}}?', yes: 'Route for cybersecurity assessment', no: 'Proceed to change advisory board review' } },
      { name: 'Assess security impact', actor: 'Cybersecurity Analyst', detail: 'Assess the impact on controls, logging and exposure, and record findings on the change record.' },
      { name: 'Approve', actor: 'Change Advisory Board', detail: 'Approve, defer or reject at the {{cabFrequency}} board, confirming {{backoutRequirement}} is present.' },
      { name: 'Implement and verify', actor: 'IT Manager', detail: 'Implement within the approved window and verify that security controls and log forwarding remain effective.', decision: { question: 'Did post-implementation verification pass?', yes: 'Close the change', no: 'Invoke the back-out plan and record the failure' } },
      { name: 'Review', actor: 'Cybersecurity GRC Manager', detail: 'Review emergency changes within {{emergencyChangeReviewSla}} and investigate any change implemented without approval.' }
    ] },
    raciActivities: [
      raci('Define the change management process', 'Govern', 'A:ciso R:grc_manager C:it_manager C:system_owner'),
      raci('Raise and document changes', 'Operate', 'A:system_owner R:it_manager C:business_owner'),
      raci('Assess security impact of change', 'Protect', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Approve changes at the advisory board', 'Govern', 'A:it_manager R:system_owner C:ciso C:business_owner'),
      raci('Verify controls after implementation', 'Assure', 'A:grc_manager R:cyber_analyst C:it_manager'),
      raci('Review emergency and unauthorised changes', 'Assure', 'A:ciso R:grc_manager C:internal_auditor')
    ]
  }
};
