/** Canonical requirement models — detect, respond and operate domains. */

export const OPERATE_DOMAINS = {
  asset_management: {
    objectives: [
      'Maintain an accurate, complete and current inventory of information and technology assets.',
      'Assign a named owner and a classification to every asset.',
      'Define acceptable use and enforce secure handling, return and disposal.'
    ],
    parameters: {
      inventoryReviewFrequency: 'quarterly',
      discoveryFrequency: 'weekly',
      inventoryAccuracyTarget: '98%',
      assetReturnSla: 'the last working day',
      disposalStandard: 'NIST SP 800-88 purge or destroy',
      unauthorisedAssetSla: '48 hours'
    , assetRequirementReview: 'annually, covering the inventory scope, the classification scheme applied to assets, and the disposal standard', criticalAssetBaseline: 'an enhanced baseline covering hardened configuration, monitoring coverage, backup inclusion and named ownership at both business and system level', licenceReconciliation: 'quarterly against entitlements, covering installed software and subscription services', endOfLifeHorizon: '12 months before vendor support ends, so replacement is planned rather than forced'},
    requirements: [
      { key: 'asset_inventory', title: 'Asset inventory',
        policy: 'A complete inventory of information and technology assets shall be established and maintained for all assets that store, process or transmit {{orgName}} information.',
        standard: 'The inventory shall record the asset identifier, type, location, network address where applicable, business service supported, owner, custodian, classification and lifecycle status. Automated discovery shall run {{discoveryFrequency}} and the inventory shall be reconciled and attested {{inventoryReviewFrequency}} to an accuracy of at least {{inventoryAccuracyTarget}}.',
        clauseOwners: ['it_manager', 'asset_owner'],
        guidance: 'Reconcile at least three independent sources — network discovery, endpoint agent and procurement records — because each alone has a predictable blind spot.',
        controlName: 'Information and technology asset inventory', controlType: 'detective', controlNature: 'hybrid',
        frequency: '{{discoveryFrequency}} discovery, {{inventoryReviewFrequency}} attestation',
        kpi: 'Inventory accuracy against sampled verification (target: {{inventoryAccuracyTarget}})',
        risk: 'Assets that are not inventoried are not patched, monitored or backed up, and are absent from every other control.',
        riskRating: 'high',
        evidence: ['Current asset inventory export', 'Automated discovery reconciliation report', 'Owner attestation records for the latest cycle'],
        refs: { 'NCA-ECC': ['2-1-1', '2-1-2'], 'ISO-27001': ['A.5.9'], 'NIST-CSF': ['ID.AM-01', 'ID.AM-02'], 'CIS-V8': ['1', '2'], 'NIST-800-53': ['CM-8'], 'SAMA-CSF': ['3.3'] } },
      { key: 'asset_ownership', title: 'Asset ownership',
        policy: 'Every asset recorded in the inventory shall have a named Asset Owner accountable for its classification, protection and lifecycle decisions.',
        standard: 'Ownership shall be assigned to a named individual, not a team mailbox or a vacant post. Ownership shall be re-attested {{inventoryReviewFrequency}} and reassigned within 10 business days when the owner leaves the role.',
        clauseOwners: ['business_owner', 'it_manager'],
        guidance: 'Where an owner cannot be identified, escalate rather than assigning to IT by default — unowned assets are usually unowned services.',
        controlName: 'Asset ownership assignment', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{inventoryReviewFrequency}}', kpi: '% of assets with a named, current owner (target: 100%)',
        risk: 'Without an accountable owner no one decides on classification, patching windows or retirement, and the asset drifts out of control coverage.',
        riskRating: 'medium',
        evidence: ['Asset register showing owner per asset', 'Ownership attestation records', 'Reassignment records for leavers'],
        refs: { 'NCA-ECC': ['2-1-1'], 'ISO-27001': ['A.5.9'], 'NIST-CSF': ['ID.AM-05'] } },
      { key: 'asset_classification', title: 'Asset classification and labelling',
        policy: 'Assets shall be classified according to the {{orgName}} classification scheme and handled in line with the classification assigned.',
        standard: 'Classification shall be assigned at acquisition or creation, reviewed on significant change, and re-reviewed on the cycle set by the Data Protection Standard rather than on the inventory cycle. Labelling shall be applied physically for media and equipment and through metadata for information assets. Handling requirements per classification level shall be defined in the Data Protection Standard.',
        clauseOwners: ['asset_owner', 'it_manager', 'grc_manager'],
        guidance: 'Classify the business service first and inherit to its supporting assets, rather than classifying thousands of endpoints individually.',
        controlName: 'Asset classification and labelling', controlType: 'directive', controlNature: 'administrative',
        frequency: 'At acquisition and {{inventoryReviewFrequency}}', kpi: '% of assets with an assigned classification (target: 100%)',
        risk: 'Uniform protection is applied to assets of very different sensitivity, over-spending on trivial assets and under-protecting critical ones.',
        riskRating: 'medium',
        evidence: ['Classification field populated in the asset register', 'Labelling samples for media and equipment', 'Classification review records'],
        refs: { 'NCA-ECC': ['2-1-4'], 'ISO-27001': ['A.5.12', 'A.5.13'], 'NCA-DCC': ['2-1'], 'NIST-CSF': ['ID.AM-05'] } },
      { key: 'acceptable_use', title: 'Acceptable use',
        policy: 'An Acceptable Use Policy shall define the permitted and prohibited use of {{orgName}} information and technology assets, and shall be acknowledged by all personnel before access is granted.',
        standard: 'Acceptable use shall address corporate device use, personal use limits, removable media, cloud storage, software installation, and the prohibition of circumventing security controls. Acknowledgement shall be recorded at onboarding and re-acknowledged annually.',
        clauseOwners: ['grc_manager', 'grc_manager'],
        guidance: 'Tie the acknowledgement record to the access provisioning workflow so that access cannot be granted before acknowledgement exists.',
        controlName: 'Acceptable use acknowledgement', controlType: 'directive', controlNature: 'administrative',
        frequency: 'At onboarding and annually', kpi: '% of personnel with a current acceptable use acknowledgement (target: 100%)',
        risk: 'Disciplinary and legal action following misuse is undermined when the individual was never shown the rule they broke.',
        riskRating: 'medium',
        evidence: ['Signed or system-recorded acknowledgements', 'Current Acceptable Use Policy version', 'Onboarding checklist showing the acknowledgement gate'],
        refs: { 'NCA-ECC': ['2-1-3'], 'ISO-27001': ['A.5.10'], 'SAMA-CSF': ['3.3'] } },
      { key: 'asset_return', title: 'Return of assets',
        policy: 'All {{orgName}} assets in the possession of personnel and third parties shall be returned on termination of employment, contract or agreement.',
        standard: 'Asset return shall be completed by {{assetReturnSla}}. The leaver checklist shall enumerate issued assets from the inventory. Non-returned assets shall be remotely wiped where technically possible and recorded as a loss event.',
        clauseOwners: ['it_manager', 'it_manager', 'cyber_analyst'],
        guidance: 'Generate the leaver checklist from the asset register rather than from memory; issued items are otherwise forgotten within a year of issue.',
        controlName: 'Asset return on termination', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per leaver event', kpi: '% of issued assets returned by {{assetReturnSla}} (target: 98%)',
        risk: 'Corporate data leaves the organisation on devices nobody is tracking.',
        riskRating: 'medium',
        evidence: ['Leaver asset return checklists', 'Remote wipe confirmations for non-returned devices', 'Loss event records'],
        refs: { 'ISO-27001': ['A.5.11'], 'NCA-ECC': ['1-9'], 'NIST-800-53': ['PS'] } },
      { key: 'secure_disposal', title: 'Secure disposal and re-use',
        policy: 'Assets shall be securely sanitised before disposal, re-use or return to a third party, so that no recoverable {{orgName}} information remains.',
        standard: 'Sanitisation shall follow {{disposalStandard}} appropriate to the media type and classification. Certificates of destruction shall be obtained for third-party disposal. Disposal shall be recorded against the asset in the inventory, and the asset marked as retired.',
        clauseOwners: ['it_manager', 'grc_manager', 'it_manager'],
        guidance: 'Treat multifunction printers, network appliances and decommissioned virtual machine images as storage media — each routinely retains data.',
        controlName: 'Secure asset disposal', controlType: 'preventive', controlNature: 'administrative',
        frequency: 'Per disposal event', kpi: '% of disposals with sanitisation evidence (target: 100%)',
        risk: 'Sensitive information is recovered from equipment sold, recycled or returned to a leasing company.',
        riskRating: 'high',
        evidence: ['Certificates of destruction', 'Sanitisation records referencing the asset identifier', 'Retired status recorded in the asset register'],
        refs: { 'NCA-ECC': ['2-1-2'], 'ISO-27001': ['A.7.14', 'A.8.10'], 'SAMA-CSF': ['3.11'], 'NIST-800-53': ['MP'] } },
      { key: 'unauthorised_assets', title: 'Detection of unauthorised assets',
        policy: 'Unauthorised devices and software detected in the environment shall be investigated and removed or authorised.',
        standard: 'Discovery output shall be compared against the authorised inventory {{discoveryFrequency}}. Unauthorised assets shall be quarantined, removed or formally authorised within {{unauthorisedAssetSla}} of detection. Unauthorised software shall be removed or approved through the Change Management process.',
        clauseOwners: ['cyber_analyst', 'it_manager', 'it_manager'],
        guidance: 'Network access control that quarantines by default converts this from a recurring manual investigation into an exception process.',
        controlName: 'Unauthorised asset detection and response', controlType: 'detective', controlNature: 'technical',
        frequency: '{{discoveryFrequency}}', kpi: '% of unauthorised assets resolved within {{unauthorisedAssetSla}} (target: 95%)',
        risk: 'Unmanaged devices join the network without patching, monitoring or endpoint protection, providing a foothold.',
        riskRating: 'high',
        evidence: ['Discovery exception reports', 'Quarantine or removal records', 'Software allow-list violations report'],
        refs: { 'CIS-V8': ['1', '2'], 'ISO-27001': ['A.5.9', 'A.8.19'], 'NCA-ECC': ['2-1-2'], 'NIST-800-53': ['CM-8'] } },
      { key: 'asset_requirement_review', title: 'Periodic review of asset management requirements',
        policy: 'The asset management requirements themselves shall be reviewed, not only the inventory they govern.',
        standard: 'Review shall occur {{assetRequirementReview}} and shall assess whether the inventory scope still covers what the organisation operates, whether the classification scheme is being applied consistently, and whether the disposal standard remains adequate for the media in use. Findings shall be recorded as improvement actions with owners. The review shall include a sample test of inventory accuracy performed independently of the team that maintains it, since self-attested accuracy is the figure most often overstated.',
        clauseOwners: ['grc_manager', 'grc_manager', 'internal_auditor'],
        guidance: 'Sample independently. An owner attesting that their own register is accurate produces a number that is right about as often as it is convenient.',
        controlName: 'Periodic review of asset management requirements', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{assetRequirementReview}}', kpi: 'Independently sampled inventory accuracy against {{inventoryAccuracyTarget}}',
        risk: 'The inventory is maintained diligently against a scope that no longer matches what the organisation runs.', riskRating: 'medium',
        evidence: ['Review records covering scope, classification and disposal standard', 'Independent sample test results of inventory accuracy', 'Improvement actions with owners and closure'],
        refs: { 'NCA-ECC': ['2-1-5'], 'NCA-CSCC': ['2-1'], 'ISO-27001': ['A.5.9', 'A.5.35'], 'COBIT-2019': ['BAI09'] } },
      { key: 'critical_asset_baseline', title: 'Enhanced requirements for critical assets',
        policy: 'Assets supporting a critical system shall be identifiable in the inventory and shall carry an enhanced baseline.',
        standard: 'Critical assets shall be flagged in the inventory and shall meet {{criticalAssetBaseline}}. Any change of designation shall trigger reassessment of the applicable controls. Reconciliation for critical assets shall run at {{discoveryFrequency}} and discrepancies shall be investigated within {{unauthorisedAssetSla}} rather than at the next cycle. A critical asset without a named business owner shall be escalated to the CISO rather than recorded as a gap.',
        clauseOwners: ['system_owner', 'grc_manager', 'cyber_analyst', 'ciso'],
        guidance: 'Flag criticality in the inventory itself. Where it lives in a separate spreadsheet, the two disagree within a quarter and the operational teams follow the one they can see.',
        controlName: 'Enhanced baseline for critical assets', controlType: 'preventive', controlNature: 'hybrid',
        frequency: '{{discoveryFrequency}}', kpi: '% of critical assets flagged in the inventory with the enhanced baseline applied (target: 100%)',
        risk: 'Assets supporting critical systems receive general-estate treatment because nothing in the inventory distinguishes them.', riskRating: 'high',
        evidence: ['Inventory records showing critical asset flags', 'Enhanced baseline compliance evidence per critical asset', 'Investigation records for critical asset discrepancies'],
        refs: { 'NCA-CSCC': ['2-1'], 'NCA-ECC': ['2-1-5'], 'ISO-27001': ['A.5.9', 'A.8.9'], 'COBIT-2019': ['BAI09'] } },
      { key: 'asset_lifecycle_support', title: 'Licence position and end of support',
        policy: 'Assets shall be maintained within vendor support, and their licence position shall be known.',
        standard: 'Reconciliation shall run {{licenceReconciliation}}, covering installed software and subscription services, so that both under-licensing and expenditure on unused entitlement are visible. End-of-support dates shall be recorded in the inventory, and replacement planned {{endOfLifeHorizon}}. An asset that passes end of support shall carry a time-bound exception with compensating controls, owned by the business owner rather than by the technology team that inherited it.',
        clauseOwners: ['it_manager', 'it_manager', 'business_owner'],
        guidance: 'Put the end-of-support date in an inventory field, not in somebody\'s plan. It is the only way the replacement appears in a budget cycle before it appears in an audit.',
        controlName: 'Asset licence and support lifecycle', controlType: 'directive', controlNature: 'administrative',
        frequency: '{{licenceReconciliation}}', kpi: '% of assets within vendor support or covered by a time-bound exception (target: 95%)',
        risk: 'Unsupported assets accumulate without patches, and the organisation carries licensing exposure it has not measured.', riskRating: 'high',
        evidence: ['Licence reconciliation against entitlements', 'Inventory records with end-of-support dates', 'Time-bound exceptions with compensating controls and business owners'],
        refs: { 'NCA-ECC': ['2-1-5', '2-10-3'], 'ISO-27001': ['A.5.9', 'A.5.32', 'A.8.8'], 'COBIT-2019': ['BAI09'] } }
    ],
    procedure: {
      purpose: 'To define how information and technology assets are identified, registered, classified, maintained and securely disposed of at {{orgName}}.',
      preconditions: ['The asset register is operational and integrated with procurement and discovery sources.', 'The classification scheme is approved and published.', 'Asset Owners have been nominated for each business service.'],
      inputs: ['Procurement and commissioning records', 'Automated discovery output', 'Change records affecting asset state', 'Leaver and contract termination notifications'],
      steps: [
        { name: 'Identify', actor: 'IT Manager / Asset Owner', detail: 'Register the asset at acquisition or commissioning, capturing type, location, supported business service and custodian.' },
        { name: 'Classify', actor: 'Asset Owner', detail: 'Assign the classification level in line with the {{orgName}} classification scheme and apply the corresponding labelling.' },
        { name: 'Assign ownership', actor: 'Cybersecurity GRC Manager', detail: 'Confirm a named Asset Owner is recorded and accountable for lifecycle decisions.', decision: { question: 'Is a named owner identified?', yes: 'Continue to Protect', no: 'Escalate to the business service owner for nomination' } },
        { name: 'Protect', actor: 'IT Manager', detail: 'Apply the security baseline, monitoring agent, backup schedule and access controls appropriate to the classification.' },
        { name: 'Reconcile', actor: 'Cybersecurity Analyst', detail: 'Compare discovery output against the authorised inventory {{discoveryFrequency}} and investigate discrepancies.', decision: { question: 'Is the discovered asset authorised?', yes: 'Update the register', no: 'Quarantine and resolve within {{unauthorisedAssetSla}}' } },
        { name: 'Attest', actor: 'Asset Owner', detail: 'Re-attest inventory accuracy, ownership and classification {{inventoryReviewFrequency}}.' },
        { name: 'Dispose', actor: 'IT Manager', detail: 'Sanitise the asset to {{disposalStandard}}, obtain destruction evidence, and mark the asset retired in the register.' }
      ],
      outputs: ['Accurate asset register', 'Classification and labelling applied', 'Sanitisation and disposal evidence', 'Exception register for unauthorised assets'],
      escalation: ['Assets without an identifiable owner escalate to the business service owner, then to the CISO after 10 business days.', 'Unauthorised assets not resolved within {{unauthorisedAssetSla}} escalate to the IT Manager.', 'Missing sanitisation evidence escalates to the Cybersecurity GRC Manager and is recorded as a control failure.'],
      records: ['Asset register (retained for asset life plus 3 years)', 'Attestation records (3 years)', 'Certificates of destruction (7 years)'],
      kpis: [{ name: 'Inventory accuracy', target: '{{inventoryAccuracyTarget}}' }, { name: 'Ownership coverage', target: '100% of assets with a named owner' }, { name: 'Unauthorised asset resolution', target: '95% within {{unauthorisedAssetSla}}' }]
    },
    roles: ['ciso', 'grc_manager', 'cyber_analyst', 'it_manager', 'asset_owner', 'system_owner', 'internal_auditor'],
    raciActivities: [
      { activity: 'Define and approve the Asset Management Policy', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', cyber_analyst: 'C', it_manager: 'C', asset_owner: 'I', system_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Register newly acquired assets', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'I', cyber_analyst: 'I', it_manager: 'A', asset_owner: 'R', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Classify and label assets', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'C', it_manager: 'I', asset_owner: 'A', system_owner: 'R', internal_auditor: 'I' } },
      { activity: 'Run automated asset discovery', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'I', cyber_analyst: 'R', it_manager: 'A', asset_owner: 'I', system_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Investigate unauthorised assets', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'R', it_manager: 'R', asset_owner: 'C', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Attest inventory accuracy', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'C', it_manager: 'C', asset_owner: 'R', system_owner: 'R', internal_auditor: 'C' } },
      { activity: 'Authorise and evidence asset disposal', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'I', it_manager: 'R', asset_owner: 'A', system_owner: 'I', internal_auditor: 'C' } },
      { activity: 'Review the asset management requirements', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'R', it_manager: 'C', asset_owner: 'C', system_owner: 'I', internal_auditor: 'C' } },
      { activity: 'Apply the enhanced baseline to critical assets', phase: 'Protect', assign: { ciso: 'A', grc_manager: 'C', cyber_analyst: 'C', it_manager: 'R', asset_owner: 'C', system_owner: 'R', internal_auditor: 'I' } },
      { activity: 'Reconcile licences and track end of support', phase: 'Operate', assign: { ciso: 'I', grc_manager: 'C', cyber_analyst: 'I', it_manager: 'A', asset_owner: 'R', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Audit asset management controls', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', cyber_analyst: 'I', it_manager: 'I', asset_owner: 'I', system_owner: 'I', internal_auditor: 'R' } }
    ]
  },

  incident_management: {
    objectives: [
      'Detect, triage and classify cybersecurity events consistently and without delay.',
      'Contain, eradicate and recover from incidents while preserving evidence.',
      'Meet regulatory and contractual notification obligations within the required windows.',
      'Convert every incident into a durable improvement.'
    ],
    parameters: {
      p1TriageSla: '15 minutes',
      p1ContainmentSla: '4 hours',
      p2TriageSla: '1 hour',
      regulatoryNotificationSla: '72 hours of confirming a reportable incident, or sooner where the regulator specifies',
      lessonsLearnedSla: '10 business days of incident closure',
      irPlanTestFrequency: 'annually',
      evidenceRetention: '3 years',
      postIncidentActionSla: '60 days'
    },
    requirements: [
      { key: 'ir_plan', title: 'Incident response plan',
        policy: 'A cybersecurity incident response plan shall be documented, approved, maintained and exercised, defining roles, classification criteria, escalation paths and communication protocols.',
        standard: 'The plan shall define incident severity levels with objective criteria, the incident response team composition and authority, activation triggers, decision rights for containment actions that disrupt business services, internal and external communication protocols, and regulatory notification obligations. It shall be reviewed and exercised at least {{irPlanTestFrequency}}.',
        clauseOwners: ['ciso', 'grc_manager'],
        guidance: 'State explicitly who can authorise disconnecting a production service, and their deputy. Ambiguity on that single point costs more time in a real incident than any technical gap.',
        controlName: 'Documented and exercised incident response plan', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed and exercised {{irPlanTestFrequency}}', kpi: 'Incident response plan exercised within the last {{irPlanTestFrequency}} (target: yes)',
        risk: 'Response is improvised under pressure, extending attacker dwell time and producing inconsistent regulatory notification.',
        riskRating: 'critical',
        evidence: ['Approved incident response plan with version and date', 'Exercise report and participant list', 'Post-exercise improvement actions with closure status'],
        refs: { 'NCA-ECC': ['2-13-1', '2-13-3'], 'ISO-27001': ['A.5.24', 'A.5.26'], 'NIST-CSF': ['RS.MA-01'], 'NIST-800-53': ['IR-4'], 'CIS-V8': ['17'], 'SAMA-CSF': ['3.15'] } },
      { key: 'event_reporting', title: 'Event detection and reporting',
        policy: 'All personnel and third parties shall report suspected cybersecurity events promptly through the published reporting channels.',
        standard: 'Reporting channels shall be published, available at all times, and shall not require the reporter to determine whether the event is genuine. Events detected by security tooling shall be raised automatically into the incident queue. Reporters shall receive acknowledgement, and good-faith reports shall not attract sanction.',
        clauseOwners: ['grc_manager', 'soc_analyst', 'ciso'],
        guidance: 'Measure reporting volume as a positive indicator; a falling report count usually signals disengagement rather than improving security.',
        controlName: 'Cybersecurity event reporting', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Continuous', kpi: 'Mean time from event occurrence to report (target: under 1 hour for user-reported events)',
        risk: 'Early indicators go unreported, and the first confirmation of compromise arrives from an external party.',
        riskRating: 'high',
        evidence: ['Published reporting channel documentation', 'Event report records with acknowledgement timestamps', 'Awareness material covering reporting'],
        refs: { 'ISO-27001': ['A.6.8', 'A.5.25'], 'NCA-ECC': ['2-13-2'], 'NIST-800-53': ['IR-6'], 'COBIT-2019': ['DSS02'] } },
      { key: 'triage_classification', title: 'Triage and classification',
        policy: 'Reported events shall be triaged and classified against defined severity criteria within the applicable service level.',
        standard: 'Severity 1 events shall be triaged within {{p1TriageSla}} and Severity 2 within {{p2TriageSla}}. Classification shall consider confidentiality, integrity and availability impact, affected data classification, the number of affected records or systems, and regulatory reportability. Classification shall be reassessed as the investigation develops.',
        clauseOwners: ['soc_analyst', 'ir_analyst', 'ir_analyst'],
        guidance: 'Make reportability an explicit field at triage rather than a later judgement; notification clocks generally start at detection, not at conclusion.',
        controlName: 'Incident triage and severity classification', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Per event', kpi: '% of Severity 1 events triaged within {{p1TriageSla}} (target: 95%)',
        risk: 'Serious incidents are handled as routine tickets, delaying containment and breaching notification deadlines.',
        riskRating: 'high',
        evidence: ['Incident records with triage timestamps and assigned severity', 'Severity classification criteria in force', 'Reclassification history for sampled incidents'],
        refs: { 'NCA-ECC': ['2-13-3'], 'ISO-27001': ['A.5.25'], 'NIST-800-53': ['IR-4'], 'NIST-CSF': ['RS.MA-01'], 'NCA-CSCC': ['2-12'] } },
      { key: 'containment', title: 'Containment, eradication and recovery',
        policy: 'Confirmed incidents shall be contained to limit impact, the root cause eradicated, and affected services restored to a verified secure state.',
        standard: 'Severity 1 incidents shall be contained within {{p1ContainmentSla}} of confirmation. Containment actions that disrupt production shall be authorised by the CISO or the designated deputy. Recovery shall not proceed until the entry vector is identified and closed, and restored systems shall be verified against the security baseline before return to service.',
        clauseOwners: ['ir_analyst', 'ciso', 'ir_analyst'],
        guidance: 'Record the containment authorisation decision and its time; it is the single most scrutinised decision in any post-incident review.',
        controlName: 'Incident containment and recovery', controlType: 'corrective', controlNature: 'hybrid',
        frequency: 'Per incident', kpi: '% of Severity 1 incidents contained within {{p1ContainmentSla}} (target: 90%)',
        risk: 'Premature restoration returns a compromised system to service, allowing the attacker to resume with the same access.',
        riskRating: 'critical',
        evidence: ['Incident timeline showing containment actions and authorisation', 'Root cause analysis record', 'Baseline verification evidence prior to return to service'],
        refs: { 'NCA-ECC': ['2-13-2', '2-13-3'], 'ISO-27001': ['A.5.26'], 'NIST-800-53': ['IR-4'], 'NIST-CSF': ['RS.MI'] } },
      { key: 'evidence_handling', title: 'Evidence collection and handling',
        policy: 'Evidence relating to cybersecurity incidents shall be identified, collected and preserved in a manner that maintains its integrity and admissibility.',
        standard: 'Evidence shall be collected before volatile data is lost, hashed at collection, stored with a documented chain of custody, and retained for {{evidenceRetention}} or longer where litigation or regulatory proceedings are anticipated. Forensic acquisition shall be performed by trained personnel or an approved third party.',
        clauseOwners: ['ir_analyst', 'ciso'],
        guidance: 'Agree a forensic retainer before an incident; procurement under incident conditions loses days that matter.',
        controlName: 'Forensic evidence handling', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Per incident', kpi: '% of Severity 1 incidents with a complete chain of custody record (target: 100%)',
        risk: 'Evidence is contaminated or lost, preventing attribution, insurance recovery and legal action.',
        riskRating: 'high',
        evidence: ['Chain of custody records', 'Evidence acquisition hashes', 'Forensic provider engagement records'],
        refs: { 'ISO-27001': ['A.5.28'], 'NCA-ECC': ['2-13-2'], 'NIST-800-53': ['IR-4'], 'NIST-CSF': ['RS.AN'] } },
      { key: 'regulatory_notification', title: 'Regulatory and stakeholder notification',
        policy: 'Cybersecurity incidents meeting the defined reportability criteria shall be notified to the relevant regulators, authorities, customers and affected data subjects within the required timeframes.',
        standard: 'Reportable incidents shall be notified within {{regulatoryNotificationSla}}. The notification register shall record the recipient, the obligation relied upon, the content, the approver and the timestamp. Notification content shall be approved by Legal and the CISO before release. Contact points for each regulator shall be maintained and verified {{irPlanTestFrequency}}.',
        clauseOwners: ['ciso', 'grc_manager', 'ciso', 'grc_manager'],
        guidance: 'Maintain pre-approved notification templates per obligation; drafting from scratch during a Severity 1 incident is where deadlines are missed.',
        controlName: 'Incident notification to authorities and stakeholders', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per reportable incident', kpi: '% of reportable incidents notified within the applicable deadline (target: 100%)',
        risk: 'Statutory notification deadlines are missed, attracting regulatory sanction independently of the incident itself.',
        riskRating: 'critical',
        evidence: ['Notification register with timestamps and approvals', 'Copies of notifications issued', 'Verified regulator contact list'],
        refs: { 'NCA-ECC': ['2-13-3'], 'ISO-27001': ['A.5.5', 'A.5.24'], 'NIST-800-53': ['IR-6'], 'NIST-CSF': ['RS.CO'], 'SAMA-CSF': ['3.15'] } },
      { key: 'threat_intelligence', title: 'Threat intelligence and information sharing',
        policy: 'Threat intelligence relevant to {{orgName}} shall be collected, assessed and used to inform detection, response and risk decisions.',
        standard: 'Intelligence sources shall include the national authority, sector sharing communities and commercial feeds where subscribed. Actionable indicators shall be deployed to detection tooling, and relevant advisories assessed for applicability within 2 business days of receipt.',
        clauseOwners: ['cyber_analyst', 'soc_analyst'],
        guidance: 'Assess applicability against the asset inventory; an advisory for technology the organisation does not operate should be closed quickly and visibly.',
        controlName: 'Threat intelligence management', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Continuous', kpi: '% of critical advisories assessed within 2 business days (target: 95%)',
        risk: 'Known, actively exploited techniques are not detected because indicators were never deployed.',
        riskRating: 'medium',
        evidence: ['Threat intelligence source register', 'Advisory assessment records', 'Indicator deployment evidence in detection tooling'],
        refs: { 'ISO-27001': ['A.5.7', 'A.5.6'], 'NCA-ECC': ['2-13-3'], 'SAMA-CSF': ['3.16'] } },
      { key: 'lessons_learned', title: 'Post-incident review and improvement',
        policy: 'Knowledge gained from cybersecurity incidents shall be used to strengthen controls and reduce the likelihood and impact of recurrence.',
        standard: 'A post-incident review shall be completed within {{lessonsLearnedSla}} for all Severity 1 and Severity 2 incidents. The review shall identify root cause, control failures, detection gaps and response gaps, and shall generate assigned actions with due dates. Actions shall be tracked to closure within {{postIncidentActionSla}} unless a longer plan is formally approved.',
        clauseOwners: ['grc_manager', 'ir_analyst', 'grc_manager'],
        guidance: 'Track post-incident actions in the same register as audit findings; actions held only in the incident record are rarely closed.',
        controlName: 'Post-incident review and action tracking', controlType: 'corrective', controlNature: 'administrative',
        frequency: 'Per Severity 1 and 2 incident', kpi: '% of post-incident actions closed within {{postIncidentActionSla}} (target: 85%)',
        risk: 'The same control weakness is exploited repeatedly because remediation was never completed.',
        riskRating: 'high',
        evidence: ['Post-incident review reports', 'Action register with owners, due dates and closure evidence', 'Trend analysis of recurring root causes'],
        refs: { 'ISO-27001': ['A.5.27'], 'NCA-ECC': ['2-13-2'], 'NIST-800-53': ['IR-4'], 'NIST-CSF': ['ID.IM'], 'COBIT-2019': ['DSS03'] } },
      { key: 'ir_communications', title: 'Incident communications',
        policy: 'Internal and external communications during a cybersecurity incident shall be coordinated, accurate and authorised before release.',
        standard: 'A single approved spokesperson shall be designated for external communication. Internal updates shall follow a defined cadence by severity. Communications shall use out-of-band channels where corporate systems are suspected of compromise.',
        clauseOwners: ['ciso', 'ir_analyst', 'ciso'],
        guidance: 'Pre-establish an out-of-band channel and test it during exercises; the first time it is used should not be during the incident it was built for.',
        controlName: 'Incident communication management', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per incident', kpi: '% of Severity 1 incidents with communications issued per the defined cadence (target: 100%)',
        risk: 'Uncoordinated disclosure misstates the facts, compounding regulatory and reputational damage.',
        riskRating: 'medium',
        evidence: ['Communication log per incident', 'Approved spokesperson designation', 'Out-of-band channel test records'],
        refs: { 'NIST-CSF': ['RS.CO'], 'ISO-27001': ['A.5.24'], 'NCA-ECC': ['2-13-3'] } }
    ],
    procedure: {
      purpose: 'To define the end-to-end handling of cybersecurity events and incidents at {{orgName}}, from detection through to closure and improvement.',
      preconditions: ['The incident response plan is approved and current.', 'Incident response team members and deputies are named and contactable.', 'Detection tooling is forwarding alerts into the incident queue.', 'Regulator and authority contact points are verified.'],
      inputs: ['Security tooling alerts', 'User-reported events', 'Third-party or authority notifications', 'Threat intelligence advisories'],
      steps: [
        { name: 'Detect and report', actor: 'Any user / SOC Analyst / Tooling', detail: 'Record the event in the incident management system with the time of detection, source and initial observations.' },
        { name: 'Triage', actor: 'SOC Analyst', detail: 'Validate the event, gather initial context and assign a severity within {{p1TriageSla}} for Severity 1 and {{p2TriageSla}} for Severity 2.', decision: { question: 'Is the event a confirmed cybersecurity incident?', yes: 'Declare an incident and continue', no: 'Close as a false positive with documented rationale' } },
        { name: 'Declare and mobilise', actor: 'Incident Response Analyst', detail: 'Declare the incident, assign an incident manager, mobilise the response team and open the incident timeline. Assess regulatory reportability at this point.', decision: { question: 'Does the incident meet reportability criteria?', yes: 'Start the notification workflow in parallel with containment', no: 'Record the reportability assessment and rationale' } },
        { name: 'Contain', actor: 'Incident Response Analyst / IT Manager', detail: 'Apply containment measures within {{p1ContainmentSla}} for Severity 1. Containment that disrupts production requires CISO authorisation, which shall be recorded with its timestamp.' },
        { name: 'Collect evidence', actor: 'Incident Response Analyst', detail: 'Acquire volatile and persistent evidence with hashing and chain of custody before remediation alters system state.' },
        { name: 'Eradicate', actor: 'Incident Response Analyst / IT Manager', detail: 'Identify and remove the root cause, close the entry vector and eliminate attacker persistence.', decision: { question: 'Has the entry vector been identified and closed?', yes: 'Proceed to recovery', no: 'Continue investigation; recovery shall not commence' } },
        { name: 'Recover', actor: 'IT Manager / System Owner', detail: 'Restore services from verified-clean sources, validate against the security baseline and confirm business functionality before return to service.' },
        { name: 'Notify', actor: 'CISO / Legal', detail: 'Issue regulatory and stakeholder notifications within {{regulatoryNotificationSla}}, recording recipient, content, approver and timestamp.' },
        { name: 'Close and review', actor: 'Cybersecurity GRC Manager', detail: 'Close the incident, and complete the post-incident review within {{lessonsLearnedSla}} with assigned improvement actions tracked to closure within {{postIncidentActionSla}}.' }
      ],
      outputs: ['Contained and recovered services', 'Complete incident timeline and evidence package', 'Regulatory notifications where applicable', 'Post-incident review report and improvement actions'],
      escalation: ['Severity 1 incidents escalate immediately to the CISO and Executive Management.', 'Containment not achieved within {{p1ContainmentSla}} escalates to Executive Management for additional authority and resources.', 'Suspected regulatory reportability escalates to Legal and the CISO without waiting for investigation to conclude.', 'Suspected insider involvement escalates to the CISO and Human Resources under a restricted-distribution handling protocol.'],
      records: ['Incident record and timeline (retained {{evidenceRetention}})', 'Evidence and chain of custody (retained {{evidenceRetention}})', 'Notification register (retained 7 years)', 'Post-incident review and action closure evidence (retained 3 years)'],
      kpis: [{ name: 'Severity 1 triage timeliness', target: '95% within {{p1TriageSla}}' }, { name: 'Severity 1 containment timeliness', target: '90% within {{p1ContainmentSla}}' }, { name: 'Regulatory notification compliance', target: '100% within the applicable deadline' }, { name: 'Post-incident action closure', target: '85% within {{postIncidentActionSla}}' }, { name: 'Mean time to detect', target: 'Trending down quarter on quarter' }]
    },
    roles: ['ciso', 'grc_manager', 'ir_analyst', 'soc_analyst', 'it_manager', 'system_owner', 'business_owner', 'internal_auditor'],
    raciActivities: [
      { activity: 'Define and approve the Incident Response Plan', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', ir_analyst: 'C', soc_analyst: 'C', it_manager: 'C', system_owner: 'I', business_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Detect and report cybersecurity events', phase: 'Detect', assign: { ciso: 'A', grc_manager: 'I', ir_analyst: 'C', soc_analyst: 'R', it_manager: 'C', system_owner: 'C', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Triage and classify incidents', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'I', ir_analyst: 'A', soc_analyst: 'R', it_manager: 'C', system_owner: 'I', business_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Authorise disruptive containment action', phase: 'Respond', assign: { ciso: 'A', grc_manager: 'C', ir_analyst: 'R', soc_analyst: 'C', it_manager: 'R', system_owner: 'C', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Collect and preserve forensic evidence', phase: 'Respond', assign: { ciso: 'A', grc_manager: 'I', ir_analyst: 'R', soc_analyst: 'C', it_manager: 'C', system_owner: 'I', business_owner: 'I', internal_auditor: 'C' } },
      { activity: 'Eradicate root cause and recover services', phase: 'Respond', assign: { ciso: 'A', grc_manager: 'I', ir_analyst: 'R', soc_analyst: 'C', it_manager: 'R', system_owner: 'R', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Notify regulators and affected stakeholders', phase: 'Respond', assign: { ciso: 'A', grc_manager: 'R', ir_analyst: 'C', soc_analyst: 'I', it_manager: 'I', system_owner: 'I', business_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Conduct post-incident review', phase: 'Assure', assign: { ciso: 'A', grc_manager: 'R', ir_analyst: 'R', soc_analyst: 'C', it_manager: 'C', system_owner: 'C', business_owner: 'C', internal_auditor: 'C' } },
      { activity: 'Track post-incident improvement actions to closure', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', ir_analyst: 'C', soc_analyst: 'I', it_manager: 'R', system_owner: 'R', business_owner: 'I', internal_auditor: 'C' } },
      { activity: 'Exercise the incident response plan', phase: 'Assure', assign: { ciso: 'A', grc_manager: 'R', ir_analyst: 'R', soc_analyst: 'C', it_manager: 'C', system_owner: 'C', business_owner: 'C', internal_auditor: 'C' } }
    ]
  },

  vulnerability_management: {
    objectives: [
      'Continuously discover technical vulnerabilities across all in-scope assets.',
      'Prioritise remediation by exploitability and business impact, not by scanner score alone.',
      'Remediate within defined, risk-based timeframes and verify closure.'
    ],
    parameters: {
      criticalRemediationSla: '15 days',
      highRemediationSla: '30 days',
      mediumRemediationSla: '90 days',
      lowRemediationSla: '180 days',
      emergencyPatchSla: '72 hours for actively exploited vulnerabilities',
      internalScanFrequency: 'weekly',
      externalScanFrequency: 'weekly',
      authenticatedScanFrequency: 'monthly',
      pentestFrequency: 'annually and after significant change',
      scanCoverageTarget: '98% of the authorised asset inventory',
      // Stated here as well as in Risk Management because a vulnerability
      // exception is a risk acceptance, and the two Standards must expire it
      // on the same date. validateKnowledgeBase fails the load if they drift.
      riskAcceptanceMaxDuration: '12 months'
    },
    requirements: [
      { key: 'vm_process', title: 'Vulnerability management process',
        policy: 'A documented vulnerability management process shall be established covering discovery, classification, prioritisation, remediation, verification and reporting.',
        standard: 'The process shall define scope, scanning cadence, severity model, remediation service levels, exception handling and reporting lines. It shall cover infrastructure, endpoints, applications, containers, cloud workloads and network devices.',
        clauseOwners: ['vuln_specialist', 'vuln_specialist'],
        guidance: 'Define the severity model once and reference it everywhere; separate models in the standard and the tooling guarantee an inconsistency finding.',
        controlName: 'Vulnerability management process', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Reviewed annually', kpi: 'Process reviewed within the last 12 months (target: yes)',
        risk: 'Vulnerability handling is inconsistent and unmeasurable, so exposure cannot be demonstrated to be under control.',
        riskRating: 'high',
        evidence: ['Approved vulnerability management process document', 'Severity model and remediation service levels', 'Scope statement covering asset classes'],
        refs: { 'NCA-ECC': ['2-10-1', '2-10-3'], 'ISO-27001': ['A.8.8'], 'CIS-V8': ['7.1'], 'NIST-800-53': ['RA-5'], 'SAMA-CSF': ['3.17'] } },
      { key: 'vuln_scanning', title: 'Vulnerability discovery and scanning',
        policy: 'Technical vulnerabilities shall be identified through regular automated scanning of all in-scope assets.',
        standard: 'Internal scanning shall run {{internalScanFrequency}}, external perimeter scanning {{externalScanFrequency}}, and authenticated scanning {{authenticatedScanFrequency}}. Scan coverage shall reach {{scanCoverageTarget}}, reconciled against the asset inventory. Assets excluded from scanning shall be recorded with justification and a compensating control.',
        clauseOwners: ['vuln_specialist', 'vuln_specialist', 'grc_manager'],
        guidance: 'Reconcile scan targets to the asset register every cycle; coverage gaps almost always appear as assets the scanner never knew about rather than as failed scans.',
        controlName: 'Automated vulnerability scanning', controlType: 'detective', controlNature: 'technical',
        frequency: '{{internalScanFrequency}} internal, {{externalScanFrequency}} external',
        kpi: 'Scan coverage against the asset inventory (target: {{scanCoverageTarget}})',
        risk: 'Unscanned assets carry unknown exposure, and the reported vulnerability position understates real risk.',
        riskRating: 'high',
        evidence: ['Scan schedules and completion reports', 'Coverage reconciliation against the asset inventory', 'Exclusion register with compensating controls'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.8'], 'CIS-V8': ['7.5'], 'NIST-800-53': ['RA-5'], 'NIST-CSF': ['ID.RA-01'], 'NCA-CSCC': ['2-9'] } },
      { key: 'vuln_prioritisation', title: 'Risk-based prioritisation',
        policy: 'Vulnerabilities shall be prioritised on the basis of exploitability, asset criticality and exposure, not solely on the base severity score.',
        standard: 'Prioritisation shall combine the base severity score with known exploitation status, internet exposure, asset classification and the presence of compensating controls. Vulnerabilities on the national or international known-exploited catalogues shall be treated as Critical regardless of base score.',
        clauseOwners: ['vuln_specialist', 'vuln_specialist'],
        guidance: 'Known-exploited status is the single strongest predictor of real-world compromise; weight it above the numeric score.',
        controlName: 'Risk-based vulnerability prioritisation', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per scan cycle', kpi: '% of Critical findings reflecting known-exploited status within 24 hours of publication (target: 95%)',
        risk: 'Remediation effort is spent on high-scoring but unreachable findings while an actively exploited flaw remains open.',
        riskRating: 'high',
        evidence: ['Prioritisation model documentation', 'Sample findings showing applied risk factors', 'Known-exploited catalogue integration evidence'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.8'], 'CIS-V8': ['7.1'], 'NIST-800-53': ['RA-5'] } },
      { key: 'remediation_sla', title: 'Remediation service levels',
        policy: 'Identified vulnerabilities shall be remediated within timeframes commensurate with their assessed risk.',
        standard: 'Critical vulnerabilities shall be remediated within {{criticalRemediationSla}}, High within {{highRemediationSla}}, Medium within {{mediumRemediationSla}} and Low within {{lowRemediationSla}}, measured from the date of detection. Vulnerabilities confirmed as actively exploited shall be remediated within {{emergencyPatchSla}} under the emergency change process.',
        clauseOwners: ['system_owner', 'it_manager'],
        guidance: 'Measure from detection rather than from ticket creation; measuring from ticket creation hides the queueing delay that usually dominates.',
        controlName: 'Vulnerability remediation within defined service levels', controlType: 'corrective', controlNature: 'hybrid',
        frequency: 'Continuous', kpi: '% of Critical vulnerabilities remediated within {{criticalRemediationSla}} (target: 95%)',
        risk: 'Exploitable vulnerabilities remain open long enough for an attacker to weaponise and use them.',
        riskRating: 'critical',
        evidence: ['Remediation ageing report by severity', 'Change records evidencing patch deployment', 'Emergency patch records for actively exploited vulnerabilities'],
        refs: { 'NCA-ECC': ['2-10-3'], 'ISO-27001': ['A.8.8'], 'NIST-800-53': ['SI-2'], 'CIS-V8': ['7'], 'NIST-CSF': ['PR.PS-02'], 'ISO-27002': ['8.8'] } },
      { key: 'patch_management', title: 'Security patch management',
        policy: 'Security patches shall be assessed, tested and deployed in a controlled manner across all in-scope assets.',
        standard: 'Vendor security advisories shall be assessed for applicability within 5 business days of release. Patches shall be tested in a non-production environment before production deployment, except under emergency change where the risk of delay exceeds the risk of an untested patch. Deployment shall be tracked to completion and residual unpatched assets reported.',
        clauseOwners: ['vuln_specialist', 'it_manager', 'it_manager'],
        guidance: 'Maintain a documented standing exception for systems that cannot be patched, each with a named owner and a compensating control, rather than allowing them to sit as permanently overdue findings.',
        controlName: 'Security patch management', controlType: 'preventive', controlNature: 'technical',
        frequency: 'Monthly cycle with emergency provision', kpi: '% of in-scope assets at the current approved patch level (target: 95%)',
        risk: 'Known vulnerabilities with available fixes remain exploitable, which is the most common initial access vector.',
        riskRating: 'critical',
        evidence: ['Patch compliance report by asset class', 'Patch testing records', 'Standing exception register with compensating controls'],
        refs: { 'NCA-ECC': ['2-3-3', '2-10-3'], 'ISO-27001': ['A.8.8'], 'NIST-800-53': ['SI-2'], 'CIS-V8': ['7'], 'NCA-CCC': ['2-8'] } },
      { key: 'penetration_testing', title: 'Penetration testing',
        policy: 'Penetration testing shall be performed on internet-facing and critical internal systems to identify weaknesses that automated scanning does not detect.',
        standard: 'Penetration testing shall be conducted {{pentestFrequency}} by qualified, independent testers under an approved rules-of-engagement document. Findings shall be entered into the vulnerability register and remediated under the standard service levels, with retesting to confirm closure. Scope shall be set from the asset inventory rather than from what was tested last time, stating which internet-facing services, internal segments and applications are in and out of scope, with every exclusion justified. Testers shall be rotated or the provider changed periodically, and findings from the previous engagement shall be re-tested in the next one, so that a blind spot is not re-inherited each cycle.',
        clauseOwners: ['ciso', 'vuln_specialist', 'ciso', 'grc_manager'],
        guidance: 'Require retest evidence as part of the engagement scope; a report without retest leaves closure unverified.',
        controlName: 'Independent penetration testing', controlType: 'detective', controlNature: 'administrative',
        frequency: '{{pentestFrequency}}', kpi: '% of critical penetration test findings closed and retested within {{highRemediationSla}} (target: 90%)',
        risk: 'Logic flaws, chained weaknesses and configuration errors that scanners cannot detect remain exploitable.',
        riskRating: 'high',
        evidence: ['Penetration test reports and rules of engagement', 'Tester qualification evidence', 'Retest confirmation for closed findings'],
        refs: { 'NCA-ECC': ['2-11'], 'CIS-V8': ['18'], 'ISO-27001': ['A.8.8', 'A.8.29'], 'NIST-800-53': ['CA'], 'NCA-CSCC': ['2-10'] } },
      { key: 'vuln_exceptions', title: 'Vulnerability exceptions and risk acceptance',
        policy: 'Vulnerabilities that cannot be remediated within the defined service level shall be subject to formal, time-bound risk acceptance.',
        standard: 'Exception requests shall record the vulnerability, the reason remediation is not possible, the compensating controls in place, the residual risk rating and an expiry date not exceeding {{riskAcceptanceMaxDuration}}. Critical exceptions shall be approved under the acceptance authority set by the Risk Management Standard and recorded in the risk register.',
        clauseOwners: ['system_owner', 'ciso'],
        guidance: 'Expire exceptions automatically and require re-approval; open-ended exceptions become permanent by default.',
        controlName: 'Vulnerability exception management', controlType: 'directive', controlNature: 'administrative',
        frequency: 'Per exception, reviewed quarterly', kpi: 'Number of expired exceptions still in force (target: 0)',
        risk: 'Undocumented exceptions accumulate, so the reported remediation position no longer reflects real exposure.',
        riskRating: 'medium',
        evidence: ['Exception register with approvals and expiry dates', 'Compensating control evidence per exception', 'Risk register entries for accepted vulnerabilities'],
        refs: { 'ISO-27001': ['A.8.8', '6.1.3'], 'NCA-ECC': ['2-10-3', '1-5-2'], 'NIST-800-53': ['RA-5'] } },
      { key: 'vuln_reporting', title: 'Vulnerability reporting and metrics',
        policy: 'The vulnerability position shall be reported to management on a defined cycle, with trend analysis and escalation of overdue items.',
        standard: 'Reporting shall present open vulnerabilities by severity and age, service level compliance, coverage, exceptions in force, and trend over at least four prior periods. Overdue Critical and High vulnerabilities shall be escalated to the accountable System Owner and reported to the Cybersecurity Steering Committee.',
        clauseOwners: ['vuln_specialist', 'grc_manager'],
        guidance: 'Report ageing rather than raw counts; a falling count with rising average age is a deteriorating position that a count alone conceals.',
        controlName: 'Vulnerability management reporting', controlType: 'detective', controlNature: 'administrative',
        frequency: 'Monthly to management, quarterly to the Steering Committee',
        kpi: 'Average age of open Critical vulnerabilities (target: below {{criticalRemediationSla}})',
        risk: 'Management is unaware of accumulating exposure and does not release the resources needed to reduce it.',
        riskRating: 'medium',
        evidence: ['Monthly vulnerability reports', 'Steering Committee minutes recording the vulnerability position', 'Escalation records for overdue findings'],
        refs: { 'NCA-ECC': ['2-10-3', '1-8'], 'ISO-27001': ['9.1'], 'NIST-800-53': ['RA-5'] } }
    ],
    procedure: {
      purpose: 'To define how technical vulnerabilities are discovered, assessed, remediated and verified at {{orgName}}.',
      preconditions: ['The asset inventory is current and reconciled.', 'Scanning tooling is deployed with credentials for authenticated scanning.', 'Remediation service levels are approved and published.'],
      inputs: ['Automated scan results', 'Vendor security advisories', 'Penetration test findings', 'Threat intelligence on active exploitation'],
      steps: [
        { name: 'Discover', actor: 'Vulnerability Management Specialist', detail: 'Execute scheduled scans and reconcile coverage against the asset inventory to at least {{scanCoverageTarget}}.' },
        { name: 'Validate', actor: 'Vulnerability Management Specialist', detail: 'Remove false positives and confirm the finding is reachable and applicable in the specific environment.', decision: { question: 'Is the finding a confirmed, applicable vulnerability?', yes: 'Continue to Prioritise', no: 'Close as false positive with documented rationale' } },
        { name: 'Prioritise', actor: 'Vulnerability Management Specialist', detail: 'Assign severity combining base score, known-exploited status, exposure, asset classification and compensating controls.' },
        { name: 'Assign', actor: 'Cybersecurity GRC Manager', detail: 'Assign remediation to the accountable System Owner with a due date derived from the applicable service level.' },
        { name: 'Remediate', actor: 'System Owner / IT Manager', detail: 'Apply the patch, configuration change or mitigation through the Change Management process. Actively exploited vulnerabilities follow the emergency change path within {{emergencyPatchSla}}.', decision: { question: 'Can remediation be completed within the service level?', yes: 'Proceed to Verify', no: 'Raise a time-bound exception for approval' } },
        { name: 'Verify', actor: 'Vulnerability Management Specialist', detail: 'Re-scan or retest to confirm closure. A finding shall not be closed on the basis of an assertion that the fix was applied.', decision: { question: 'Does verification confirm remediation?', yes: 'Close the finding', no: 'Reopen and escalate to the System Owner' } },
        { name: 'Report', actor: 'Cybersecurity GRC Manager', detail: 'Report the vulnerability position, service level compliance, ageing and exceptions to management monthly and to the Steering Committee quarterly.' }
      ],
      outputs: ['Verified remediation of vulnerabilities', 'Current vulnerability register with ageing', 'Approved, time-bound exceptions', 'Management and committee reporting'],
      escalation: ['Critical vulnerabilities not remediated within {{criticalRemediationSla}} escalate to the CISO.', 'A vulnerability that misses the emergency remediation service level escalates to Executive Management.', 'Scan coverage below {{scanCoverageTarget}} escalates to the IT Manager for asset onboarding.', 'Evidence of active exploitation escalates immediately to the Incident Management process.'],
      records: ['Scan results and coverage reports (retained 2 years)', 'Remediation and verification records (retained 3 years)', 'Exception approvals (retained for the exception life plus 3 years)', 'Penetration test reports (retained 3 years)'],
      kpis: [{ name: 'Critical remediation compliance', target: '95% within {{criticalRemediationSla}}' }, { name: 'Scan coverage', target: '{{scanCoverageTarget}}' }, { name: 'Average age of open Critical findings', target: 'Below {{criticalRemediationSla}}' }, { name: 'Patch compliance', target: '95% of assets at current approved patch level' }]
    },
    roles: ['ciso', 'grc_manager', 'vuln_specialist', 'cyber_analyst', 'it_manager', 'system_owner', 'internal_auditor'],
    raciActivities: [
      { activity: 'Define and approve the Vulnerability Management Policy', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', vuln_specialist: 'C', cyber_analyst: 'C', it_manager: 'C', system_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Execute vulnerability scanning', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'I', vuln_specialist: 'R', cyber_analyst: 'C', it_manager: 'A', system_owner: 'I', internal_auditor: 'I' } },
      { activity: 'Validate findings and remove false positives', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'A', vuln_specialist: 'R', cyber_analyst: 'C', it_manager: 'C', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Prioritise vulnerabilities by risk', phase: 'Detect', assign: { ciso: 'I', grc_manager: 'A', vuln_specialist: 'R', cyber_analyst: 'C', it_manager: 'I', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Remediate vulnerabilities within service levels', phase: 'Protect', assign: { ciso: 'I', grc_manager: 'C', vuln_specialist: 'C', cyber_analyst: 'I', it_manager: 'R', system_owner: 'A', internal_auditor: 'I' } },
      { activity: 'Approve vulnerability exceptions', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', vuln_specialist: 'C', cyber_analyst: 'I', it_manager: 'C', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Verify remediation by re-scan', phase: 'Assure', assign: { ciso: 'I', grc_manager: 'A', vuln_specialist: 'R', cyber_analyst: 'C', it_manager: 'I', system_owner: 'I', internal_auditor: 'C' } },
      { activity: 'Commission penetration testing', phase: 'Assure', assign: { ciso: 'A', grc_manager: 'R', vuln_specialist: 'R', cyber_analyst: 'C', it_manager: 'C', system_owner: 'C', internal_auditor: 'I' } },
      { activity: 'Report the vulnerability position to management', phase: 'Govern', assign: { ciso: 'A', grc_manager: 'R', vuln_specialist: 'R', cyber_analyst: 'I', it_manager: 'I', system_owner: 'I', internal_auditor: 'C' } }
    ]
  }
};
